---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ./charts/

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: gateway-helm
    version: 1.6.1
    repo: oci://docker.io/envoyproxy
    valuesFile: values.yaml
    releaseName: envoy-gateway

resources:
  - ./templates/gateway.yaml
  - ./templates/certificate.yaml
