app-template:
    secrets:
        secret:
            enabled: ENC[AES256_GCM,data:EKXIiA==,iv:/4ye9XqJU6O8+lcbHT9FU2vDtscKxYBH0BSms/vY3GM=,tag:DpdXGbBeqQtDiN2iinjaxg==,type:bool]
            stringData:
                FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:nUEXy0gsDA==,iv:BvdCO4V7WGoUMOqg/R8KtPxTUThEd0IfvljLn8309lw=,tag:herRTdAAOKFOsnBBeYgp1Q==,type:str]
                FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:eaHcC7u5sw==,iv:Fij6tIZagwKJLWVosqQbLL/Ix18YgjKcakZeC9lmf/Q=,tag:jWYMzzYLGqs/3s3bUXTaBQ==,type:str]
                FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:cZE5L+s2LWpbTg==,iv:Gz4S36slPBqcAXSYjn0qYvSmWHIB05TLV7/1gDT7dp8=,tag:2h26Lxi2PnemO2LqpWi82A==,type:str]
                BAMBULABS_IP: ENC[AES256_GCM,data:mPjAN4ITbJhYJqVjgQ==,iv:RbhG+dvDhWbAb9IBZ8bwTQsYA9i8o1MQHA/Ja7SAB58=,tag:zKkhY8ft6JxnEVhsmC0+AQ==,type:str]
                BAMBULABS_USERNAME: ENC[AES256_GCM,data:0kN+cg==,iv:qm5O9TJzuWksqAWGjKEoN+QeJo5/sEuH2NDbMnBKVWs=,tag:cy10NiLvg0ushvErNtS4pQ==,type:str]
                BAMBULABS_PASSWORD: ENC[AES256_GCM,data:4t4+Tl4z35M=,iv:B49yaU8i/x+lDslYe9mER2UQbQT5x0IkV9SOtaY2KXg=,tag:hUZY71pwpE6GiEjwQTLfLQ==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwczZiZWhMb3cvaitwZDEy
            SjZnVGQyMXlrUHNBSFZ3ZXNqbnJ4dmgwSjB3CnEvcnArYnh3V0pDbzhqSGlQbWU1
            ZnhobVhCdUtYZEoxYXJzRjhGK2hGeUUKLS0tIFdPMDRIOThCTUxkNnZyb2hoTW4x
            RGE4U2VldytUN1ZRWW80bDVqeHhvdk0KY01Z5yz8nmDu5pzOYrLxlv7c1l0QgiVY
            zFPRQ4KoDlU6bm/FUEzcUzCYhZKS/R+xiqXuvtVqdfky9Hc7O7uhdg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpNzdiZThwRHp5OVdhYmRC
            NGZLbGxEV2tpRUdvRVZMTWJRV0pDcnpkcGcwCjlzSlVrOHZaaEQ4Q21FRlRyRVZl
            eVlNMm5DZW9wY3RFMjZMMEZpemp6ZGMKLS0tIDhyNmtjRHA4K0tPRVZDcUlDbUFP
            WjBGbVc4ODZhWTBrTTIxMUNFL1ZLWFkKwF8lrwCRqrv5TRrUViBGXvmbAMlhSfZH
            mbR0yCBwhIPjn8y8S08Gs1evXUfZIreBIpBmv5vfPrtglrlS75y9qg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5N0t2eHFLaGYvZ3U1ZXRY
            ZlhIcVJLNFZvdURyV2dRdHVobmpDT3JWV2xRCkRmLzJoUzFaQjBHNFFxU3B0UDlL
            bXIzblFaYVM3ZFFKNnRsZTNQdk5FTDgKLS0tIHhsa21YN3F5ZnFqTHFDTGEvcjVi
            cE5MRUUzU09Rd21uVVN4cFpnTXkrTHcKcvgHXZPcBbtvrqiiZ4UxuSRCiR/LHbdt
            mArso0ONF2aJb9uZBs0GTVSJZFddhswRhfhDUR8iQeEPMyZLCBVq/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdlc1c1BqcTdrNUZjRXcr
            L0RkQXNHdXBUTWZraHhEbkVTK0xvakZ3SlhJClNnY2k1ODFUYVg3ZXI4cDVkMWtS
            UmE1UWkwS2t5OWdrMFE1QXJiQktrLzgKLS0tIFh3Z2tta1VTNUJBK0ozdkhKd1dP
            bk85dkUzcm0wcDFGTHpSYmFsUzA4VWMKo9d+xv7skF0C4U54c6B53naYb5Sr5IQF
            W19fmVyL81J58h0kNdgCcu1B7PHk4FaZhOUeYUDTSzoyawK7Yi0nnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuSlV5bm52d3gvTWk4bUJU
            UGRjRDJucjZseXhKK05kcDRKdGRTRFVXUFZRClNOUzhTWVlsdmU2d3o0cktHcG45
            Zkxnclk5ekxRalk1OGoyK2g3cmxjcjQKLS0tIE1BVG9CM1BESHZHYXNhT3dUcHBQ
            Y3VwSXVQSENHQnAwY1Q0dWJWb0Faa00KTPUV462R0Y0o2qsrOLnewMs1/XmkRHYo
            Y3YJxg/Yg7v+NDINxzZUGU3rv1D9UtkTxfgQ8GEEiG7LAS6ntCrReQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyByRis2
            VDBTNjhDakZyM21qOGJlM2daUnpaUU84VmxPczhUb002eE1YT2dJCkd1emM4bnNj
            OUhoZE1MRzZxVm5EZStJT05aZ2JrbGxzQ25RNzhUc2czLzQKLS0tIFJBK3FwcGRY
            czVFR2toSHphQUpFa05DcVc5OXNKK3pkRVdEeGV6MUZRbTQKvAV9qivU5pdAQcYV
            CdcOR722ADyoqq2nTinkXEAvt7AwAzIzUH/46hoOrLlCz19f1HUrPFkXsWz/q8Le
            AnvV3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Rm8zbkVCKzl4Q29XZDNy
            dkN1OTZxcmVYWmoxVzE0VFRndVgvRjh0dTJjClRjUTNaemoweXZyUWZtTENTbkZI
            NWF2L1NZWUtpM0tjOXk4SE1aUmRIV28KLS0tIHBSRDUyQVFtR29US2Fuam5JWFU1
            aUtweHNITEhEUkQxck9VWVRpcWVORlUKlOYn0Scbr1at3Hx5ZyQkubGqlF1VRs/U
            6MlAPPfZvh/FLgGQWB5u28uL2yH9IcypA/ln4QQ3BBOiiqdjRS24oA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdnpiUFJHVUQyZks5VnNo
            U09hbzRUeWdPMm1tLytSN21MRmRxYmdsbTM4CmpqQjkxeGFvYXhGZytEUnVMaXQw
            ZSszVnliUFVIdDJ0NzhtWk13S0ROa0kKLS0tIHlSc0tkT0lRdFZlaGplbkNEUTVQ
            MU5HeFlFQ0t6azJCNS9jZTdoclE3OUUKMeU7lQUm/4XDui8Wv8vR5RexTg/ypcW8
            eMxGgxiYTE07OPtHfpGMtaIwLDSqBd/DjPIeDDLdzOkkxKebT6R9OQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOG5OVER4OUZZN3VtQ1dE
            dDlCdjlyd1VxNVVGVkRJQ3VVQUF5NzV6dm5RClkrc0NzTktybkZNMGExODhCR1c5
            NE5TV3pnaEtRYTBIRHNMdldNTVFZSmcKLS0tIFgzYVd5Uldtdnlodmd0c0JlRFl6
            SW9obGJkUFpwVWk2M0xXenRCdHlwOWMKCeysyVQ5d8MjnHuqgiZifydREwAv02zR
            YbVJaiZMZX58cs5LrxutcjBuqITarS5LfPKpCrWQpOiJ//xrP+LalA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0enZtUGs4ellueFFETTFO
            QjJ0anVQamFoeDZUeGN1Nmo3aVlNai9GL0UwCnI5a1lrWER0MUZ2Z0l2K2RyM2JN
            OTMyeWVkdWw1SWJrZ0gvZDJ2R0lrVFkKLS0tIHZhb1JBU3IvRFFsTENCQTV1eExn
            ZlgvRDBkeVVnWTVrdlNwUDF3cWNqWE0KVzpkU5KCqETPFlxOuleZzx0FmU84C6D8
            ikDdbboGdJuuTxYlwSqhj/0uCSWRfAx9d0urCz6r0doCY+mQ8PnE7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-30T07:50:38Z"
    mac: ENC[AES256_GCM,data:f3UQeFAWq1ILbasQPQftLj7HfBbv1p/jCCkov2g1l2OKIYMyTWU0tUUVpADzupqckbOa3/XX1kz5pEiR8jQmEpfHh+oVqHUZwwkiuilM/g5kd7dAPWXnEbvID7vJIKJqgfSrsjN0OwFTG3jXMTSRqhzNnCkyIn+FO2RNjnxHAlU=,iv:F8i6gg88eiViZXkwWeP5oskWzhKB7Yr7C5OzMdJfnws=,tag:Xwc6sUoxlanPRUHG9wVcbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
