---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: envoy-gateway

helmCharts:
  - name: gateway-helm
    version: 1.6.3
    repo: oci://docker.io/envoyproxy
    valuesFile: values.yaml
    releaseName: gateway

resources:
  - certificate.yaml
  - referencegrant.yaml
  - gateway.yaml
