---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: umami
spec:
  database: umami
  dropOnDelete: false
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: umami
spec:
  role: umami
  database: umami
  secretName: umami-db-secret
  privileges: OWNER
  secretTemplate:
    PORT: "{{ .Port }}"
    POSTGRES_URL_WITH_ARGS: postgresql://{{.Role}}:{{.Password}}@{{.Host}}/{{.Database}}?{{ "sslaccept=accept_invalid_certs" | mergeUriArgs }}
