---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goldilocks

helmCharts:
  - name: goldilocks
    version: 10.3.0
    repo: https://charts.fairwinds.com/stable
    valuesFile: values.yaml
    releaseName: goldilocks

resources:
  - ./secret.enc.yaml
  - ./httproute.yaml
