---
image:
  repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
  tag: v4.14.10

dashboard:
  flags:
    on-by-default: true
    enable-cost: false

controller:
  flags:
    on-by-default: true
