apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: stashapp-exporter
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:r5P8wQP6Im+an8Lxum/SUjA=,iv:bseanfKiiXsMNh5OuX4rVFkOpgq7HA7dc10D2JRi9PY=,tag:S7axZkQeQrwuRzvB0R9Zmg==,type:str]
          stringData:
            STASH_GRAPHQL_URL: ENC[AES256_GCM,data:gCLL8uPTDlCLavuAtZrexwZWD4JH2lfbx+w/is2i6Q==,iv:tG0J6pt6kESmUppTCkPnJejJP3ExgUGxoKV8l2o79Gk=,tag:jieOxsEuXtIoGdb8fEyPug==,type:str]
            STASH_API_KEY: ""
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb3puekNhNGczNkdMa0cr
            eTdYV1J2bStvODdPY0xBZHU3UmZ3bTJMK0hBCno3OUpMaFNjWDJMMk9KR3JYUjRU
            NjFCRUFJUmxDNFhVZ1BCUFhtQTZIcHcKLS0tIFZZMmljS1NIUWNMcE1hTm5URm5m
            NFpMR2pvNkMvdlNPbVJIeHBIQ2RaUXMK6tTcLu3ivwbhhRRgZzJO4y8CtWmR0Gl6
            ztdgHhsxN+OV+5NBOTLnhtVeuiQKyoeQPyP26MOeCynNB9ec+K1HBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQTdXbWxET3Azb3VBeDNI
            c0JkZGZoUlJrdTJsbmlIcEpjL3krUWIzUzN3Cjl2TTBiSUd6YmVKU2RJM1BCRGI2
            OWM5ZFo2TDdJRlE0aURtczVFNkVBTTgKLS0tIHpYS254dDk1QWRaV1NIU3oyVmtW
            b0FXUXBHWVNOL0NOZ1NEeVF6SStwVjQKvgEaCbGUdJFdhn5Ua6bEEjqaENEyBjNA
            +nkCkCrNnEpPvA1uFflfBnc4+8GTy41WJWWb3xY5hrk5KXp+ko+awQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cytDSDY0VEdGVTh3dmtB
            dUFjNjFvNkU5UXg1WGRyUEMrZUxjRVM0NTJjCmtuUVVkRlVHalhzRTZnZnJZanl1
            SWQ5QkV2ZmhZUVhPa3JpbFJZbE5zT00KLS0tIFhPODlSZDMzWm9Kci9CQnZPZEty
            eGtSbXJ5dys1czRsRUdJeGhzYnp4RjgKvmn6kJU8Fc0FuPjTc1yomiqt+qL84YDL
            CUZdBe9qhzswGJWkQ16+bqACBDym98tyZ7PNJ/TOb5H3yH0YtuAovg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb24rUGxNbjhiK0wrVk4v
            bUs5VlJRQVRhYWFFUEdOa1BFblRwZ3Y1aFZnCmNsUXRiaHIzTFZ4dTNNVmRpU3hH
            VHZQZ2ZvZHhpS3R1di9nTkQ4UVlDQWcKLS0tIGY3Y0VDUVFtVndiWjdsOEZOSVVO
            ZEM3UHpnMndHbFcvTUpXYk9zdlNVVlkKLhrW34hgA6WOj4eXfuniu2lv4eM2EB12
            1xzyyRZgHHQoKs4a6sltgAlUzz8c/bAZiewa3wLepDm7yXLmhfeRjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV1ZKbWpwN3o0T1pXN0dv
            TFRxcXFTekFlS3JCWU1NS01JSHJKaHAzOVdnCkhzcERXTG53RTlCS1RjOHJXeDF2
            cFg1T3p6L3haNlg0WTc1MkhnNk1JMTAKLS0tIFIyNFIyZ0g3VzZBQmZzam9nYW4z
            MWQ3ZkJ6SktOMFlmRFpKSHhubnYrNHMKzK9dk6jzeaRzsFZOd4MU7DBSYV3ZmJa2
            1gWIQbmyIRvO8ojXgvtliu3+7NC3prdbT0XL7hSn3L0iPytfWWnlKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyB6Q2JS
            anhqMUJSS1A5cmRycS91YXJsM0p6NkdJTTNKSndBd2xhdXhheGprCjRoUzZNZHY1
            Zm5DbGV1MnFIendFdktWZ2JrNCtiVnY1ak1aQllTK2lqZTAKLS0tIHpTY3BPbksw
            aVZPa05HOWZqWnBncjIvWE9OMENVaHFlR3o3eEFZL1N5K2MK1EppYjLznFeKq8O3
            7DkPWcKydCYspEkafqHzgYcfrZMfX9AZetjepSD/ehydM+yGh6AgYbQ61dss2B17
            HGTzGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeEVVSStpY1cxRldvR3Jh
            cGwxTThZczdaUk50V2pWWnpIVHAxVmI4K1RFCisvdDhFeTBYdUFrZzJWTWJ3MWlP
            ZXhCTnJzeFo2bTdMZVF3WmNUdG4wUWcKLS0tIEVJS2E2aVROU0F6NWZESzZvWCtU
            UkZpY3RxZzZWNG56VzZmelNqaUV1bnMK6im3EL/4eIWQLqSrnvmOzPDQxRoyX/bL
            oij8yFaJ/1knVbHEJpCSDi7qnJRMHXxvAUt5Whc7UU85MOYqWcoBZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVzRnRmhzSW5OdVV5Q21v
            Qm94a3RSemQzb2lwUm5BSU05TjhOdTJyamhBCm5KVjhmVHdDVXNDL2kvOUlmNC9F
            U0F0Z0dtbjcwdk9YYkE4Ym5UMmZ6VmMKLS0tIEpITkcwUElWZkFiRG96MGVmVUFU
            Y1pnbEZNTjFaOTR0Sm90b1l4NHRsN2cK2JTn8VXV6aazpYx/2+xxWpfINMijKvGs
            uJm0OQa+guepEbRI6LH3NZnsfWQkD7bGGRHqPHQfh0Rf1Y31yKXyaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMXlGMFBJUjhvQUpFb2lu
            dG5QaXYzTW1XK00vOWxxa2Y3YlRCMXNUcGhNCnJCMU5BTExtR3BIckFxUHhVWGgr
            TmdzZW5tdlhNZUtuc0JVaWVkYS8zT1kKLS0tIHoyYjV1Vm8yZ1laSXRrWlZzWERL
            YlBETUZRK1JXK0hqS0VpMklHdFhBYk0KYmaX0AB9lePuwen5isF8Y1I9DHQVfDAf
            kUP9heMsFLYRxHtQqHA+5kaQnr4vdRlbfus6TxY5Kk4cc37apjQEmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOGxTT2E4ZTQ3NjVrK1hD
            K3VFRjVUc1JqYTJETzRsOFFaYTZuK1ppMDNJClNzdUYwbTNYMjA0R3pOc0t0dFFm
            NEZSd2FiVE5pVUNkZUEzTzNaVk9WRkUKLS0tIDZwSHdrVmc2TVNiZFpGNElxbjUy
            aDJEVUlRdjMxZXBCY3A4QU5oRS85V2MK9YAfXWrDs+n70d8LKkzc/u4iKEotzTWZ
            fLTu5655nLcryYDc8BHrTgnEX7l304svtp0wHCdpdySH+OfEYQhepQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T07:57:03Z"
    mac: ENC[AES256_GCM,data:xPVJ6mA2csj2DzsrmlkOQRwFEpK13iWxthpOeC0bfg9/ze5i975xMR6XqcDSk7H1H460MmhpE/n4n1fd6h+r7z/k8sXPlh+23hAd+e9wITnAbXxTCvH3/FXwMBTf/W7T2k2oYP1jB4FhBsUjILlH2mvZDc8tOQd4xR/e8pyiJZA=,iv:SxTc2YxbabLYApYeV3YuXsOo3O69b1v8shLER3m4MxA=,tag:W34ZQyWWkUWkyIlcFcuj7g==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
