apiVersion: v2
name: prometheus-operator-crds
description: prometheus-operator-crds
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: prometheus-operator-crds
  version: 25.0.1
  repository: https://prometheus-community.github.io/helm-charts

maintainers:
  - name: halkeye
    url: https://www.gavinmogan.com
    email: helm@gavinmogan.com
