---
# https://github.com/rommapp/romm/blob/master/examples/config.example.yml
exclude:
  roms:
    single_file:
      # Exclude matched file names to be scanned.
      # Supports unix filename pattern matching
      # Can also exclude files by extension
      names: # ['info.txt', '._*', '*.nfo']
        - '@eaDir'
        - '#recycle'

    # Multi files games section
    # Will apply to files that are in sub-folders (multi-disc roms, games with updates, DLC, patches, etc.)
    multi_file:
      # Exclude matched 'folder' names to be scanned (RomM identifies folders as multi file games)
      names:
        - '@eaDir'
        - '#recycle'
