apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../charts/whoami/

patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: whoami
    patch: |-
      - op: replace
        path: /spec/hostnames
        value: [whoami-h.g4v.dev]
  - target:
      group: gateway.envoyproxy.io
      version: v1alpha1
      kind: SecurityPolicy
      name: whoami-oidc
    patch: |-
      - op: replace
        path: /spec/oidc/redirectURL
        value: https://whoami-h.g4v.dev/oauth2/callback
