apiVersion: v2
name: postfix-mailgun-relay
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: mail
  version: 5.1.0
  repository: https://bokysan.github.io/docker-postfix
maintainers:
  - name: halkeye
    url: https://www.gavinmogan.com
    email: helm@gavinmogan.com
