---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vpa

helmCharts:
  - name: vpa
    version: 4.10.1
    repo: https://charts.fairwinds.com/stable
    valuesFile: values.yaml
    releaseName: vpa
