---
# only used for goldilocks right now, so only the recommender is needed
recommender:
  enabled: true
  image:
    repository: registry.k8s.io/autoscaling/vpa-recommender
    tag: 1.6.0
updater:
  enabled: false
admissionController:
  enabled: true
  image:
    repository: registry.k8s.io/autoscaling/vpa-admission-controller
    tag: 1.6.0
metrics-server:
  enabled: false
