config:
  address: 172.16.10.50

env:
  vip_arp: "true"
  lb_enable: "true"
  lb_port: "6443"
  vip_subnet: "32"
  cp_enable: "true"
  svc_enable: "true"
  svc_election: "true"
  vip_leaderelection: "true"
  prometheus_server: ":2112"

envValueFrom:
  vip_nodename:
    fieldRef:
      apiVersion: v1
      fieldPath: spec.nodeName

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
