apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: nebula-sync-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:NWwT4JPaURJ95DIGB8o0iTVJ,iv:MvP0upz7h+PzhffagZgyOTxTYGZBr75QBgHZ+05U0fw=,tag:prolzmr7JMcU7UDqHcSO0A==,type:str]
          stringData:
            PRIMARY: ENC[AES256_GCM,data:7M1i0SqcWWJLsRYhYsHVU3ultAPkdFDarfwFXa9jZ+zXZBLqLVQ2Ka7rwQ==,iv:8x8A9IKxCsj5OBPHeS70V0Bj/cb+mkHBskdTVyhIVqQ=,tag:0ChF8pDOqF1mtkXhrp9IAg==,type:str]
            REPLICAS: ENC[AES256_GCM,data:kj7l6xcgKiGj0n2m9rDMKwL7mVUlbimLeG57txliVH0kYtfobhoFf7i6,iv:iVPb5HMlnCUuIpw68hS3zQuYe4ogDTeKTWRlhcpoXME=,tag:g8Cp6tB4Eac9EsvyBkanxw==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicEw0TlF4ekZvYy9ncnJu
            ZkZIV2lLSk92Y09oRVNPU3pMZC9nMzFyekNNCnBnRVZBT2cxcXREVGdHMmRrdFJ1
            UDhPL0VlaXVOTEpuTTVGLzErNWRGOFEKLS0tIHByUEZTbUJNcnA2amltck1zWWp4
            M01Cbkg3SnF0OTVZWG9QS1c3bENNRDQKq9ThB0G9dZOHiyJHZPvy6P41qDpa5xNe
            oW7tRVyoxjlJqsJtg4vVeKsnQQEfQZ1zN/J0jrs1cjqzxLPMYKDi0w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd21yL1NsZVZyVlkweTJM
            aE5wOGNvWTNJMWdYaTJYNnRmQi9WTXBEbW5vCkJrNHhzVTJMbnVEUlU2MVRYbVgz
            WlBFRkNwa3pDQVRsbWRWODF1VUtVem8KLS0tIFQvaDZBYy9kczh0MllOMi94YWZP
            MHI2WkFNMEYzWHRSa0xFeTBPNHlIL0UKGw8Q/ebh38HNkglyKKVFVzfSbZvvM/UC
            Fsox9urJaj3mWoFRgW8hy1MtNpNgYSAD09w6I2mbrDS+Xpp0FHgX5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMV096QVdVNGtlazNiQjlq
            VEIrUE9TVEdRZ0pVUURmZ2phSXFxcldNblJvCkUzQkxMRnBkRUo3N0pKVzhSRmY3
            RGF5NjlBaG4vWkxIRHZtVlVOWXNQU2sKLS0tIGVUak9RWEFuSXVabkhxb0h5MWNq
            L0MrNjA1NlFWQW1KQ0Fuek10VC84bncKAXctf7jFJ7RkpzDadG20QLv7GrZaQZva
            6gXSlT05EUm/kGYKErpnegOlLHH7GvuE/vVn1SCV9hfqdUfhY7MG1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYjJJVFNSZDJjZ2FyZitW
            eXNicHMzYTIzK1lvQnNTVGV0dXNraEtkdFFJCjZqY3VCQ1FTMGYzZmxObStDblZD
            OCtIdHBZOFNUbHp0TFBzMkNpSG85M3MKLS0tIHVrSFdLN2Z0b3duTENxZXVQZzBL
            c0NrbEQ4RjJ3SzRXZ1ZEUzRkeWluQnMKAyc6HwOELfkhD6hJY63GAMjR+gIpJ5b8
            UJ6HL0bwZBqPPTsdCYVgFLs1CsilSrZirzKrsFmyyn7MryPMLqA+Wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjT3EvZE9lcmZEa1JVZ3BV
            TzkxL05zbzFsc1Azeld2YkdUR0lCcVJpeG1JCjVsUDdEaFREMGFpemFWd21EUzEy
            b1dPNlQwakVIWmNSNzJsblZsRExxNjAKLS0tIFdCR09xeVc5Uk1oVkY0MVIzZ3NP
            SkNNVUxkeldpTGVvbW1Hd0VVQWZXaU0K8cXD1oz8Nq++i2+TkksbplqRj1PHJYyu
            0Q55RQWQvhxLjgL4GGrM3zAYPT+7QQL2ZC8Ypou8Q837py9lQ8gUGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBGdVBY
            Y2pHTGRSYzdnUGpoMkVhTzl2Yzl5RU1uTE0xL3JBWno5VTVOT21ZClU2M3k2TVUy
            cUpSb2xHTUZ4Z3VJVUZtdys2bDhaaHR6TEJscHV3VFJDZkEKLS0tIDVaMFNBMm5p
            NktlVVZHRHh4Sml2UHA0N1Q4dEFzdEFsOUx4bUJFQWNxTDgKrHh4uyFfrL1pTDaA
            HwKkAIhAgEer7H6L/VEai+3/BjmZKGl56rPYapRPixiH6A50w6Ts7izpybKPvDMA
            4OUg4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAza2V5VDdMd3pxTy9mbG5Z
            eUFEUzMyS2RxSUsvWS9KWlNyS3BtdmR1YUMwCmRkN3N6OFZnZVczM216cTVBV1JZ
            MEx4YlM4TmpEV0lRdFNibWNvWkhpaDgKLS0tIG5Ddno5dzQvYkt2YVMwekdqbjVR
            V1RTa3VRSWJ2UkVnUnp0cGtVWW5zOXcK3tKnKg8+C2icoFNi16t5e9kV76jE14hu
            s3UwcHPbG3S2lQCbSfELV+fjU6M1PHj+X8+wTU8pqisMW91Cs1XQYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUFRNMHRucVU3bnFBT2dy
            d1RJcEIrZzY2VldJZzlMcitodG5keThDdkNnClFsM0w5RFpYMmc4VTJHczc2ckpF
            eVdsdUFZUHpqbXhLWVpDNTZ2N2Era2sKLS0tIGZGcVlpZFh6d2ZjZzJXWG9kejVJ
            THlCM0wxRGYxak14TW9QTWswdFpEcmcK3mh/Q8vy7IgiQNqwyY0E5ALjha/2IzjF
            NKzMFMyADn7wOnV4WqwP7RIHZBD8AUEv1LbiresAoaF/nJZlSin6EQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia3lEM3VqWDdFYUVxRkhr
            YlpwSjdZMkNoK1JVRlAxcjAvSDVSSWJCb1dvCjMzYi81aWFnSVFwZCt2SFlCdXVQ
            SU5wZTJIYjNBMVhuN2kxdjlBZHBPQUUKLS0tIHZiV3VZT0s3ZW9UcUJuZU1hMHdx
            ZzhEOW52WmY1UzB0NHY0Y0dXTUYwVTQKNFNUJfDXB0WgF7kg0vtPPcqgDjyUmN9b
            44ZZxSzGjZN0We2l+IqOgQm7UhD0HcK+VjE64+hDX1M4u286OBzB7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZlQ2bUxObStLSmNuNGh6
            bVpRYktMLzNEZWpkR3F1T25Wb0c3T05ZY0VFCnZOL3BCTGRZUHhQb1lKM0V5ZHhv
            dlZJZjJCQXpvT2FSQnNlL25xemNFODgKLS0tIEdqTVBTR2RML25GSFhHb3IzdStO
            MVlUUVhURDFhbitheGpCZUVZcGJkZWcKYx/TI/Pt4OH2t2b2v/M5SrZ21Gp1frDC
            OUCY/aT6GuGSE9RpDFLLLsBdSRQ39709aRL8bJYuXtGIBbh/Uuby4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T03:51:19Z"
    mac: ENC[AES256_GCM,data:RDExbCVHdrmipiBCsiSiNOFgxQz4JmNai+MPCjznxLv8Zi6K/dxQYRDfu0keLMaRUE3FcXRjaJkdc7asSdm+HC9e6EFqqC/IcGnX9hBXu6UuWmNOOG5JeREH3NemE5WrlRRohzL5Ks8S9ysp5h+wvgDCaJnJrYSgy3yT7otTFUI=,iv:Ft77ymxCNINI5ZmBCnyJDU90HWmksdXY9KP7CV9sRn4=,tag:WEnmcHaLlh/TML5/QM5FyQ==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
