apiVersion: v2
name: node-feature-discovery
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: node-feature-discovery
  version: 0.18.2
  repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
maintainers:
  - name: halkeye
    url: https://www.gavinmogan.com
    email: helm@gavinmogan.com
