---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral-device
spec:
  rules:
    - # Google Coral USB Accelerator
      name: google.coral
      labels:
        google.feature.node.kubernetes.io/coral: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["1a6e", "18d1"] }
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: gpu-device
spec:
  rules:
    - name: amd-phoenix
      labels:
        amd-phoenix.feature.node.kubernetes.io/gpu: "true"
        feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0300"] }
            vendor: { op: In, value: ["1002"] }
            device: { op: In, value: ["15bf"] }
    - name: amd-halo
      labels:
        amd-halo.feature.node.kubernetes.io/gpu: "true"
        feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0380"] }
            vendor: { op: In, value: ["1002"] }
            device: { op: In, value: ["1586"] }
