---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: google-coral-device
spec:
  rules:
    - # Google Coral USB Accelerator
      name: google.coral
      labels:
        google.feature.node.kubernetes.io/coral: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["1a6e", "18d1"] }
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: gpu-device
spec:
  rules:
    - # Intel UHD Graphics 630
      name: intel.gpu
      labels:
        intel.feature.node.kubernetes.io/gpu: "true"
        feature.node.kubernetes.io/gpu: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: { op: In, value: ["0300", "0380"] }
            vendor: { op: In, value: ["8086", "1002"] }
            device: { op: In, value: ["15bf"] } # Phoenix1
    # - # Strix Halo [Radeon Graphics / Radeon 8050S Graphics / Radeon 8060S Graphics
    #   name: amd.gpu
    #   labels:
    #     amd.feature.node.kubernetes.io/gpu: "true"
    #     feature.node.kubernetes.io/gpu: "true"
    #   matchFeatures:
    #     - feature: pci.device
    #       matchExpressions:
    #         class: { op: In, value: ["0300", "0380"] }
    #         vendor: { op: In, value: ["1002"] }
    #         device: { op: In, value: ["1586"] }
