---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: not-the-plants

helmCharts:
  - name: app-template
    version: 4.6.2
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
    releaseName: not-the-plants

resources:
  - ./secret.enc.yaml
