apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: pihole-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:RXPsIPskVBQFnm4fvfU=,iv:TBqI8/EA9fyk/xHeHLBeP8QKUkZynRoFmN+6xdQpQWQ=,tag:v/jM6M+DSHP1MqNRWurR0w==,type:str]
          stringData:
            password: ENC[AES256_GCM,data:thwFbRY8Xqx5ZCOklWG9FaCpKYp4RM5n,iv:FxEeSQ/YAYOu0HTPWWb1B0DM7rFQ3sOJGo0CURAwswU=,tag:jVpu5JY2fcQLEPOtA3kPtg==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4c1ZkZTA5and0czVQbS9j
            WU5NR0tXcHpEZW84b1hrTXp3S3VvUFBmdlJVCldmNzFXWWlpcDQ0RUtqMlV2bWV0
            RWxGUkZxZWRnOHdoUlc4MFNKWlI3YjQKLS0tIHU3cFIzNm1UU0I1azVwYy9Qc24v
            WURRRGFhdjdnZS82WU5SMjJSc2U2d3MKvTHdl2w+h0xH6oQ8/LesGmDsjUyw8AX5
            JudEuDlc5hY8gByAIr55QQ8aqc/TQPT4BdxlQZP21/+4wWFsViC2tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTStNSUFDWFBma1lqT2Zr
            SW5tM24yaGJDOVFMbVZocFdLeXNFYnZJSENrCkFKajhORW91dUp4U3lDaEVsR2l1
            K2JhZHVHUjl6TGhYblBXTGdhWEdSeUUKLS0tIElIYjhmb3NoTG9UV2I1V0M2NlNr
            OU9LKytXY2h0b3VlcW1mdmo3RU9LUWcKObK7dOY5aNrc4ILerH4NNtpLchgsba05
            mQfhsH/JQr6Z478FUhDkjgM3M7XLJQTdylDh8FnJJ1Ptk87DVFjTow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eDNIRmMraFdqR1c2dGxt
            aFUyckwyWDhuODhUcGtIcjlpeVBNVFUwN0RzCnZTS3NlYWJYQXUzdkJ1YVdUOWRG
            bEdWVGZYc1JSL1RyVWsvWWhvYVlMcTAKLS0tIENwSVBmcUtSZSsrRDVPNDQrNGpJ
            a0FBY054dGtVYm16cUJzNXo2ZmRKK1kKBue0RKl3n9WECLI4PdhOdXNfErkT7JX3
            R/vrbY7aTSpFhjPsRKT4QrKB+EzfIOs2D2ghp5degN4nxQgHoQoYLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNUNETHVyenlWamVwQTdZ
            Wmx3UGxndjdrZ3U0SXB0RE5BWWRlK3c3NkJZCko1b0JCbklFblIwV2tHc293OUpM
            L0pRM1NydUpPbk9OY21UZWROdGx5aWcKLS0tIElmVFpBa1lOZUNLYzIwSG12Wjln
            ZTFDTktPeGJRWWdBYWdzUFdhd09GUEkKHwPgPaC2fjACVgxy/MLpWHFc2CfVqr5q
            w+qyaMvj3wDzrRc/JYy4cwiBOXxvsXprePetsd3K+bHt7z4DnDhtGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubXVwUVkwVjRNNE1zNUlF
            M3BUaHFJbEZUUUdoNnhlMTRuZVFnbjl2a1VBCkpzWUxoTW1DQ2luVFg2UWkwaDRx
            d3k5SU5KNGgxZCs0ajVaK04vdUU0MncKLS0tIFUvS0EvTE85c2hERzVIRzhpOFEz
            TkpkbTQ5bTV4K05PdEZ1cHlFL05MSk0KgfPg/bVFYh0aj9n9DEplsFcgEehtyqZ+
            PcxGy8nWOy8v3PwClrzcf6XiPlbpCSUeeW8GeI8LQ8BfX+cqo5KLcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBDMWdP
            WmxuR1hUQXRkcUZIZ0o5VjU1MTVHdHNCR3VmZ0JQejZXTTR6QkdjCmRCM3hKdUQ4
            M3IxMVlpL3Z6ekhQMFZ4bm12NmVEQTRzVklwZHV5MUl4dUkKLS0tIHl0Q2JNMmtt
            Yk0rUFJHakdKcy9xV1Z0MjFGV1VGMkphdXRxZW1hK0RFcHcKHdEotFKDG+wvas43
            4BiBFWG7ODql3z0yMTKVV1/qV2/57+PKm9m633UyjrNwhNSMhHmbpNUzsWL1R+4V
            /h6t6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d2dFU1MxQjl3VmpBSWJz
            cDI1c1hRWjBDR0g1TlozRU54aE5VL0dmcEY0CnJxWWlVZmRVRHJwd0NrZWFmSnVj
            VFA0UkYzQVlDT2xlNmJ5ckU1b3RqdWsKLS0tIHBNaGJUV3hwams5NFFoTVAxZEFT
            eFhxemJKaEdjY0xkZTJoT3RjalQzT0UKczhWeQV2QGxbeyFqjIz0MtDzNzFm3HxS
            k2NYZJHvxPH+gfWKpX1H8yaooDeCd55gfDXYX191rhigLwgApXIqCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5SXRSc2QvbnplNmhIaTY5
            QWlpUlNDRTk0NGVFZUJXMnVrRHJQUTJVaGtRCncxWEtqLzlpaXBST0hFU2hPM0JO
            TWhkbnp2bDhNYUxZV0tHK050Mmt2UDgKLS0tIGpOT2tJL3gweE1jOXV6YXFpSnUr
            ZnZuNndSWGF5ZXg1TThhSkp1R055RWcKgf1yPa5pmgoG4IdWc4m0A/waudY0TBHn
            aX5XsvbDyhm5r4zC66Sx/wX7V21arsRuUbGX99hlghWJO3ffm1eScQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU080WXo2Ukg4Ti9kNk5i
            WWtNOHBDNnowWjlscTFkN3RpTzlaaGs4aTBjCitpRG1Pa2lHMERJWnI5ZzJXb0g2
            TGhTVzQ1dVczaWhFZ1ZpM0VBY1B0MmMKLS0tIGRhZ1RIdjBjMXQybFMrellHakZq
            a085OGhKaWw1cWtuSDl5R2UzbVBMQk0Khsa/1HMkJD+bE6NREy2WF4/y1OmG8IlF
            B7selZGjjJ+pJHA3Zc5Zob2Q4/9rW7vZNn924SaIKBQrt3beuFWssA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzNTdubmFtRTArSnhjMjdS
            RUdvRGZpUDFManM0OUZrTkg0NmxWYkFSMkY0Ci93ck9TNm5ZdCtXd3NxMkpMZ2E2
            UkhjRlBUY0prL3RRdTlGR0dXMllnalEKLS0tIEVIRU4ybk9Gc25iSTl2UUlvaFVj
            Mk1nN0l6eXdPc3U0ZlcvbTAvei9Yd0EKGjP4vqABZKD1wAxtTF8RrKFvRTELgIMg
            R+LNuPLmpwpc1yMh0aNO0LdBRV47UBWzYPHA/VyEFjMnP6I7OtIq9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T15:41:12Z"
    mac: ENC[AES256_GCM,data:Ydw7ST8ZgdPi6ZTGp3czKdjnDy0xNZWOe8pxMMJSiP0yAdK0EjIu2GthR+ajq9wct0vcWIGFG2KW2kKP9tDH8YA8KFGgTVmcIAJns8lM2py32EUYaPXHH+fdYXr7+LgtGy2wT0/gIEeXMkge0msXmnLl+AZoMg+OnHG9BNy72+Y=,iv:FF3ShUhLVa07cfp7Y16O6rjoKmN0twNf4gPkXfI9Law=,tag:bn17BtOytCv4JCk56Utxpg==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
