dnsmasq:
  customDnsEntries:
    - filter-rr=ANY,HTTPS,AAAA
    - server=/dhcp.home/172.16.10.1
    - server=/10.16.172.in-addr.arpa/172.16.10.1
    - address=/nas.g4v.dev/172.16.10.10
    - address=/odin.gavinmogan.com/172.16.10.2
    - address=/synology.dhcp.home/172.16.10.10
    - address=/mqtt.int.g4v.dev/172.16.10.107
    - address=/ubnt/68.183.248.183
    - address=/unifi/68.183.248.183

persistentVolumeClaim:
  enabled: true
  size: '1G'

serviceTCP:
  loadBalancerIP: 172.16.10.204
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

serviceUDP:
  loadBalancerIP: 172.16.10.204
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

admin:
  existingSecret: pihole-secrets

doh:
  enabled: true

ingress:
  enabled: true
  hosts:
    - pihole.g4v.dev
