# dnsmasq:
#   customDnsEntries:
#     - filter-rr=ANY,HTTPS,AAAA
#     - server=/dhcp.home/172.16.10.1
#     - server=/10.16.172.in-addr.arpa/172.16.10.1
#     - address=/nas.g4v.dev/172.16.10.10
#     - address=/odin.gavinmogan.com/172.16.10.2
#     - address=/synology.dhcp.home/172.16.10.10
#     - address=/mqtt.int.g4v.dev/172.16.10.107
#     - address=/ubnt/68.183.248.183
#     - address=/unifi/68.183.248.183

persistentVolumeClaim:
  enabled: true
  size: '1G'

serviceDns:
  type: LoadBalancer
  loadBalancerIP: 172.16.10.211
  mixedService: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "dns.g4v.dev"
    kube-vip.io/loadbalancerIPs: 172.16.10.211

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

admin:
  enabled: true
  existingSecret: pihole-secrets

doh:
  enabled: true

ingress:
  enabled: true
  hosts:
    - pihole.g4v.dev
