devices:
  - enp1s0
  - enp2s0
  - enx000ec6ab18ca
bgpControlPlane:
  enabled: true
# endpointRoutes:
#   enabled: true
ciliumEndpointSlice:
  enabled: true
bandwidthManager:
  enabled: true
  bbr: true
bpf:
  masquerade: true
# cgroup:
#   hostRoot: /sys/fs/cgroup
#   autoMount:
#     enabled: false
# cni:
#   exclusive: false
# enableIPv4BIGTCP: true

gatewayAPI:
  enabled: true

externalIPs:
  enabled: true

# l7Proxy: true
# loadBalancer:
#   algorithm: maglev
#   mode: dsr
#   l7:
#     backend: envoy
# ipam:
#   mode: kubernetes
routingMode: native
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8s:
  requireIPv4PodCIDR: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 6444
# k8sServiceHost: 172.16.10.50
# k8sServicePort: 6443
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
localRedirectPolicy: true
operator:
  rollOutPods: true
prometheus:
  enabled: true
rollOutCiliumPods: true
# securityContext:
#   privileged: true
#   capabilities:
#     ciliumAgent:
#       - PERFMON
#       - BPF
#       - CHOWN
#       - KILL
#       - NET_ADMIN
#       - NET_RAW
#       - IPC_LOCK
#       - SYS_ADMIN
#       - SYS_RESOURCE
#       - DAC_OVERRIDE
#       - FOWNER
#       - SETGID
#       - SETUID
#     cleanCiliumState:
#       - NET_ADMIN
#       - SYS_ADMIN
#       - SYS_RESOURCE


hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http
  relay:
    enabled: true
    rollOutPods: true
  ui:
    enabled: true
    ingress:
      # using gateway api
      enabled: false
    rollOutPods: true
