---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: "vikunja"
spec:
  role: "vikunja"
  database: "vikunja"
  secretName: "vikunja-db-secret"
  privileges: OWNER
---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: "vikunja"
spec:
  database: "vikunja"
  dropOnDelete: false
