apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: vikunja-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:/2l+JqOItlqE2vVhegw=,iv:l26qb6z1ynGe1akA3yBdwpWiKQmWXxPcgxvrrhcDBy8=,tag:rkgXlZd81ANTxWRIPsWOmQ==,type:str]
          stringData:
            CLIENTSECRET: ENC[AES256_GCM,data:GoFrbNf2b3d8uZM6w1ig5CeEaXquysPrZVNTmbnkf9JmOmFea6AcUOzqmy4v4AmOnUXcjCGIEFtF+JfPgebzWXJA0eysHACC0EZU4tF7bKQLgviZDfG9flVNhLzFNTTfGdG54Tsxh7G3sBzbKqsVEto5QZ7nE33/aPHx/KqTVUw=,iv:+JANH8zYVswLlKdzzA+L+qmSEplyYEdJ7NavCDSzMUQ=,tag:0ob5zFKbwzgGQRCWPeX3Cg==,type:str]
            VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:IWMyeXSC7Pd8Bay2BMGOjJ9aHg8k+xchJvi9HfzpDQjHfQRQ0kBtjQzoYA7VOw2jIDfkFBHc/3xKpG6OxL1CuVgje7hE+ohSI8q73zoc0BR2d95eNTDR/kdg18q2IcuJ6vR64ZyyCfmpo4QdK7s7Ot4V2XYdDOkxN+Fydk085RKLOMD0WKJltfa7Jg2AmsmB96VHtpWjARLfgtdXny7h/II3H53lw1/Jiiwb17uMmmNEYcVF2zbUJr07kAVj6kz2GpfXr/kSapFudXL7GbvA9rhUs8nw9zI+rc+GvWbJWf6mWBNYRWWNA1GuQmQ3csB2YkTCjhhw/4sslmGUxRkAxFkyHlU8AzuPZtHGa2/GtcAWKdEyRGutCIGGdqsvWbII3bsleaCnk1t6Xtu+00GrURpm1jysN0wO2jQniFWNH5phBCVAbIjZZhpGZ5/ZYepYfzOuQX/6LrgMHN38pYYPsQWJ0TrAYO87XzP06MZpIU4JhfqHkGfg/V7m/sFoqJ7Upb6botPWKmrHyaCJZ6TPZDTdx1wmpmmbad21AD9SGHYRir8XLaNtUtxZOFK6rZFE5WSXqPJO3T2By4yum0MDuf6GG+E/iZyTkKaxCOCSqJ+YaqSn1mm3CvTd5FkxEpeVR0osgrsMcU/sCWEulq0sIc7s2sadlJJVPHze6LSrQZU=,iv:teDeWW8TXl6kUWG9NGGUGrjO99By9t4mT7NNE6syux8=,tag:FWqkhL4ScFmsYVUSJzMXHQ==,type:str]
            VIKUNJA_METRICS_USERNAME: ENC[AES256_GCM,data:NsHcf+Poak5iwUNISYOZLE3QsfNOykv1pyP6/ffEOFWspCFHdHB/tnA2iMxbFLOejKX5mbNxbchI+l3sOnrkRA==,iv:WpWPJGZYFVf5t3Xcw+QAAPOyMs2NZZsMe7lUq6I93do=,tag:8OICMvD3c1UfC6R1pRRgzg==,type:str]
            VIKUNJA_METRICS_PASSWORD: ENC[AES256_GCM,data:m74JH0s6f/nWXLjT9yPwtcPuTTaZt5xuOR0o9Bn+K1oM1bNK5Di2KjH4eNXKj4uNq5ngr8YqeVSI618XL6OD5A==,iv:LaO9h67Exv0khTwmC3xpv+TMfOvJPjCjfdueOJGslbA=,tag:p+3NwufRYKNiW6KeKVa7cw==,type:str]
            VIKUNJA_MIGRATION_TODOIST_ENABLE: ENC[AES256_GCM,data:Kg==,iv:lueSBVDERmHZaeMVDB+P5dUsns9azui+G43X7285lB8=,tag:bY8fH8931DLkpVcSATwk3w==,type:int]
            VIKUNJA_MIGRATION_TODOIST_CLIENTID: ENC[AES256_GCM,data:D0pq9I7esG/sV7ww7DXsUum6+rFiiu4AEJXxJgpOdDs=,iv:cTEjBT/A4BGSRJFtZi2uFRkO8aWm4qDIccyLg2MnI9U=,tag:7hLm/SMv3rAQYLb2OPncLA==,type:str]
            VIKUNJA_MIGRATION_TODOIST_CLIENTSECRET: ENC[AES256_GCM,data:rgl+zxdC67+DKsSVFV/DFW+HOl2SAHOL6Re6dBDE1c4=,iv:98qdVLgZS99hPNqjS0zPJASOAPvr/rmhIt+Jm/o86NE=,tag:+MDXNCMcU0KB8F1fB9NRZQ==,type:str]
            VIKUNJA_MIGRATION_TODOIST_REDIRECTURL: ENC[AES256_GCM,data:9QTVsRfyDbwNUvQvYbcz2GmFPXYa44e/D6tJv+2aLK/FBnbxQg==,iv:MacGO9Re7SNm2SENouYo4rIaLS6yR3Mz/YrFYi/2UHs=,tag:55GpSlKV375+mTzW0yc57g==,type:str]
            VIKUNJA_FILES_S3_ACCESSKEY: ENC[AES256_GCM,data:WD1BuCPInx+C35TnpG1iuOwT4+k=,iv:cTlRCnuLL4IUdbrwPxQ55UCFk+u/Jn8F9mrYNZ9+iMU=,tag:fX0xaXOBwOYDLbh2KBv38g==,type:str]
            VIKUNJA_FILES_S3_SECRETKEY: ENC[AES256_GCM,data:qBuS9bbkpUojmbr+qiq0HSlHkwb93p0AxeMzGLRrxoC2W5KOO92xd3tmyQ==,iv:sehvIVlO3eaLYHFttc73GVgpWoVEp+kWqNa3JE97AtQ=,tag:PDv5Sv2/tArJuUZhkeO/7A==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY0V2emtVY29nRVNRT2pi
            REZTWGExb1RBL0tYT1NDUnhuN1AyTzluNVZ3CjVMSEo0NDVibnlTVUs2d2tFVVJZ
            d3krOUZJaG0xaGFSeWhidUtJUENNWU0KLS0tIElYRVBsdVNnUFV1eFc5RHpzUXY1
            WlA2cVU1YU5yTzYrcUYvQXV3L1hUZTQK/WJmi9uPxZ06DFhGddRlLiXVo0K8bpSZ
            4ugpyBB/v1nBL/5yYq93DcO18afHvx2pVPpf9uKoHuJwR05TLJbuhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM3A1SXcwSzhKeWlvd0Er
            Zm9HRjVBVWFnVUw1ZTZyKzZhcmhhbEJKd1FJCmJnbk04S1dPM3lob1lZV1FtWVRP
            UFl6UWQvUjVGZlU0bERHbjRUNDVCS00KLS0tIGxEUFY0eHZBNHRlQWRCcng4NExa
            cmU2cXdZQ3dyL3MraHRtU0NYY1JIbmsKsN0tHPkW0WY8AC651hds8bwmYB44KD2N
            gV5M7ug/0V81BisnV8MFUs44lh6ZbWSPcXSi6ydg6rdU5QhNis9gng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSmFhTG8vcXpielpHaUUx
            ZFN3SXZxM29xV3N6bSsyRDNsMm5HbHA4cjJZCk9GVmIzVEhRZ24wQnpocUZQWXJk
            aU9wRmovY2YyZncyT1UrNHREUHdKbTQKLS0tIHVvbE1MZ25mczZNOWQ5Y2xSTU1n
            N1lBNmp1WWlYT2ljcjBRY0w0aTdUQ2sKTt5MEWIHaLhHzbwW1YNdrzOdg9UM/VFT
            dDOzWB2/TGw7BjEoaNYAbHeB4z7uLbuSE7Ixp7d8jc6mdA2Gk3lhow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybGhzRnhzYjdTQ3M4Y1Fv
            SDJ5b1FhbWQ3WDVBZ2lHQWk2emFTU0pISXdrCmE1RDhLUXl3cDJRamUySHcvaFNo
            WkN3MVg2aXRqVGNaRnQ0RXFBMVJkU0EKLS0tIDM0Zm54ZGxxRUtDbTFPQWRDd2pD
            UCtkRk9aVDB1aHBtZzhZYi9iOFUvRFEKio7oWouCoia65sd/+ETp8vME7fVioGot
            xfj+EctL1uNq57hMMWr0a5ukf6yIO5UPfcS2aJ4zfZ0ap3AqlUyqLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwZ01sNUw3M0pMTmtkTkFP
            QWdXY3g4bFRRdlNxenpLRm85Z0h1NTR1Y1djCllVS3dEdThCUGxIaFVCdGVrWVha
            bEhPSlBPZU9BQ3loWGhTVE1mZmlOTkUKLS0tIHhVRlMwa3ZnNnpGcXFvMkUrL1RJ
            Y1pMSjBzSmNTMUdPaGFiN2V3VktWNVEKEA6gYAozuUVsOlO5FilT7rtOwfVyhevo
            ZdFPTNAaPehDbw8AgUiHVREuFItmip6B4v/PkHpzDHBInIk3YmPx4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBudWJ2
            WHBOT0Roc0pTSFA1M1UyY09WMU1Yc0hZQmVaNk5EcHJVM2VRSlY0CkdGa2FRNUtn
            dCtZVlhINks2VU44RjU2eGJoVS82M3VjTmlNUUJjb2dXMFUKLS0tIDAvOEVIN25y
            cjZ1cGV1Um1XSE4zQ1RCMXJtVU5QeHRicXN2Z3pFeVJiQjQK3giBvptvbQAdTAEH
            PnfjM+S57h0W2dPKGpmDLq+20Nmo8KjM0Q++FG0dskCjSVqA5GmCX5KYwopb4+zi
            UfZFOw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArU255UnU2Ym5CM0NGTW9M
            MVBDelpvMXdOcXBRUi9OQ2krdnZYZ1U0dTF3Ci9MakUzVWdXZ0ZwRklYbWFnc3JF
            Z01wcWxOYVo5ZTBPbUF4ZDBjSVFMNDgKLS0tIGQwYU5ERER1SVJnT1JmbnVPRE5J
            cUQ5bm9MUGNjNWN3Q2Y2SGwyREFpNE0KW3EYlIMi+3CYrsrLob+1VylB4edV2u1W
            vD/pGYanUWL5P40R322asSPmqtlTTApQG2jATLXTlQisMAFpp5bWLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUHFscmRrYmRPZEUrZm1o
            SUgybXpWVUU3Qmpnck8wSEhiL2crOTFLcXlBClo1NTVZNFU5RktmbGMrRTdIaWdP
            NkN2UjNnQWlDVEp2SmVWaklvSm9VQncKLS0tIFljWE5scXh0Uy9Xd3Q5QXZ5V3VH
            TW5aRDBINjgrZkRoY280NFFrcHVkUFUKxRhklFoY9p+IZPBcuHQrxv7hTfg78tko
            wd8U3V8g+nB3JlKhfv2KXjxUwYlLVnqo9zeatMNEqoBxQU2M+EciOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOWRWeCswdU8xRmJick1x
            U3dieDZQYlREbWp3Y3BGMWkvS2FZTnlFTkVrCjVEaHk0VlEwQ0lpMUZCTUFHcjBP
            V21WSlRjYmoxUWtPRFVydVZXQytGcjgKLS0tIENlbzJKTkduQmhUOXZBQThNcTJ2
            N3JINlRvVWdYQzBCTklJck1IdWtqdEUKsPBxLM4vCAMl7Br2zgoxEYgo8zOGP1r4
            7OYiHigs1VDFFdQmO50VgWkO5iQdBAy4O2Rr6VxCQ9UQqUv8QqC87w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYQ0FWU0dzRC9iNkpiMU8x
            cGorUmhyQ1duQ3djK29VZ054UWV6UU4wa3pJCjJMNlYrQjVmMXphQnZLK0V5RHFo
            Z0lLaGRhbCtqQWZCcmJBMndNNW5sYUUKLS0tIEwzdzdSME92aEhreWxCMGJOV0th
            c3RJSWZva0ZHL3ZpOThPd2pUZ0ZFUTAKQWOeXnCOsZOn6C+iPLhCpNfYCYD8X1J8
            s5cphiAvN4D+x/3ic+fPOMgUjfR5AMfu8Za2CUzwNao7ixahdUEjJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T04:51:25Z"
    mac: ENC[AES256_GCM,data:WH6Q1AZWEK6N8zyyHBRbhUYBlKUO7YirUTC6/D/Q6A5xmsLXDPGltv3bafR1LgEHtNVaD3e8JnQnn/8jcgegp4h4xGsOlDIW+OS67foN/dmFnNiiEy+4Ixh1p17VsHhAvK0NwD4OUGLYOfH/8yP0/Yx8o9azh6Mp02lg1LYAnJc=,iv:rFyf7SCM47H3It0RevAB696az/30mVGlIN0U+m06Pus=,tag:qVOvqFlJvx5BGpnGDjdG5w==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
