apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: hoarder-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:0ZAPlX77Xnc48nM8u0k=,iv:FLC5jfBfQ5wMZDePIJ3c2CO85OiSYv6GfeG/V/smLI0=,tag:qd6Oet58ECHRYxHTXScoEQ==,type:str]
          stringData:
            meilisearch_master_key: ENC[AES256_GCM,data:tMFLcIQ5vliA7uO/n4Pe2WN6qlcDRcDQAlOPkewq9MDNhxGO3OvlT/oF+g==,iv:i0wzTyPoJR6xDO+1dXa9unNard5xfIGXpKeau29LO3A=,tag:vlcMrOAmfyI7QgIWyPbjKg==,type:str]
            encryption_key: ENC[AES256_GCM,data:pJxLrkZewhltyN/pD3oQpYW1C+WHwMpxbsIRM5o8wpM+HhWXy/T7HXPEv/ixIuDvGH2VjoWYPGyr51g8BMvapCrq9cqlZfJuGKLMHptQ9bf3VYDv5Qk3WvWFj2RzvtfLuOUG18j8b3CBPAYUn9Vu4BSD6xegzyrgAdm4kKkTUjyX2WtvGHIgka3rhPCNY2AMs0o8SBhYEbm9U7HBKP1mX+7K+EyPnoqdS+lopuIHLhNsrsa5bgGTqVqGOrxgTj1QLG7YTdNlGiBbFnZK8mWH8yIxS/foizd0dhQ0ivWfaem7fGBJwLx0pfYNFijOB0PwvRi661FvCETwdFg8d3P61+zNvfJTa/JYfkzsgPbQg8/XrM4ZWFjKZ6+sD5TiwLq7xSzyGIAlInNjKwrHsxuScGO10yvCUH6A8pvOKAj0RwE3zPtUr2PLfR44GPmufNByztVnKpKrriOHCZ9b940jAR5oLukAMHoBxIruidzwcpKHgUZOKtwbEDsWvILM3mShpEkPrql6cEO0gY8ZeXrKZ1wLPiSVGEKQ1EieOZU0Ueaa+OwgXzU0TiJFyal/ChiRQL6ypi16HYwUNDHJy1HdZ5BEo3lH6uX4LqK57XKPTVkH2vjINBeYE8yvN6ktNhTk4c/ipY5QyW0c+73Cnoo0dTkiCvKUy+cHaJlwTus7hSQ=,iv:U9+yhVdJLInKCQ+gqOTzNsZyyzpDLbXWczX8CF6ce2I=,tag:sMDOjv7ZObftz7MPB9wFDQ==,type:str]
            OAUTH_WELLKNOWN_URL: ENC[AES256_GCM,data:dZP3mGHrsn0Qj20igfQtMB4Pwo6Lbbx1PPeU5fSDNNcO0ei/kAOiQ0fr/t0aJh83UdYG6sSfqNprfm4CneszX4MF/pQ5YBOSj8Fe,iv:2MZNj7JTabQYW0xVuVWpNL4i5zbfRDP+Z/AN/BWdmow=,tag:GN9l/KqQuoYcmJq+MbDu5w==,type:str]
            OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:zN0MnfQz1wB21IdI1IaxQfyEaqYGVXcQ1HpzrOFHEEzF+kD7RuTO7YhsC0ylHk35Suc1YBm/EXST3wrI9ecF8crz5z/x4C001mTr5ZgYlw9fmw+o0Rxqf7RTYlbkzUqE7CbxGXSdUGlBLjylYRe907H8Us5C3+Q0igTxmEq+vpI=,iv:lW5kTJ8aZs1XPonjzUFGnr3x66TQrTUSruLOWWciF94=,tag:LxLFhNwvns35tRsB9IebdA==,type:str]
            OAUTH_CLIENT_ID: ENC[AES256_GCM,data:7fM+sITiTsDWxLtDaFcY4nRpQ1Ja26O5Bz0Xe18M4VWWE41ap4ogvA==,iv:3GedN94Pe34tw6Dk8x41LV8U5Z99EAgnU49C1DIj+aM=,tag:UF04+uzF5IktxcroEU97Bg==,type:str]
            OAUTH_PROVIDER_NAME: ENC[AES256_GCM,data:EAycDA==,iv:llettnneiV3Lhibq1aOtKVAiTKb4o/Ryb7flyChVkfU=,tag:ADI3biWsDdLadesFm/1N/A==,type:str]
            OLLAMA_BASE_URL: ENC[AES256_GCM,data:yDvfwull+cPqvz8ZD4dDJLHlfiSTL2pMHc3I8CKmbASKBGZnJoaxb3pH45r/Q+gX,iv:cMtOhQ6zxXvAm6KyV8ZYXYSryBK+fGaxm3ctxa3Lbac=,tag:9aHcUyTs/LhO9HkBPXsSOw==,type:str]
            ASSET_STORE_S3_ACCESS_KEY_ID: ENC[AES256_GCM,data:tUTGN0okKWkAdEqdrJzCBwx3z9w=,iv:i0rTPoIL5XB+dZ5ISg2Ne9ww2DDkgP1t8/OaVlMxw7s=,tag:/mf9A1T4+wi0GK0gTDMu9A==,type:str]
            ASSET_STORE_S3_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yLoI3X9wEvqpnqol2gCM49EdPs0U7zaqVSlJ75GSfbg/UoSQxxq+VB/cSg==,iv:maMJj0uwoniGnIj3iURF3CzEXYkRaCWuhryA/1/Tt/s=,tag:AGbT3t1FUolundqoB4bHyw==,type:str]
            CRAWLER_HTTP_PROXY: ENC[AES256_GCM,data:7hFx7p9FHxJ6v96RoNoxCG1o4J4XRT0xZfNaT8AU9FNqigU4IhNIiQvWC0QdoTnCLHxuG19xoDYx9RM=,iv:/BFV4z0fXVVzLqcDxWjcVkiDqWvAi4OEUYHg0zQt/04=,tag:9D/dGzsv0zqXaj3/BuhMkw==,type:str]
            CRAWLER_HTTPS_PROXY: ENC[AES256_GCM,data:AWVeXuZ48evHukkdVe5FHFKn9/2D3cYi2TAJlrgIL48TjdtRLD47JjV71xrKG+S4Ash6XVS6rjCRrhg=,iv:IJ2bNZ91tts9pkkOsWRKZJ8AYGkKJroYpzQ1eR7NP8w=,tag:vjR7h5m4qObOO4UY0WHBnQ==,type:str]
            PROMETHEUS_AUTH_TOKEN: ENC[AES256_GCM,data:d5NJQzLcCLApSG90hGZuCTj4YKqWad9PrQDvZw+Rjhg=,iv:+Bv7HwY0/HYfT8xkngu8NyB/H1AWxuTjc4zMYF3Kyx0=,tag:qVs3l+4nLurt0TqMVQg/Bw==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZzAvWjhuZDM1UjlwWlhv
            OExLdEVlQTFYUzh4aTg0bTN5RGVoNGVMZEdJCmh4Y2ZFMm1ISEFSN0lscUJyL3dn
            dkVKMjhiQlltZnF4MEV4MjluZkl0L1UKLS0tIGljKzBvN1RDUFUrTGRScnFsdnlW
            RlNtMXJlVUVPeEdrT0NUNG5hNnp4VHMKudEOE8GiOhhHFFUoJGKUYdaf0RgITy0D
            Qd8I8VjQ9D+v5NCAXABm6N5Tvdzm5xcemClSrX2hpKiy9LF4UnSxiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcmxhbXpMZWhjOVoyRkJo
            bmhyRnh2ei9KZVBaNU12YkZiL0pxQTV1dEhvCnlYN0FJUlNPaHlFbSttNkYrZWp4
            UUFSZXIrckN3OU4wZlFvY0I0UVNwVVkKLS0tIEJNaElrOXJSRGZITUVicFpYUDN1
            cld6Q24vMXJaQVJHMGR6dW1IMkJKaHcKI/QWlz9druMs+sxnu5fzJBcm9PKGXXxT
            LDj9lARKWgOkk+kJ2jbsp3XYYSbscufkrT3FBTptoMS2VCR9Ky3zLA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENFFvbFB3VVRRc3dUL3FD
            TEZ1K2ZPMDZzdEIwVVBReFIxMU9sUG4zbnlZCk90bGxTdnVoMW5kRzVFMExvNnZZ
            Nnh3Zm1CamVpWXZTQzczZEVFdnFxL3cKLS0tIEJQWkpGWk1nS2wwNmsrdnZiVG1q
            czIyWlVuRzlLL0tTUDJzSVhINzE2dUUKxY/jI0RntPhPASCyh0lyBtbilT8y2P3H
            vqtoYSsr8d0V/SdWgkgq2AVgxREEZ2bgAZEcBOUm+OHRtMvCBGHRug==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseFc3WEdGRVZMZC90K3Fq
            MmJ6WnM2RlJGeXVycHlRNU9RRUV1c0FCNVJZClBpNVVqWDdHKzJUMTZLUkZ6V3pr
            R2gxS1pkR01RVE5oVmoxMHN5YTVqZVEKLS0tIHc0QTEzdUdOcC9wV3dzaGIzM3lR
            OE9GRmoxRHBtamNxWUNMV3Z0T1VkY1kKrMQDr7eTSvuqS6GtYHfTbCDPjBUeWliN
            DWyzxIazNlSLLw3myGxsWsgyTSoOmns8F/dyb/CGbHuOAqNCW2yQ6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOHo5L2IzRHI1Tzg3YWw3
            Tm90MUx0ZjNmK2JpY2dJM3NXZ1Vxd0lCbEcwClhqa082dHNaVk8rVm5QT01WelYz
            RjRKOWtqMERzSzlYOHNjWEhBNERXeUUKLS0tIGJJQUVjL1N1aTJlU0dzTmdGMExp
            STJsY2lHRGV3bDg5dE8wVWtxTmFJOVEK+9C5FIOoPXIN3v7xhFr94YECB1SSfdV9
            X8ClQZSsY+ac9wod6nVWtwfGaVtVB3ZDB5hFumzuzsqzCiR386hbuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyA4YzFG
            SERvYTlBbVNFenk2b2oxdGRtZVVIVUkwbHVLc3RUZ204T2ZRWVZnCmlpcmt2ZStT
            S2dpeUpEbDltZ2lueVF2YStlNldTbktNN1BodlZyWDhEam8KLS0tIDNCOVpTdHdV
            SDd1Q2ZTWW5RNkhISGV2MmZ2YTZEZmIvTjFaUW9kd3VURDAKu7gwfulbgwANEGQY
            HeBJFhNlC3wX9S3DLhyRmC/Tii8srCeatqyJDp1jW8bqbPNFaBtSiHwrILV+4CUU
            fYCtrw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubnFMNnVCaFdTWU94N1Mv
            WVVvWEdweWwwR3Qwa1VyR1h3VEwyR3cvTm5nCmJoMGw2V3FxVkVvbzlEbm9HVjZx
            cFRSM2RWaTZwRW5xSFV2ZmY0T20vQ3cKLS0tIGp6YzdJS2dTTWNiQUlVVXA4ZkJH
            Rmp5Y0E2TWJKbjhnUzFKZVRJalZ5T1UKXCTF7dsPmld5VGB4l7I5jpo4uytXjQoO
            5fBwcgH0M4Chiw3nIt1qyyNSJPq3G4fiQr/4WaYWtfnlrns1aV9eqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVlhoMytYZHJERnVVaGVE
            SmRyS1cvL2lENzBucWd6VHV0Sm5TWWt6Y0JvCklJNUlsYSt2L3NVZ0RyaWpuUFBF
            ZnBYZlVuRVVpaDdmalBXYitoTXU1azAKLS0tIFhERUhPQWVIZG5MVlhaY1pldklu
            c0Z3TlJPMmxpQUZPVEgveStxc0VUeHcKHWLoaLuSyWPeYmnKQjl0IHPteLMHvHdY
            5HaTMW+rgQR+KVkZELTDiXw/uXU0sd7Ia5pSHwh6Zd/VekBvDcopRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvT1ZzYXlFbkFtSTQwazNX
            VlM5VEFxbGZUZ3FndTBJL0M1Tk0vdlhuOWhRCkdCTGxFWnZaNGZSUlg3a0l2bTE5
            RWNrVFpRRjFWbk1JYklMMU5FNlhTQ1kKLS0tIGtnZTFIM3p4QlQ2QzhiNXdoZC9y
            KzVMUXVPM2xyaHZHVXZwSVROYXRkVTQKHP8EkfJNhKFs4tYIxqXrz3BBOED/4/kj
            vCF/vatvTIj+rvAy1UJb0ymRUbEpBaeqzurt3VHO/OfYarhzwPQVrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcU5abGVYU0Z3QWIxM005
            RzVPNnZrUlRDLysxL0c2ek9jK0huRytWNFZ3CnVGS3ZHZmF5dmxieGRScVZMbVlu
            UWcwZHFhUXB1Q21PMFd2eUE4Q2tURFEKLS0tIHpUWWFrZTcrRU91Ylc4am5OV1Zv
            NnZQR0k4Mk9OUzdkT1pWbDV6ZjVJcWMKnA0V3H1R2JPXryhJFixo3z6/iOGR8iXp
            iYHCGbNEBJEj+koFhtdBF0KmRWJ1UGtnxp+G3XyQ/IRWJ4PJKxD00A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T04:37:11Z"
    mac: ENC[AES256_GCM,data:JnYVZrhQwwU6UeYimFOMCVMIz23JpTcU3AK1Q3uRtvIZAw2kAhW1Y6uCbHqD9cUfhmQZ70yjV/dNKZQlt5o7Iv9e/tJb0YHwYLh2dNT0X8bayu6lSywi5ERIyz61cuOAGEH78NNAbsi7ib0u+WwOcgUhNn+D4fogVZ3JDcoXNPg=,iv:/TUvX2TqB4uywtBwLnlh3pvFKXl07kiD41QOoWtUWAs=,tag:N0Uu5YpUBfI6dVRW0KJIcA==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
