app-template:
    mongodb_url: ENC[AES256_GCM,data:bfvjJlGXVIQ/Ew1q3hAQHBxxxXvH5A0JdpcGjWkcn01on+CGC6K/S6t1na4DrCiusuy9CSfzrbyZULFnom5pRb1+U2x48qwWjoydI8437VYBgO2Yfv5s5QUYOSB7F3IKdXk+/8j979vcyDKfi016DNNAwr+K8wFz+wFcIrdnX6ARJtK2JWRKC6rkA+1teH9kKiKM,iv:BtY8gzsdU5zzsgkXmwNcMn/vXXfqvIgME6hQWQ4a2YM=,tag:bAhB5GkliQxoqV6QPfsuxw==,type:str]
    smtp_server: ENC[AES256_GCM,data:WKzVAfcmdfZVhT5zPszmkkfWjhtX4Fxyld7up50ja5sBt1BYetCR,iv:59sww/6SeLKjx9o7qaQjms+vXrA+pr3T3UhSMuaYPTI=,tag:P0cVs0UcfWEO0TYm/fAFAw==,type:str]
    smtp_port: ENC[AES256_GCM,data:SfrY0Q==,iv:XtRJTB7Ew0O9Des9VW2bwqh7P5bPgCjpl5D3G/376ik=,tag:yIHCdaQxNVCZsdDqyIcpyA==,type:str]
    smtp_username: ""
    smtp_password: ""
    creator_email_addresses:
        - ENC[AES256_GCM,data:GBU9xnV2HUZtyrDigmu4TtzatlIT,iv:DGV6Xbwnm7jDT5a0CCTp6x/Znz7V/XFs9ZwRrD0+Nic=,tag:Sv7UANRk8ADxJPkuXEh0CQ==,type:str]
        - ENC[AES256_GCM,data:g3V94ssXnrrkmdhBT2oZ080cCH8=,iv:JjhFh8Wm1XO4mDB4DWY+0QREbFLn9ao03TuH29F5QX4=,tag:xOtK8w0Ppkt6mzFtTtPxrQ==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlZFY4ZUViMWhkclBxRTFE
            TzgvMXEvbklqbEV5U2JHdFp3ZElzbzBQMVdrClpZSWtuR0pDVlByTjRIRG9uUmNB
            N0RHWVdUbys2SHN3ZitMZytrZ3JXSVUKLS0tIElCV2Y0Ykl4ZW0zMVNTWDc5OXB1
            b2M4SzdCVm5GdHBIR1BoM3NEdjlYS2cKc3vqXCW3gux4VzkKvJJdvns0NZfTOKw6
            B0K8knzsbv3Tw9ELO12q+/BdPHpSQLb7p2auX5zJy7myE/WOV+XBow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVTVEK0ZwdTgrd2UxRUE4
            UUh3UzdOT05BWmpOUFdteWF4Wm9rTWhQZVhJCjBGNEIxYmZENGhDZWxrVGdyZWQy
            Rlp1RlVueG44cmJOU3Fjc0EwS1lHZnMKLS0tIDZ5cHNUWnhLKytVWTNuUXkwMDQ4
            eDVmZUhNKzhSd1JPOFpGSmw2cW5YSWMKS0/wsIUebWIuflRGZXkct+Z8E+VETfmc
            Cs9AgwP1PxytNGdUzslhFw9+1bDZro80/egzcXHt+dBKayG9xh30SQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWmxKUWozUG5IWWhsMkF3
            VXZ4WWpxbXFXc1pGVVFyRXVYbERZNEg2RXowCkZsMG1ZWGhKTkFWVHZRSWJKWGJ2
            QklFblIzcXRldDhBS0ZmZTYvWjJseEUKLS0tIFNLOFhWT0xCaVFMK2dVdnJ3MWdk
            MFMvZ0h1WHFpRmZDMllVMTZCVHV0ekEKAE8u2XV5nENkSAO5MdA1VNA0dqivohs1
            acHhq2bk2ScHfS9nDQ4ZnpEK/20C+3rQCgid0ihWHKGW1DjMsLb/OA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBicHJUSWhkT0hlZnVsWTZD
            TmpXRXpnT0o4WTNTYWFLTXdwTWdKZ0VYVXpZClBla0lJeU9LMnZhbEZMNnB3L2hx
            bTlyNW1QODk4SURISlUwMjN0WGY1SnMKLS0tIDcyOGhMTGhyNkVUQnRrQitJalY2
            dnpGcmx1Q3Z0OFFzMlEwek4zU085Y1kK7xyTnw9i7ALKnFfgLk4qV8HiqRRcoC+7
            w9wvx0mweeGQdXYGytsraGXJcRlE34XffkOe519U82K5Pp2uRocIPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuMUE4K25pZk5VNUJqcExL
            aU4vZmx6ME51RC9VYXlWWXM4eTVWUlJ5ejFvClFEeUVLTWt5VnpYam1XNlNJNVFE
            cmxydXdZWllNZ29PSVA5eS9POWZhN1kKLS0tIGhEUXlmcjNYL1BGdkdyQzFVODRF
            SHBnUmkvTmFsVERubFBHR3FQTDVIeTQKqTzDND1uYKazceE/LPqmxmMvjFVKYHqM
            fTFKPh8GR4BB/kxFw1cEv4tdYLAmylrNcUowLCCLey3+K7Shk07/1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBCdmFN
            VlE0OFQ0a2JvZXNERzNlTFA4NUozNWYzYlpJb3B4bi9vZ1ZYL2pNCnFGUHlmRSt5
            U21EOVpYOVpzZEJ5RnI5N2w1WjdIeUV1bVlERHUwS2dkQ1kKLS0tIDVVa05BdVl6
            TzNMZ2VvZzc3L3lTRm1DcC9vUHdSUnNaZmpucDRFMi90YU0KmBir09xD30keyba6
            b08zY9FHbvZ85Qk9FIyAEq+lr3Bco6IgDp5Q4okwKXBjEgi5zfKfhAbxQPurS4t4
            xRhsAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTGIyaEh3ZlpkNXJLU2l5
            Yk1KV1B6OVgvd3AxRHNkTHJYOFk0Mmd6NWtvCnBNTFNyZ1NLSXk5YW1DcUUwSFZ0
            QjJ2TE1iWTdVekJFQzJrMU9EZlprZk0KLS0tIGxPNzkvazBhVDdHdEZDbFlxaVEr
            dzV5WTdRTi9jNHlQaUp6dkQzdVo3SXMKNKoXMQcwnrn7VyzDtsgwQ8MVcTiPIpU5
            Dzii+q79oQ79MgXBzlPyNLGnsttpASwBBT/Y+4dgKVuUIVwjLtAhIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6S3RZYk0rUmxacy9iY1JH
            VnVGNEpUSnM2MEZWbm13Y2I2bG4xWG9EVUNVCmVHVmFmdHd2YmR1eEZXanNnc0du
            eVRQUHRIV2tvM0dDUnBYNVV4Uk5PL3cKLS0tIG50VGlWSUt0WFlNVk1WcXZmQ0lD
            SG1kdXNaVDlOWDlrcG5wU3JMQ096STQK276dljCII1f6O17ryMcRxI0udYg7kHsp
            0I8GP1cA+kRPHo+34vRf0XEm08dggJQQGpOn6bEQ4vmWBiO53RheiA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTUlQYlhQTXVYN1ZWMCt6
            Y3dINWprVDlqR2pBWGI1cGJJQ1l6cmNMYUVRCkE3SHozbHczY0lDVFVNZzFuRzZV
            dzRLcVJpZ2Q3YzZVMDBtb3M5UUlKQVkKLS0tIDJXdjNncjF2c21oZG5iRG1mNFFV
            SUZ1aXVmVHpzMzUzNVpaK0tKNlpTVTAKLavDamUjvNMY45NepZQGAD+FA9OYLv9g
            LMNXCZEkktBTDpCXQiyDZaJUFxLKJmVUPkIEbumTjaj1E1VQrrigpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoalIvckxmNEUzaDBxUGM1
            MWVLT282N0pybzRwa2pYdXZIdExFTmFYa1dnClhaemFxUms5eHJkWDVBK3ZCT3F2
            OUtRYzY1TnRud3NhMTcrNk5QbUduUncKLS0tIGVrUzVGaDRySnE2Qms3c3RJekY1
            Vk1DK05qZDIwSDdNQWtpT1hNVkZRVkkK2KjZ6giwqaTJTpZCppC/HhEMzj85HmSJ
            7VAekBGecsDtptljokxfEBnKuFj6VtZfMTas7PaecbtLxNFUbT53GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T06:49:25Z"
    mac: ENC[AES256_GCM,data:XhkjhZALQgyRTAtYISNDZCJ5+HeqTZdUzGy+BbvJmf1jz+uKuaU6cLrSBX1Oqhl7btQeGqXzd9Pl+LAQBD4DQg7AF7tl1QzAeub0OZIi3lG031oCpOXBSd6jHpwDrHmGMrT29IzczgWBw3eQE07FBnxWVlZ1Pj9Gjp7Y2XeTq+c=,iv:ZkzW8oxelq0n92V14T7ZwIKBDtKNIZGturKRbdAs6Ag=,tag:DnFG/5LSWe5ZQ9AGa7Kdog==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
