apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: element-web
spec:
  parentRefs:
    - name: http-gateway
      namespace: envoy-gateway
      sectionName: https
  hostnames:
    - chat.g4v.dev
  rules:
    - backendRefs:
        - name: element-web
          port: 80
