apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-fqdn: "go-socks5-proxy-go-socks5-proxy.taildba47.ts.net"
  labels:
    tailscale.com/proxy-class: accept-routes
  name: home-socks-proxy
spec:
  externalName: unused
  type: ExternalName
