apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: synatainer-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:rTH/FrNbsieWJcB8mdB1UdA=,iv:DlSsHkjUmfm4DiDmbPwg3EpFnOYC/snkMYfGIWokB60=,tag:zqXNhWWtz0BhcIAuPrdnnQ==,type:str]
          stringData:
            BEARER_TOKEN: ENC[AES256_GCM,data:beP0BLBjNBWW+lbDXj4Ph6Xu+Mooo9+ZsBgiQVzMr9lG6nSxflYc7w==,iv:GzBKMsfYC2d4FVJLJS6bEc1DqXm4Ra3o5qAqxKKBtvU=,tag:P0I6uKrBSjQNwbRxups0iQ==,type:str]
            SYNAPSE_HOST: ENC[AES256_GCM,data:8Bw8B6VYJhCD1jUq9sF2Qsk3csZYpa7Z9LqUCjiTulk2N+sxv2cTiIJ4SJ4=,iv:pldk19Ve6cHmg2R1qUi+lVZ+ydPeqdIJPrzPi6+Z4GY=,tag:scA1YhM9VCUtQcT7PyC7iA==,type:str]
            MAILTO: ENC[AES256_GCM,data:s0jACG1kIVE6cfvVz5tLPjP4vkZv,iv:eeVDmhTyn5mt/CV5fDEmsNkfKigByiGDYdqu5fLM/Ls=,tag:yXuRqecsel/4oW+6ICNKIA==,type:str]
            MAILFROM: ENC[AES256_GCM,data:UH/eC3JI5drtmIe1SS8=,iv:nQJhrXNlwlxdZzB7A7GO9/q6OfXhSgR9RbN4k6XcbEs=,tag:dVzd+HLVWh15XyPEZuR4bQ==,type:str]
            SMTPHOST: ENC[AES256_GCM,data:XGAkJbDCpbVXI7+NYnPlVC6p1hURfct9jyvQPcNBL0m//ikYQ8arZ2RKktI=,iv:7dNsviAMWCzJHlfD2IpTQbYVMUIr7EwNnVa8UkOaXTw=,tag:KM2tmSSXT3LgxU7ljlB8DQ==,type:str]
            DB_HOST: ENC[AES256_GCM,data:Sb2fh9/lpzEEkBMzR4GNc6/j6olr6+EKQeQKUQJ8NmIxonGXE8iRmmpCSsvbrdEmXtXS1KW1VvppTA==,iv:HPeFK53tM0cKS22xvlDbrl8X5whmmh0h/03SLjrpOm4=,tag:85K+WT1E2GIjt1fvBt9VpA==,type:str]
            DB_NAME: ENC[AES256_GCM,data:B6IZrc1maA==,iv:pCAjLWRiUZMAYvqGUU9j+iY/jrAhjcHCmUzdmia4LBc=,tag:8/ffrRd5oyTenaWETynm/g==,type:str]
            DB_USER: ENC[AES256_GCM,data:7jLl21quAg==,iv:NT7PQnWS4ZRs9XMpT5b8oKZ94r8eJVU6aV+xe+niFio=,tag:UpnmSsB39UvQIVj7giWQXw==,type:str]
            PGPASSWORD: ENC[AES256_GCM,data:cnpi/NADhse1hO2SYvlsiA==,iv:7Rrh8w67EA3UcmavZ4zBsg4t4IOJh0oBOjKs7cgVdl8=,tag:tKe+Xw5FB1vCymTAkCn+GQ==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdmJ1YklOemk2R0crZEpK
            NUtDYTI1d1hXazN0WmVNMDQzaUNTOWNZSTI4CjFtQ2duWVhiR0EwNlJuMXRTVHpq
            ZGVROUZQMFdnbVdYRVNUczJZR0hhQWcKLS0tIGwyQXc0c2Z4VkhCNzM0a1g5Y250
            SHpKbGJnT214T1FtUFdqUTU0Q0xUeEUKI+p2k9Dpktl1fMTkcb9saju+TiTh4//N
            GuUTlTwd4JQVEPXIVvgT2GiKD1fMhxf2d3aGP+DFvc44O/37R6H9wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaFhYTURqSUx4THZBc3lp
            WG4rZ0s4eUdJc2tsQmpGdXhxLzBIOVFTODBFClBMZlFadlAzWG1BUXJKNzZySnla
            aGNLV2poeVJrVzltbGhnR0xCWGlUMEUKLS0tIG0vV0Q4LzRFK29Cak8vaHlGaEFj
            ekhMaC9nVVM4NGp6SGZJM0hQMXdDM2cKU0BFWbchmbD+cr+H1Jl2ggBkob4cYlo0
            DACIXsQhV6sFuC3YnhR/DPNwokgQIn2leoRRELPEExPiYJue+zwxBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVEpjZVJuUGt5blVqSW5E
            Wm03RFdYTkZYb0hvSXpQTGRlK0NKK3hFVHljCnV5S3hCT0JUbkFvT1VXL1QzQWpH
            Zzl3Ry91OFp1QVdjUUNTbVJSUTBqRDAKLS0tIG5Udkh0M3BtY0tla1JEMzN0QUho
            Y2tZSmtTbVgxK3hoWWxtK281dFI2eGsKKd3H0Hi/OjzsZRJI4jdLDRMhsKj0FN3e
            I4IpFXo0EFCyxB02shOx9mEWBcqg8GxpLO2h+e7jGjTMisyhMF5N8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N2ozcnVMRllHcHFWOCtF
            RTBrbXBPL3BGR1NKRzBYWTkwZmpVT1N4ekNrCkV3KytvZlRKaUQyT2hpZ1g4c2Nz
            THNHekJzOGlKZGZHaHdCUG50WDA3TEEKLS0tIGpKZmJPeXdvMGhjRjFTYWZPSSsy
            QVpHZmQ4TWhla3Z6SGRUeGRnN0FzaEUKbXGvrNDRf1hhJKJql3BfoDDZtOdD+GDZ
            KYHIYM+kTBp8wT0mHy2G4wRD5NtBfnrMzwbNNmOrk2iJSLXTOHKGAA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORG1IZHJkMEUzcHZSUUhD
            dHR0anVQWEY0ZFQvR2VESmY3NDYyU0VVSVNRCktHeVNxNEIyU1NONHZ1ay9zTnc2
            MmoyOG0vcEFUQjQwNjFDcFZ3MXd0N28KLS0tIFNIcko4T1l4OStxMTEydE1MRTMw
            NkdQZVJhUXYwekdLZHhGTTlpVFdiZVEKx9XTMYizhMJp16itSNK1E3NQQvFUANGn
            sMY6KsvATIw8amUzooQKL7gDf2U0xx0fazLnlVTJYMTDRZ1DVjlE2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBEU2g2
            ZGhDQjIvc0ZTazNqNHVXbVlXSERuNkhra0EzcXQ3QmZTWk55SFZnCllDZTNjdkdO
            bWNrWFA1MTJCYzErOUdydTN0bW1SREM1TVZWMkQwa0JxVkEKLS0tIC9MTnhTYThV
            ek0zQnlOVFJKWFJWT21VV1ZScGdUTG40cjJKU0lzMU53NzgKFyqMQYe+N8OohQeH
            q8tWEnS9sMGmVBKEQwdfXcZTlbd2XOd/zvNvUlRt6ZQApQUSZmZzlbeVaOJ3ytIK
            I5aBxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuRDlqNUthMzRJejlSSHhw
            c1hwdDZraW0wWGhMTnIzRk9VNWZQYW5CbEZRCjV2SENJYW54S1lpaUxWNjM1V24w
            aUg1Y0NoNTd6d3Q2bXhRVEJBZ2FhYlEKLS0tIEFFczcyb0kwZk5IemU5anZWU3dn
            dEU4SUFSRDNNTzNuZENlMjN3OFpCNmsK4/q+i5WWYf3d9WIMLoW2P+CheyjUMBEJ
            eYlZddM/OTOZicNMdJQ2mZmRu4BWLeg5IZ7joBiNOJWaIQi9OZ60og==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwLzdVOTFjV0poZ1BLVDR3
            eHhObCtydzBFdzR0b2JmNlRYYlZVRjFQMkFrCjR2ZGZHbG1SZTU1czMzQWh0QWxK
            YXlyNGwzN3ZjakRET2dUcEdHVzRGUzgKLS0tIC8rQzhiL0Z2bmw5ZktkRXh3THdO
            S2JobFlaYUZaSmN1QitqUjNQdVBOM1UK2xD5C9LAfkY2upLpFJqtoT+ltv9ZhybV
            0/VmcdJTQctK1gX066o/Jv9UqVn9IFQBu0b/0CCWSNwlkHbCOt52hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWnZ5WnlYdGkvcEZ6bWRR
            NWpxTnVDUWxFWGhrc2MrNGhDc0p1M1hSTXpBCkRsUXRobHdLMjg3SWpKclBhWHly
            MTBBVnhHRmFqQUcrUENrQkhVcWI4NHMKLS0tIHpSZlY2REtVMnNXYUZ3Sk1yMTlQ
            N1NVeCtvWEJ0OW41U0NidkVXNmV2b1kKJUF8Q2GKF3JOwIeLvKIE3QTVnqEUuDiA
            LlwQSR3uF2CAeVP3drtdUSYSVh9SjpahSIoe69nAZCPc+GzNK0bbXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRVA4R3VmTUFuclZGWUdi
            Y3hnZ0ZXZDBjTlZhZi9LQXh5MlVnZnUrSGpjCm1rN3dLR05pQVErU0FDS1A4ZnE5
            OHZpdGh1RDR6RS9wTXRsdU5oSTJ3RlUKLS0tIDdjN0UvajVwRlVuMEZoWDZxcFJ1
            YVJkazJvbk9MWWhyTlpvWUFFVFJybUUKyCwHaSW2lYdeBEX4ua/c1v0s/2jt9lis
            z68JpOTLNUBHUnHMYOd0+pxWqjVHpATWo8QyDe88Lwi3YMB4H/QYsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T18:25:07Z"
    mac: ENC[AES256_GCM,data:r6vuf1XEvOQsK02OeHQIopUywWJRIPl6eokAW58TkI0YQUpPWOV7vehH+vhzRG7cqEs39Tc2enhQjMyZ+ep0aoOjz6EH9IrB68vOm2MBACuTRCtHGSZbjcOsJYuf5Uvfe0WA8yYHrSY7Ot5ILvlefZzwa3VE6sR7UP4HGF4LYe8=,iv:Q1+7oWrYSp4sXBu0IiG7P+RbvSXWnKi9XOE6rJVmooI=,tag:ltszQYdBmNZhBAKyYNzTCw==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
