---
fullnameOverride: do-k8s-ext-postgres-operator
resources:
  limits:
    cpu: 10m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 100Mi
podAnnotations:
  reloader.stakater.com/auto: "true"
existingSecret: do-k8s-ext-postgres-operator-secret
image:
  repository: ghcr.io/movetokube/postgres-operator
  tag: 2.4.0
