apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: qbittorrent-exporter-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:zpEbeXty8QvjBnZ3RXDQZ7idl2qnNUrCMh4B,iv:jIBJg72U61SNKTvIYig9PPcTw+rxExvFuLKGhDd6+cM=,tag:hm1FIIsLBKzccG+PXz7uaw==,type:str]
          stringData:
            EXPORTER_LOG_LEVEL: ENC[AES256_GCM,data:/1KFsnE=,iv:tvnZ5T1HM1oXY5pJ9C9WcpvALZ5HtA/eoo0gJaQC3A8=,tag:VJEIJmwW+MD96gegAGSzVg==,type:str]
            QBITTORRENT_SSL: ENC[AES256_GCM,data:ZydSQQ==,iv:AF45GyhptahZTq5BOoAFKkYhU++HSezulhF34+DC2fk=,tag:+H1d9XR03SyEPwprxzrViA==,type:str]
            QBITTORRENT_PORT: ENC[AES256_GCM,data:ZNue,iv:Ra/CI9NtTFZrNoJEqimJqnZM+t2AHbueodsuHHQ81O8=,tag:XZfmX5Yg/bDHW2AHzlvWLg==,type:str]
            QBITTORRENT_HOST: ENC[AES256_GCM,data:UbBhOu5IGdlG13umdgh/Hf3hVvWVGjM=,iv:jrIaO7HdzUWRtKU+FcBEmzNShECBLTW+xVaGUogLrcw=,tag:2JFGp3Kry/laVK0gZhbrvg==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZUhKbFdBNnd1MEpBNHhT
            cTlPaisrTzU0WG4zVHNKSW80UVZEL3N1a2t3CklMMEEwMzJ2WVVhT2l3blZpUHhj
            Sm1iZ1RBM3doRnNIcDlvK3lXUEl1TnMKLS0tIHkwNHhFblMzdmxiZjRmSXAvYm9C
            STZORnZqK0o2WnBNNVJsdUdyeHJUNm8KDo8erbNtX7ga0hv0rhSc9Xn16CTLXFcB
            7vdQKaN8p3/qDmwOsZzikwonhKP1xGLxdA3j6rQTbu5ChctdEX+YZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTGZIK0FsRUd1RUJaak1U
            NUM0ZVFFam5Lc3pkSUR4QTJhQys1UWRBMW5JCkVwY0N6UkczRVRXYm8vNGlLcXdZ
            RmtyZUNWSjlqbDZYR0tlYWJMaDRHVFkKLS0tIDEzWHJMVzNhcHcrdWlSYmRqUmJt
            RzRmcitSQTV5UitGVUdTQzZuZmNTSU0KttcmtZbzW4AeJrLO1K8VJtfQcAr2U0PJ
            9Q8aOREwcLov/rnvYTzgpN9Ffd5Ny9P4Os15lcaPbd5TS3VJ5+8A8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNk0vWkNoK2NEL2RzY1la
            cTM0S1ZIbWdJSzlZcTVLbnpQSUE4TVpYZ2drCklXOVBEV0xpeFdMRUd1ZDFQR1pI
            ZjJlbThkN1JCU1ZuM3RUdXlJUUhqWVUKLS0tIG1DY1BQT256Kzgwd3ZlTGxMZXNH
            M2NhYlpMOS95aHV2NHZ6MElGdXpXREUKiH9sh7T42KAh8M529S/pRDMBYReU2DFp
            Nk6H6+EdynrUpE0xKs8G141Fm6Ul6F96bQbzO9oRTdIsJo1i1dZE5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRE5NUnB0aXE0dlVVWXZu
            dFRCcHRoeTRxbXdpbHZ2VVN5ZzRtMVBPSEFFCklyeGNjSE1UakdPOUtTampJK2tR
            RFdWMzl1ak9jZlFQNUJnbUZiNVFiOTQKLS0tIEgyMEM2S2QrbzU5c3JNZ3JzOUpF
            cjB1K2VtcVk2RnEwZ29IaTZDaFY4NTAKcbt99W9l/zhRNpQ3CU4H6C/TSk9IIRsE
            06fG79oYORQKrdXEJqw7T5IVzKplvShjwyqeqVsCfxT3e9Qz7o7iEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVm9TVXlJVEptMTNBaFE3
            amZSSmNCUlZvLysxTFRhaFBNY01vWkZJVlZrCktTcEZIbCsvcDlUYkJxVC9KQW96
            U0d1dWY0MFJqb01JT1dJN0s3R1RZSU0KLS0tIGRZbEtubWJvcGlvb2x4MHJIN0hn
            ZWFUNHl1UHZ6N0orTTQ3VUo2WU90eWsKcP5fnO1uqYnQq7J5DZnUjnLfejVH9zId
            gM5BXKaqjP732KgiessKGGrFtkpb82ADsytN1chN9nLKaQ2dsY3SeQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBzc253
            QUUwSG1hUkVHS3lEbzZJNUJlSjJ3Q3dPdkRGTUR5TmVpMDF5eno4Cmt5ZENvSjdr
            dE5kYkdTR284bDhTTk1LSTQ3dDZSaWd3c0hnQTV5K2ljZTAKLS0tIGZVSktWR3Nk
            Z1NSV2dIVUowRTczMUgwUWpTTWdUMVJRZC9WSm91VGtiZkEKL+e2jTTUxvi6ykGp
            GOTbDq7s49vwxnYSqHEJAYR1iEu4+KoqdSM2oG6uG7OFeMvFunYUZbEc/fHxpXXn
            ldLxvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUFQ3RE5LOGJwc1dRQisy
            bkVaeTc1TFU5T3hrb0hkQ2Rnb2VQQk00UHg0CjFwUTJ6TXJvNFRLbG5helIxMDNF
            dHQzcmxoMC9VSjFSMVM3QzZ2RmhMZlUKLS0tIEdUQ2RBUHZyVUY1R051Z2xmTzI4
            NUVlUFVzZHRYcGFpMDlwaERFZ2tiNEUKjPtmsPTqhav2CaqLCkW9pPg5CiHEKfjc
            TKYE3/PFJCuNk0OA0MByebo+8OLn+SXgmKSmGbGigDK9W/Llp7ZuUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUzhlRFovNVp3WXFBVnE2
            Y2p3TmNJNzh0Y0JIZUppaVAwOGtCemNzZ2xJCmF1NGI3ZkU4NVJBQm5sRy9lK09G
            dG9vMXRwWjR6WWkwZ3VPSzlQdXZTVlkKLS0tIDROYzQwcFJIOG1Id2t0ODZiRnNY
            dVRReWJOWlp2ZnJOMGF3UE5SYVowVDQKMDNTn4gbwt2nb0xmU8zqfJ7FrRMhmR4R
            EDbj8AFfA8BBtNe8RKR3kP9pDKfAxtW946DISTaJszfkqudD3JDCNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTytHZ09aWXpVSHJVR0RS
            M0ZuYWpsaGtlQnNsT0RLSlVGaFdnejR1dGkwCmFjSERlWTYxdnJDR0FkbDhqY2dP
            dDdjZFovdXBsS1pudDk1UmcxdFJXcVkKLS0tIEQ1M01SMzNJNHdlMUI2UGp1RGFw
            c2NSZmVhcC90WGd3L1hHRElmODk1c3MKaBl5rOduobBPaX/A5Dgf0mOEuBNxQLd5
            1MSqvQHhMQkj3M4O4IuasBrahYOwKljGB+W87Z25N9qppIdyp6cFnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY0o4OFdyQ3d5Y3VmS1dl
            dmpjalZ4RHVzQ1pkME1MTDFXMzBtcmxaUEU4ClZZL0FuMzgybXhJZmlFYkZrMVY5
            T3VYeHdrY3hocURYb01aT050aVVLcEEKLS0tIHBKMW12cTVhazJaZVQwYk5pTG1H
            dHZWM0ZnSXhqYk1VZ0pBWm5MTlpzdTAKwcFTfVYHSFZxPEYnCj07MGvuqPQZ23Ad
            4AtiORJjC/1QcTiuEnJf2QpnTIZ7aNDFghnMTWDaB5bByp71O9NuVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T07:35:37Z"
    mac: ENC[AES256_GCM,data:qPkcG7gJkRDcMSBl4adwdOV9n/38FgsyfxkR8M2SJtH2hRy/Uo5TXshorSIAgG/iZT6g8aTqPlqGAHGPXVsCMMYjGaQITnw5zRTI8Vlhr+4hrsOetTZXO+feyd/MABtwMH9O5G051KY3wQMXrRkeJM7nDrQgo/4rZv2w2ewgOeg=,iv:/1abD0uc7j61NGcWA65Z9ESR22tsG1nE0gUrfDY7WBI=,tag:5mn6dzNp3bbrZoJckJp4jQ==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
