nameOverride: externaldns-pihole
fullnameOverride: externaldns-pihole
policy: sync
deploymentAnnotations:
  reloader.stakater.com/auto: 'true'
domainFilters:
  - g4v.dev
  - h.g4v.dev
serviceMonitor:
  enabled: true
sources:
  - service
  - ingress
  - gateway-httproute
  - gateway-grpcroute
provider:
  name: pihole
registry: noop
env:
  - name: EXTERNAL_DNS_PIHOLE_API_VERSION
    value: "6"
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: externaldns-pihole-secrets
        key: EXTERNAL_DNS_PIHOLE_PASSWORD
  - name: EXTERNAL_DNS_PIHOLE_SERVER
    valueFrom:
      secretKeyRef:
        name: externaldns-pihole-secrets
        key: EXTERNAL_DNS_PIHOLE_SERVER
image:
  repository: registry.k8s.io/external-dns/external-dns
  tag: v0.19.0
#logLevel: debug
