---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ./charts/

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-externaldns-dashboard
    files:
      - externaldns.json=./dashboards/externaldns.json
    options:
      labels:
        grafana_dashboard: "1"

helmCharts:
  - name: grafana
    version: 10.5.13
    repo: https://grafana.github.io/helm-charts
    valuesFile: values.yaml
    releaseName: grafana 

resources:
  - ./secret.enc.yaml
