apiVersion: v2
name: synapse
version: 0.0.0
dependencies:
  - name: matrix-synapse
    version: 3.12.18
    repository: https://ananace.gitlab.io/charts
maintainers:
  - name: halkeye
    url: https://www.gavinmogan.com
    email: helm@gavinmogan.com
