matrix-synapse:
    registrationSharedSecret: ENC[AES256_GCM,data:b+9lcWSPtLfeHvt55Ppn8lf0suuF9/uyTmghuLDAUhQTYqhzGOm42ozyoLtX+ckbkS4=,iv:rq3l+vBML6U8qftjTmBEC2AiZFl1KwzyId5E89Gw/+4=,tag:TqDgUaYeFu7ZCinYZcCmOQ==,type:str]
    config:
        registrationSharedSecret: ENC[AES256_GCM,data:Jh73NKvX5N0o+9wj7g2UK4QK59aoa5oD,iv:+WKUO079JxDMvbzr2iv1iGmDZra29rqbtN6aKS9wbB8=,tag:+1AGnaZaT67GAx3/U566Ww==,type:str]
        macaroonSecretKey: ENC[AES256_GCM,data:GUztA9XpcR3F7cUdCqNOnRo3GAOlNq3ItR8fPxqJ1oUK177djnKIWs8ejfiJBMnOIrI=,iv:C6X+97Zx1bifxomMc/JbFeTA7h/9w9wTBOEN+71h1uo=,tag:tP24SIlnLmWyJ4rnRgMydg==,type:str]
    externalPostgresql:
        database: ENC[AES256_GCM,data:vThguvZ9gg==,iv:zm1EyRwkmwbIkugQCiMdIfFbivOF/5AUXh5QW/WRIUI=,tag:5zRD38jKDDQxSb7wVS1+zQ==,type:str]
        host: ENC[AES256_GCM,data:pfPh+YgtYC+aY4YzeLiODvzcY2/X6+7HvkXsKLV1OwqoUtB4Pt3QhTZt5EVGks4VtS9G/g==,iv:iyj9n+7Dv+LSwk8oNQu0UfiCYNVibv5IRPvwXedYrxU=,tag:b2YOFMvs0jPyxrdoIWkrOg==,type:str]
        password: ENC[AES256_GCM,data:jKYz/+PBOJUjB5Yxl5a+Qg==,iv:VZMSlw2BMqjIIL0OKGK2sgmeSLPqL7bMHxHHDNoT+xQ=,tag:23ln01QBTdRT4WsCBIa7rg==,type:str]
        port: ENC[AES256_GCM,data:94MYZ18=,iv:1WCavD34HNSHhD5yHPJVSNXPizoZd2prtqn19AmILx8=,tag:8nBkmDfa6gpQLcbabwuZBA==,type:int]
        sslmode: ENC[AES256_GCM,data:3aho11yFEQ==,iv:yQme6IelZA/NCKRZHUKEYvhIsOM9HaX38XUTNdnrofA=,tag:nq9xPOT+gXG5wvGKGk+Y+w==,type:str]
        user: ENC[AES256_GCM,data:hUhMckQkwA==,iv:AIIQKMUnFYxl669UltkkZqpyCxQeR5dOOrQIusjKECc=,tag:TFXJndfZxt1aWPLXIak7EA==,type:str]
    redis:
        auth:
            password: ENC[AES256_GCM,data:q680e4yQ4AajD81aMaD6b5oSiFd83GPiX0I=,iv:krKAc+Fffoz8NjPZTVP5EJxWUEhpxV7QjKc4sWkEIKQ=,tag:FiFWcEHLZcyUppd+RaT9Lw==,type:str]
    extraSecrets:
        worker_replication_secret: ENC[AES256_GCM,data:eKvVYmBVf1fLpk9CmDYJVH9uzHOsVXeM3xY2QRX7kw2qgsB6POp2wNg=,iv:XvESuVe2RT9UdasyVxybTGle8Nd0xwsBW5Yvp/IY/Sc=,tag:CdNQxmSgoSV/H4/XHn0eIg==,type:str]
        form_secret: ENC[AES256_GCM,data:5tQ762L4bKN5Va16y9jVHl4eYiG1uQlw1r8E8HGZYFMTQx15H6TkXQLIEHGwjKUg5Ok=,iv:Xmu8FYbZ2OTbo/vopnQ+V18peoyohgsU2vFxOuxSH7Q=,tag:qQjxP/k6VEgBhuEKZxmrJQ==,type:str]
extraSecrets:
    signing_key: ENC[AES256_GCM,data:VZ3ckDRXZKo+4zZClQ1bTeSaqp4oAjN+V0kr3F67QxI+euKMFG/lXaSBZ/PACN6txE0sbP8oJEpyQw==,iv:8h4aCMka6DkkKN35z1R+R6tjXN2nGHc5NutVwCENujM=,tag:AoOlBj2XuqrEp+Smgz9xfw==,type:str]
    sso_client_id: ENC[AES256_GCM,data:UcQuZLCQNK59fcO1nYnSnZQl7Sf1pzfwb7g7Tatccts4wI77QxBMrA==,iv:zodgjzVx+u0xW95OMd3kANY6Ybjz6k1FEJfsK59gTlI=,tag:tfMsJOMuzGXPY4KSH63V5w==,type:str]
    sso_client_secret: ENC[AES256_GCM,data:WTDgQlhcA/ZZt3RvHpg5F79daCfSw0i7tLf0RZ/rjve81bcNCuhIODGTD/vmajQh/pP7ir6kjem22mLjFR2PyAxj91iGOTqXGhm389FCNHY+p5dWvd965iTqX20+gY2ETYq+hNv+fdfUF+ljpnOMfgSQebUy2NjBJJCHvhqSUFM=,iv:X5IJTrnsASJLNRIdGlLRCX1tK4WZ8BnnJOtgTEdOAYM=,tag:Sp0QxBh4I1uTeSysxcL9Dg==,type:str]
    s3_access_key_id: ENC[AES256_GCM,data:rBxEkjOpjkCJBDppoHX3nR5Kbog=,iv:BAgNpoUqVD/CVNRfiYirOiF86qEW8KToguaYa0yQS3A=,tag:6SRJ5GGEdi1pP+tayaMTVw==,type:str]
    s3_secret_access_key: ENC[AES256_GCM,data:v4pd+nE+w5HUhQZ7KNbWtwe2q+NlbCn3E51o/qtlbbqvSYaEjvu4z/8Fpw==,iv:hEr4H4z0/Ra6FWx61IvjcFCrlLtuCxQFeymFb83qsfQ=,tag:hpQy4203U3YofHcZ8UDaZg==,type:str]
    synapse_shared_secret: ENC[AES256_GCM,data:u075tugQkf2a7doRlgDHf0BRMGOgPWnCZ2fN2KBaHMj7rl8TUhKviLy2rHFubmNjSgOd8X6Yf+ZTLzhXn6NyuK3VzirR36zl+0fqjF7iPw9pAdeSDu6xixgo1OgCswWYvrXDRTsnNZh2qvSCTKCaUnHy+T8GqLrzLEfdQww3Ipw=,iv:BVEPuCIpn++UgAy6ouLhkdrsY+bGxDYJtrVSTlqA3Oc=,tag:Q0S4ptZHULzTcc2poVSolw==,type:str]
    worker_replication_secret: ENC[AES256_GCM,data:WRfQ5Jk75uAt1F3lHpV2RYKh/ePouV0cPyfk2yk0OwjeFiP0mOoW1wo=,iv:C9JBXznVtuprCimDx1a1c+N6bd9ZFTfhppPdHVlK9t4=,tag:/mkl7no82N3zqz6CwgahpA==,type:str]
    whatsapp_registration_as_token: ENC[AES256_GCM,data:rdbIoGgfKKHQRHFZmUXS1/yvkPRhnwi8psfb3AtL8M9peG/VOyA5iY5ApiY77GNvgYRzzIqkctIwiG2tZDNCwg==,iv:WKkz4b0W80sFLpokuR1T+wDyJ6mMQUl87DBOcepe97w=,tag:Esly5JE3fPDB+z+WeAOV/A==,type:str]
    whatsapp_registration_hs_token: ENC[AES256_GCM,data:hq1WCzg5Ed2akAVLIsHC3r9RmDWGfwpGYpfQBEFhkXI29lRVgv5R/OAwQZiVH5CfXQpAKRBfeCpGGrKTNwXTww==,iv:wciLmvZvYVtudIobu5G0XwaTW890rx2g85lQenrgjqg=,tag:S2o8MrWzE9tV5EsytUNQzQ==,type:str]
    whatsapp_doublepuppet_as_token: ENC[AES256_GCM,data:enqM9Mc6H3UbnHHqSx+2z9GiEUSCpGz2UVIbFk9y9EcxjrPdRHRoViVsgs1jgzsc3ZyUSA8a/ugSzTIRYj06Hw==,iv:wAP5gJgIfwIOQWFOC/GqewjebtnsNzUAMOsroRmvA6A=,tag:wwE3MUE8b/2eXkvYtbvyRA==,type:str]
    whatsapp_doublepuppet_hs_token: ENC[AES256_GCM,data:BnKcv85eXSmIqTO9Qo+0ZKRDt8UHar1B1z8/P5YZ0PTHPVxdgdmoR5hXORc0zJ/A4/22itOw58GNBvKM34QmPQ==,iv:qXX1+cv2nDd9Vdh89lKwKmjYzsz9/g2m2N2YDxLfUrg=,tag:XTF0t8XRCnv40baM1C+oSg==,type:str]
    googlechat_registration_as_token: ENC[AES256_GCM,data:sVMfxDwhI6INV/kbNwxTqQmONBka0YbPB7vjZDQYawj5+xThckYI+jnja35l54/GvbMS5896RYqEJqEzfjF2HQ==,iv:z+lQWSvQGmY5Y/ijONYmsqM9vyuiEbg1hzM1WKc8/rc=,tag:X3gfHbCg77o/JTSE0+Rzyg==,type:str]
    googlechat_registration_hs_token: ENC[AES256_GCM,data:GyX6uFKzsmQ33EvQkC8LF9q2rpoCbUEqYlMT4x/qjaN3CzbSuOD2WoDF/6RR1j57pu4IpFwCullEpR17rJ0IeA==,iv:OtyzRBwNi2fF/kx6bffMrVWsjw/igGeesyB6sd04Mb4=,tag:ec4bAnEYsI5DgVGmIFxowg==,type:str]
    googlechat_doublepuppet_as_token: ENC[AES256_GCM,data:GtGa3s2kZa5RgCM6bzHimgphbopZkzRxbj9XnD7s/qPIVI5cuW8A5WdaDQOPq1ZEtriFJqeFxpnp34Lasc8Vtg==,iv:c5SYvBYinGQCuEcQxcaNVwWAMmmkNAGNAZW9tPt7Ud8=,tag:Awo4QmzvyuKKs2OkCZCd1Q==,type:str]
    googlechat_doublepuppet_hs_token: ENC[AES256_GCM,data:uSLdZHgGWOLRit8H1NjgWk2hAcSzi/f8ufl1bIajDQLwpO2w6Hierhq7DwCRmoZ/5v6481OyKROIlA/kIEq4kw==,iv:Yb8oiKd11fi4FjGZuBZHn6A9HN43Mp7z4069TzhXy5w=,tag:MPLWgKrQnOqiDaYE/EHijQ==,type:str]
    signal_registration_as_token: ENC[AES256_GCM,data:HZzmLo/UHPsVsRIt8k5h8kPMT3PBC1nz8DJTaM/KRGRLsVhNTdeAD+++yttNKXvnlMMfs7lAcoA6RuTHP7BN9w==,iv:d1/UQsoINgmdQXUiRdC5ZXl/wcCBfzE4ttCF0O2hw24=,tag:7NC784tMyKZxqAHvYVCY0A==,type:str]
    signal_registration_hs_token: ENC[AES256_GCM,data:NQuVPCg+Mquj+rFSzLUm5MXcxzPtRduNpjwa+eTRu7ncDdUV1IawBAAoLAKmoMUEMgHzQTAeo7JAYiChSh2ixw==,iv:OtVpWX/FkrucxqW6lEVExX4QEtuHV1/hD23WxCgw4ac=,tag:a0YG8akNz10KDfkgWPsE1A==,type:str]
    signal_doublepuppet_as_token: ENC[AES256_GCM,data:jqKq1nL0FDDmNXsfBBm+ZOXBz/pK3nfs02jI3DcqhWEd8JsCeegFmeRMqtxIT/kx3AKBT4Zq58go06nX5ctrkg==,iv:YFPEYVe4OV7ppKlVjLU+Bn/xoGSsB9SHQmdbEfbTDUw=,tag:1vasKWLPCXzYXcjfFHys/A==,type:str]
    signal_doublepuppet_hs_token: ENC[AES256_GCM,data:MKEJfoCW9OAS5YN5IA7zvpz1DxZ638HMhmYAGmo+18US0Vm25STtTsSmS0cUTWFg/I3FFhGLbUJsluYcusL6yQ==,iv:cqBIMwPNYzdDNF6tyHolVhQBlqLRKWOXJUS01jaVPEM=,tag:XHEcv1wDvqpl7vS0+t0Xpg==,type:str]
    mautrix_gmessages_as_token: ENC[AES256_GCM,data:yCcNGtxsoEfdb3GqvxVQuxX4gCbS4q5h3gnvtVXx7xClJ2hqwoh1plP0CWj/HAXVbcSFi2lJ3zLseADXuc2kHA==,iv:+7/Jm1D2JAYi1EgBcYQYv6cfaq8gmAcKxebKp3B6Kok=,tag:sZ9cGdJh1X/ikcRLHUt7sA==,type:str]
    mautrix_gmessages_hs_token: ENC[AES256_GCM,data:l7xzLxN65H0ybbfEsfyJz5j/SkwnjChYD6bYn5i/3K/gCjKkisVzjBf+DwyGgxnlgAB6jLzhZ3tKmH2vF3elAg==,iv:KTa39vEpTtedwu+KTVgO2qfciorbXIi/tV9GSs4WAO0=,tag:ClaWehbHso/G9yT/qE0gTw==,type:str]
    mautrix_gmessages_doublepuppet_as_token: ENC[AES256_GCM,data:Dhb9rbr2zMlzMuGeTGpifGQDh4nq7U/qjcJ5L+zxNkNQPISyC8vKi/1/YMvIF7k5DvkO0Uae5LG3MFFbJIOvvg==,iv:7RmDjh6HE3mZrpKE4OjfgTNTeXlaYQF82D+hYNWPDG8=,tag:r1AorVJdzCIT5tzazMsFHQ==,type:str]
    mautrix_gmessages_doublepuppet_hs_token: ENC[AES256_GCM,data:SyuhgP1Jp6A1vMR6hN/T4tyhxvxfn7usafDO6qYZZmYNXlOmxRXQUfYM7L6FxJj1YfVy6VIGl+JdKKbW2KbPaQ==,iv:+mLOFjvK4RpFrtdVNaaqTeIa9QpMjD557VTJynYClCE=,tag:Jr1rRUiH5tE7tjQeMD2QLA==,type:str]
    mautrix_linkedin_as_token: ENC[AES256_GCM,data:/o1WC4b90uBndbhfRyMzKvoJyzpDbtcHrEi1kII48QavxM44c6IpYdmfHc2OGSIcDpUL31Ao61dPFv+9I7enrw==,iv:lxbJv7W+C1oE4AaHIeDh7d07+tDj7BoYqGilY+yXPhk=,tag:UlkfyTDIVSXQIkBOunwPCA==,type:str]
    mautrix_linkedin_hs_token: ENC[AES256_GCM,data:OvCi/9sihrprD80aSkjqv5biXqz5LN4Xi+BVSdofsehn6fsMWNFwJ7aT0MZOg8YsPPV4+yKYn+X3L31YOreqPg==,iv:npqt56IyUdc0plizTUiy0FO4S3Gj4TFRFKID6M6oK6E=,tag:ekjKjOwS+WLGL/c5dfOyyA==,type:str]
    mautrix_linkedin_doublepuppet_as_token: ENC[AES256_GCM,data:fgpGmIe0uqHR71spsvbhRBF9oNWYRvUirm0xYAV68CUi74PGaIaGJhVFR9BkQT2L2eUr6sVE+5gyxb9lkgCjfA==,iv:caQDhYLgBKsqlTJOXHed9zCs/30nkJIwmDbDGvfZ+mk=,tag:sXzDZOSZlTmuCPmhWVN8DA==,type:str]
    mautrix_linkedin_doublepuppet_hs_token: ENC[AES256_GCM,data:rTK8dFcawaEMSvCYYpu5+oKgY1/db7ST9LV1SnEXXhAciAE74XY810VYY4Re3uYNAyPykg5yIOU8i0PgL9ez8A==,iv:y471gWO29dmrTyJ6EhMcBGTVtoJ7kJsXDiWuYPF4yNE=,tag:exCS39jortLjNCuDHh1NRQ==,type:str]
    mautrix_instagram_as_token: ENC[AES256_GCM,data:2oLcoN43ceIsjbc40lbV1988c7wdHqnobBdLO8txa6waVm8wHmi7A1qxbihwRySGVsQ62Z6R+G7Rcm14AuCFwg==,iv:7byr0TtWWeg7jTTZmjm3tFHZSjQrgfiQmOy4a7q4jPU=,tag:R5EPvuXcQon8oWHqcEaZfA==,type:str]
    mautrix_instagram_hs_token: ENC[AES256_GCM,data:94fjPd6RD1O3UUoyy+or8xne1dYz6ypP/62rE45cOQHUIeib2Zvz+mzHxZlsIy66KOPE7OPeNybdn0FncDKFUA==,iv:pEGAUTX00T6EPkR5ANXZGIbcTJW6nEICXFN5m+cG2lA=,tag:yaIhPwxpgmMMdI7uAVXJzQ==,type:str]
    mautrix_instagram_doublepuppet_as_token: ENC[AES256_GCM,data:y8xhccpDlNKAtG8u2q9tOProTKdB7kS70SEImgT/a6Yjaf25GlAziNRXg5E1G7NXGyZ861QqwZ6ewLW+7CyTPg==,iv:TEj4m+yXLjVJeB13UF8lXkYa45wyF0X72M96PzSKOkM=,tag:6YI35R8RP7JQHT2KO7NVvQ==,type:str]
    mautrix_instagram_doublepuppet_hs_token: ENC[AES256_GCM,data:3az+PEDNJSXAxAk8Oo5fsHq4ZiqmSARj44teXA1LPwcaduBpnqmKvrjA8gwJyN/OFZGD/gghfnM4Yt90fqCrAw==,iv:FCDGrDEDgCgk0oH1dffUSPsgOxASO6YueDM7q8+uckg=,tag:vvcDUOVoCeL8kfUSeVs49g==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL21pVTBzWjhxRks0dktY
            QlVsei81bzNEVFY4UXVXWXpNb3hnQ2w3dkdvCmtjNzlXMDkxY0lqcXNDZkxUamY3
            OVpvcEVhdVFGbFdPc3pyd2VvRG1jVWsKLS0tIFhMMnhKSURQZzBEZ2dIYjE2WXZR
            WEtsczhMaWdpSDE0QXRpcFFWeGNnTlEKbrlyFI1bfWjYz67a0stywg1/62O86ZR4
            DvrJbychn53RJxevRt2KjrlzUBfBB8o0G5YGOeSPiY0MM0K+Pm64dQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bExGOEphU3BDcTMvRUpk
            eUJ5WHhSZHFkaUJGUVM5eHBwbWZBUUw2QUJVCkZuejJubTRKMkh4SHU5dVA3clIr
            MVFWc2JqNHRkMldtb0t1dXZPb2hYaTAKLS0tIFZzcGJqbHZwSFJmY2pqNFRFZmpW
            UE93ZS84YjFYek9rOHVpV3N0dURsUEEKPZdKXHNrr/XaNhokrkOWcsyg5I3DyG+z
            GajJ1jVAZ/h81iZJyjD98STBpG1l23C8PtjwcXaGcBAnMp4Fkl4PPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBRXY1TnZvUzI4RHN0YjhM
            cEluN3YydEFRa1MxdXp2ZXJ6TXRQRUJPQlhZCmJpVkNmVWlFeDhKamxqLy92d2l3
            enZiemhhc0NramZ0Zis3N1hYaEY2a3MKLS0tIERvcmRNbzlWNHFUd2w2Y2Rib2tw
            VnpMKzZpZUNabHFSVVBuZXhEYzh0SmcKUHSn+T5dpunhy9mDOpugUlKMS9US1b6D
            Z6l3lcyFRoSZ9o0YzJOm6pd68UPsljp54skc8SoyJ4nNcmjG6cM2gA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVDg2cDVuY3JYcC85alVL
            bnpSNTQ1emVPWG9pVVQzdnlPQnpqZ2NBOWs4CnZURG01ckFMSlJFd1NqQTBRdUdZ
            RE5rNkpRZ25FTlg3STIzSDlkMmZFN2sKLS0tIEJTcTZDaG1ISzZ4bi9VZ2ZkM2hy
            QzFHbUF0N3pKRUpZbkFtUzl4NzBpS00KF4fvxZz+d8j8Us1VqTIM/9QMKtIl3EN1
            2AsNfg+p0Og3PPsXGGXxqk6A05KK1Bn5kXoxia7q1ebrMHjiHC9Plw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQaERkdWNxdkk3OFRSOEtW
            Y3BJMjFNMTFtbXV1Vm5qZ1huK0JIcUovK0Z3CjQ3ZFloTG9CSC9PcCtxd1lCc2E0
            WXFMTThvSjFMTG01NTZ1K0hrcUFjZ2MKLS0tIEZVTTlkRkllZmpvTlhqTVhBSG9R
            R1l2M2s5bGhMbTFJNmM2UkRrRTNYN2sKbwhykm1tz0SQql2nlQs7r62ZUWM2Lir2
            3/+eUpnVXXrv181i6QwV8yRW3s7PqhDvyMlvoU/xFNuzCWt5+dDv8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBnS01Q
            Y0ErZy9ITExIVnljOENjZ0x3V3JOSzFWTVBteUN0L3RJTEthZjJJCk5WVWp2OTVx
            Zm9tekxpaXhBVTkwUEkwSU1LRzdsaTNXQ0lPTVJPVFUrSmMKLS0tIGFHOHc5bUcw
            MklmRGJiTm5nMHliRUxucHJaVkFBTGwzM3c1RHRYSDZiMlUKloUL2YsSR2zjrMJV
            Bt0ftRDcGk/9tvtFg7wcc9LSX059yqYmc4tN0ohy1jnyfDui4qMVCZlVGK/edz0d
            Y+9dKQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaEw4b2RaU2pxM2FtdHJI
            bXQ0eFhwL2QvL20xemE1NWt6U0lxK0ZrY3hNCjZMeWZwYnlCb1Y0cm5PV2xHeHhF
            bWdveVBDck9oM3JZSjhqNXhKeno1VWsKLS0tIE12cXVyS2RHeVRRZS9IdG1DR3p2
            ZUFoOHlXTlV0c1BRcDcxSzI1Sm5MdmsKVfgfUk+9SiYtEtJgwT/d3/msy6tnZQr4
            62iisxeCjtpH6hQ55tntTS/YpN3fjRc2hQG8ijjfzUmLIgd1d9eP/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RGFSK05HK3U5aXQwTm8y
            OW51TzdmajdkNkw5Wk8wY1BwaS9xSnZiK3drCm9JRXUrVW16aVNiVE1ZWUwwWHd0
            SDltWTJUK3p6SExUZUsvY293UUdhaXMKLS0tIE5HMk9tTFQ5bUc5ZkFaNDVSYUhi
            YU5xSFc0cG1oSklTZnlpWUJYL1FOVVUKG9niTZM7kpkq9LSIwyP82Ij6jbcpfb+3
            LxOmFAm4N6/6SPwxD39p/r9GRUQ9d0IDnk6Cnzmqt0uNBwwyf5XKWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaXIrazBnZDNHd3d0YU1O
            eUZXVnZsbk5VY0piV3pHTGVJM0ExUHQ4d2tJClY0aklrcmpUSFFmd285dzhDd3Zm
            YThSOWdtTE11TUFidnY0RC8zVlNlNFEKLS0tIDViV3RsZHFoL21wWXQzeStuTnYw
            Qjlabko2dXVzZDFYRUNGUXNvR0lXRHcKtwo3qljbwxgzaB0aTo7B9HSoMjbtgXO4
            AawtwkjYyLDmGL5p70aLe7xvbPO3LNlEO7DExq7dlckkuhn89c4PeA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQllSQjViSGs1UGtxMzMx
            U0RBUGtFTUo0SmNZVzFtNnJsNEJ3NGtXSGhJCnB0K0FqUUZWTHpqME1OUi9WT3NE
            YzY4UGpXWEFodERteUJnS0VzaE9tZ2cKLS0tIDJZZUVMUzZHaFh2bWxMYUtwY0dT
            U2JSQzY1Vjh2TmlpYU41dFlaUWhsc28Ke3dvV7BjXp6DPRXG4pbqpJS0cw8kNCku
            taAONkS5wD9MEyvMFb8wHlMnkvzFtiAfe497VHIqxHn5Iiopj6teFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T19:09:28Z"
    mac: ENC[AES256_GCM,data:iKXBlWpwAGfjYkryi08VrrX6NGRSuro4L9Vl0GYC0sk1GGMo6mWTK2T4CgthsF0X5cjDzTVYF0fhwmWqEdASAoW7hZJ7+7n/4YD1AHyCIQIddM0y6qb22+5LEMxIH5Nu7Cnq4W77eaGZv/6x8xl1Bck1PnH7Np0wYPOMP0AAjBE=,iv:ZwdK5C1maEjYUuPY6crgEpHoupBevUKZF4Sy0tJHGfw=,tag:QTrGSPzbXghhnQbdESguCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
