authentik:
    authentik:
        secret_key: ENC[AES256_GCM,data:40+EIODRfNnU5QWIQNxBid7ptO/2K9ZCTxa6aq9rbN8mpr/R,iv:2/QyoolBLgXe3o2qlebf5HT7BjKKMgj7iQaPj14Vr3g=,tag:U0ccpbeD95BLOmCGfpUVpg==,type:str]
        postgresql:
            user: ENC[AES256_GCM,data:PPhG+r12wRpY,iv:4Pu6epzUiS9395a2uXRHaT0A/8Wgena/to9dOS313Zg=,tag:HNQ5Vj44bmnBnCRvMYnWow==,type:str]
            host: ENC[AES256_GCM,data:RTg87ODryt+p+CJ8DNgRgPJrpzZ7Gh7hKiTrumWBPtElyWHuBtZK7oAuoarSIloSpVg26Q==,iv:9Nay6V6mzwxMoEFtGRuumzQDQrrMnCc8qnR5dQX+83w=,tag:fpl68SjrdFMJl0MyNkaOeA==,type:str]
            password: ENC[AES256_GCM,data:38ANTqQPFIXSH6WG0x/MzlrxyegmNwLz,iv:9vr5cshTNb6AK9t13Yj2ZOWXQ1fFaFREdXvBDfUQ9lQ=,tag:qbH9PlYjfVdj+cdRvuAf1A==,type:str]
            port: ENC[AES256_GCM,data:kKgC1TQ=,iv:zuUjrn/JOFCY6e0D1e9jHkTcUG+Jz49D+pSQdjElqqc=,tag:5bd3n0MsYK1bvwbt0/pLNQ==,type:str]
            sslmode: ENC[AES256_GCM,data:raG9z+7JfA==,iv:0fwNyAuWDMPD8ppoWDOBFyv5G6Z94Ay3FVUKseMHj7g=,tag:TqRxUpNP6CxDSFBlNA9SFw==,type:str]
        email:
            1host: ENC[AES256_GCM,data:kcIrfQdqDLesgX81BPSrdQ==,iv:M8Gknww4efYBuxWUXH5l1mrEqDL+k36b8pY/xRa9lMs=,tag:jaS6c5Ap/yuu9VFY7orv5g==,type:str]
            1username: ENC[AES256_GCM,data:0lBdrzkPzFnJYZlv11nSCxR/,iv:EQ6Oq/mm78F3VpDQTHzm4ftoP4UTHP9Gnx4oZHGNvRw=,tag:rphG/Qi8V+9J3vCuRAk0fw==,type:str]
            1password: ENC[AES256_GCM,data:BLGNgQl5zV4L/OfgIs43PtHOBNv2yzorTd8pzs6zHWY=,iv:294yaKIuWiSj49uCtg9Ak9Vzw5jgKiXZPY/4tuKg4Qg=,tag:7RMrRPe0YVgHLM9uwWDa3A==,type:str]
            1use_tls: ENC[AES256_GCM,data:26l3/g==,iv:dBDk/kd6OAHX3APXC8SGVyt+RBEJxvFc43n8MNOY7pA=,tag:/KFIxfBj0Ir6ZgZUP0B0WA==,type:str]
            host: ENC[AES256_GCM,data:a87og9eKQ5PLMrmZwwjpYV11dipoWiy5dtGd5MLBLBbyTcPv6XE5CTKCYyA=,iv:LSz0svdtolFTDsTZZMsuyXy2q2aYXg9pEihuZPhoXA4=,tag:+hbDSrSt2emjrwfOZHCj1A==,type:str]
            from: ENC[AES256_GCM,data:L9q9ALKfhyr12ouEgVI0UUo=,iv:OlM4hMbfuzozQtNso1AoCmT+tL/IZDTG6MfmUMVSppM=,tag:d2/9WFqMAb0kAmISugLr9Q==,type:str]
            port: ENC[AES256_GCM,data:CjaS,iv:ckwo3mGWo17pQuaYH4EW7dozaKFmNVPfEeTJeKGIGHk=,tag:EW8gHyqqkwQJ3Zy+dnqPTA==,type:str]
            use_tls: ENC[AES256_GCM,data:pRczjIQ=,iv:/yShLtGwKiXvnLsRxqgVQ6mW+r10K0+KoO9Ico+KnDs=,tag:MZc3YAdMQCZRp6OwK5LV1w==,type:str]
            use_ssl: ENC[AES256_GCM,data:S3abOjk=,iv:Yw+ACYe7XTpN454LwH2lwoyYNC+o9/a0XN1sBgJfv0g=,tag:N8rbANsXs3IYPLIRFU8Qww==,type:str]
            timeout: ENC[AES256_GCM,data:rZ0=,iv:1DSFedmF0OXmZoJAudoLVoy+fjnnttaSb5rMTgdgwGk=,tag:vgh1Oob02MKbYE4tncNCWA==,type:str]
    geoip:
        enabled: ENC[AES256_GCM,data:FxUW9Q==,iv:Vc0YGOrUUzE/2HbxTIQT+ArlegmyY1zIHQy4IKrZL4w=,tag:lfmaj9gNRtV4jSHQdk7UoA==,type:bool]
        accountId: ENC[AES256_GCM,data:w7gIQwEr,iv:zZS5FHolcIo9CAIulUNNXE13SjnSZNDXFWCcWU0BtiY=,tag:exa9p9En7Ls+z22uYJfZ+g==,type:str]
        licenseKey: ENC[AES256_GCM,data:B5/kabiVY10DxMUCQ2xyiw==,iv:MpSZaUItavg5cMcdkTpso+NP/aC74YLnRZHp56lfqYE=,tag:kCGfwNapwK2aA3i2oJ8diA==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WnFBek9ENk1TeTZ5N3Rk
            TWFJZEJxdzgwbnVHOXFPVFpMTmNLOEpyUVhNCjEyeFlWT2dwQlhFWVpOYTF4L1Ux
            RVIva3BJVjNoWXVwQlAvdTc1a0ZQTE0KLS0tIHdFQTVESGtGUmpnUW05M1lKRG1X
            a3hXelNEYXFreG1xUmNUQWN3cU9vMTAKXnHA7pK8gcvK2dgXt7sCpgTC8sfZ6CRM
            WJGP2siiHINAeNBnwURYDSbYytjlHfIybpJi22OhBpNMaWHIPojQ6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiNHJoQWVEeGQzQlgrNHdD
            eWQrY2dONHFpVERIenpqZFE3L0NESDcyV1NFCmhPSkZ5K09mRi9LS3VmckltdjBh
            enJaMWVBaVMwQlhSOThCdmNtcXRXWWcKLS0tIE9KVTRUaUZGT0JqcUl4Rk9OcitR
            NE5kcXM0S0JESkhkVU50Si9MWUpZOXMKWKFJTN+ApCYO4cgveCTpwbGo0YLXt1Iq
            KfEXoNT3lgU3TJVmrw3EkzdMamxfr9F9QoLufe/BGebcKAwuhWrMcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNDRBVGFLNnBJQy9ERDF0
            aGV3Rk1TSlFmQjA2b25XczQ2eUFmcEROY0NjCms2bCtteWN0Y1ZaY0dHVVJwWG9p
            cmJraU5DQ0luRWhDRlhpT0luVTkrQ0UKLS0tIHpRTWsydTdUaGlaaFppM0tSRkV0
            OXovNDhzYkVNVE9PSi8yNWRDS21sRzQKvOLgDwyY4DS90eL9pvp7/COz/i0vcWLq
            CmGhxEQByvb0g40FheKJk+6gNnFLrk1xR/+2RHdJ5LfrJTG8nwPXBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSlNlZ1U5MkxPRWhuOE1V
            TjFaNzFsMEF2bjNwMWpXMmtCcmtvaWtoK3cwCjIzU3NwMzlUVHo3N1VUOXNkakVn
            Ym9YNHBKMk9lSVJpY212STV0ZDk4cDAKLS0tIDRUdDFYbHRBVHFRM3RaRDVJTWx2
            dGd4TjBnaTdDR0lXT0VYZndwWGhsQ2cKzzXxM8jsw2PLNyyjdb6lWNHbzHmV6yix
            GPdaNcKKTkrguFQPemVxL8QgVpyq77WUhdgpwMIEB/XMrH073inbWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZa1Z5akp3ZmNMZEwzZ1Ry
            OU8wUktOOWRkMGtXTkVGM3U2cTY4L2NJY0ZvClRCZWJxWUZyV0ZuY2RSUnh0dHZ0
            N1k3Mm1ieDRPNjZQdEFSMUZOSnVGemsKLS0tIGJXVVA0TElqTHpJdXVGN21uQk1l
            dGxXZUR2dmwvYnRiNkdmODFvTyt6VDgKWWjHDIwSc9LQ/vhG1vgJsJbrF3uDSbkR
            Rd1CKIxR22JkpxG0pT/k0o1j/05+IMvUkL+lxd/ytqfvldSda9iS9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBBS3ZT
            M0QyMU5Hd3VlWTZyWStrUHJoU0lYYXd4SjVEYmdvV250YWs5V2o0CjRlUlVJOU54
            QW9FNytVQlZnTlI3d3Q5ajR5U0lxbzQ0NTNhSTlRTUlwZUUKLS0tIGNmWUJrdzdU
            THphc2NRTlRDSXJaZzhrckVGSkR4SENHL2x4TEFaV1hwbE0KOXu/89uJvC/BLDIm
            h9Q0ZNPWmIjpAHo023k6RenlD2DeN5iXoVyxVJSQnrhX8BDKNEwuKC9NSgWcM1NS
            PjMYOQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHL0srSmdpMGpPdTNkc3NH
            ZzJ2ak4vemtCMkpsUkc5RjlWWTZPekRNb25BCkViNmNHRFBiMmJLbjdlN0JmajV3
            VFpDV1lDNEprSnRxbGZ6WTFCQS9YZ1kKLS0tIFhsUlNYcWprZituTHZ3VEI2Y1FT
            TEFYcElIcXFnMkU5aUZFZkpzNngxNkUKc8KeFMX2ax13E0jWbxp4gu5Rh89lVXB6
            ho8JLZ+J73uzuo332XU8CSImuOaKYj84QziuyVxiqSXllwXLnSBexQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4cEJpVlJDa2ZYZmFoNjBH
            enZWZURrK1pDUTNPZG0ySHg1a3d0MDExNXk0Cld4aENCZ0lyMkpKNEpJSnNwTVg3
            YTYydlQrSk1IdUQyZit3U0p5cVhPaFUKLS0tIHF3N1RkNEpyVjZlSEdiR2FuUWI0
            anpqdGNLSGlBSEd2UDJCbU1ld1pvdkEKN2ONj967FZCa30nej3P8Eq2B4oLofO/j
            TFwT0varM8kZVBrrXXvsHU5HlIO19OioIvh0Ufm9fA7tEga7IkczLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZXUxZTRWLzNoQ29KQmFv
            aDJNZjMvcUZ4anZUbGd6UjBTZUdEbnFjd2hrCjhsRUIxS3JOVHBwRkJMRUVVdFY1
            d1BuMTB1MVU2eU15VjcvSEJzVmhYUDAKLS0tIEhzNU1DNzB3cnJVM2JvaWJsOEhi
            Z0Z6Z1RxaU0rTjF1c1dqSWxnMzZhaHMK3/lkY9OVeOJocAnQi1QYneX3NTYePMpO
            8qj/px9jTEU1X7JfenLUwxQQzkUASOg7Cof+JckHJc7DcUxV+DQ5mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT25ZS2pVTHlxZkdoM20y
            QmlUNEcwRTNLUVNac25zTUFleE51dHMxeDFVCmd2YU40RC9NeWtoYm1QdW1HQ09L
            SjlvdXZhc2p5cUQrVUdSNkJkbzJPL0EKLS0tIFJKN0dEUmt4Z0hZelFSY0ZqcnRJ
            VFNPSE5jZ1BYTWlkV09kbTU3bVJmeHcK7qOhDcI+/A1YzrQakBpcxLYzBYH2KpSP
            MdJFZNrsKttu//DDbcKU8yvY0CGlUDjjoPIbgXKL0q10TPAsPiVwuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-27T05:06:15Z"
    mac: ENC[AES256_GCM,data:S5xbe3RyPJ0sZEOf2EhSyT4trR2tNuV5bT51XJQfs/Mcu8J6HtQ4Vv616f4BQNVIHjoqnzyU+pvgc7Vb9bR4D2Tg3v9Ta5NV2TsIt0c9XFWmrrRX7xZln1oAHFDwQ45r0Y4HlKsaES8B2zQy1XElyDrn/apKjxbx8O9jfLxLmZg=,iv:tqDxnTnl+3YqOjOMGudX6C13iGdJ4UmUf0O46deYxns=,tag:5xJmjcO75pnv8STQzDBo0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
