---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ./charts/

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: app-template
    version: 4.5.0
    repo: https://bjw-s-labs.github.io/helm-charts
    valuesFile: values.yaml
    releaseName: navidrome

resources:
  - ./secret.enc.yaml

configMapGenerator:
  - name: navidrome-configmap
    files:
      - ./resources/navidrome.toml
  - name: litestream-configmap
    literals:
      - LITESTREAM_DB_PATH="/data/navidrome.db"
      - |
        litestream.yml=
          dbs:
            - path: /data/navidrome.db
              replicas:
                - url: s3://halkeye-litestream.tor1.digitaloceanspaces.com/navidrome

components:
  - ../../components/litestream
