controllers:
  main:
    type: cronjob
    revisionHistoryLimit: 1
    annotations:
      reloader.stakater.com/auto: 'true'
    cronjob:
      schedule: '@daily'
      successfulJobsHistory: 1
      failedJobsHistory: 3
      backoffLimit: 1
    containers:
      main:
        image:
          repository: ghcr.io/halkeye/nortverse-downloader
          tag: 1.6.0
        args:
          - download
          - "--output"
          - /webcomics/Nortverse/
          - "--flaresolverr"
          - "http://172.16.10.10:8191/"
          - "--start-url"
          - "https://nortverse.com/comic/valentines-surprise/"
    pod:
      securityContext:
        runAsUser: 1026
        runAsGroup: 101
        runAsNonRoot: true
        fsGroup: 101
        fsGroupChangePolicy: OnRootMismatch
persistence:
  webcomics:
    type: nfs
    server: 172.16.10.10
    path: /volume1/Comics/Webcomics
    globalMounts:
      - path: /webcomics
