---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: radarr
  annotations:
    postgres.db.movetokube.com/instance: postgres17-rw
spec:
  role: radarr-group
  database: radarr-main
  secretName: radarr-db-secret
  privileges: OWNER
  secretTemplate:
    HOST_NO_PORT: "{{ .Hostname }}"
    PORT: "{{ .Port }}"
    
---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: radarr-log
  annotations:
    postgres.db.movetokube.com/instance: postgres17-rw
spec:
  database: radarr_log
  dropOnDelete: false
  masterRole: radarr-group
---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: radarr-main
  annotations:
    postgres.db.movetokube.com/instance: postgres17-rw
spec:
  database: radarr_main
  dropOnDelete: false
  masterRole: radarr-group
