apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: n8n
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:h4lu,iv:Ps1aVAByzO3AiTjkwHmdkKFf9G3WidGP9n2Buon4sx4=,tag:6jE/JCFEktJ2xV7uQltwqw==,type:str]
          stringData:
            N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:lOIl17g9RtgFGrChSII3T0836fq+uYQZ+UFee3NKBn4=,iv:5XuCzrAjg1IrgXWcnAN/32P82snODJd7kloKXXgAQmQ=,tag:dyrNu9fFSuIRtoyZbxwjVw==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZStjTm5hZUNZVk9NdzA2
            MDlXL3hWNlkwTE1qR1A1MnBUYllZY0ZZL2lRCnJYTGdUSEVuZ29tR0VNelgvSmNh
            akx6azZnd2hJbmViNHA1OEN5eDFJOUEKLS0tIFlZRlFNelBsWG8wNXFWRjRlbEhO
            dDlYdnM5SDRLYVU4TFhLaTYzSGdDTVEKClbg2QFyGl6QfVOqG+YCa8GbYDSI74bV
            FW+NS9A9O7SdAGqM7iK829S/FIa99a7GxtSjOtrXkPX3qeuCHVdq9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbHBDeXR0Vi9ic3d1YjBY
            YkplaVAyeTlYM1JFU01nSGUwSXY2MzFJcVNNCjU5RFo5dGVrRkp1L3dZOFZDT2ts
            aE4rZzI3OVpUbUxxTENGNkdqUW8vYU0KLS0tIEJNelAxTXpQTDVTV3lTVDRoR3VI
            SUdrZzVBQ0E3QXUrVTc0S0dWMk1mS0kK45Jedvmm7UD7hA92EIphdxBqIe0hQD4V
            opheQ8VgeS/hlI8KriOQVPA6WMVXjg+ISwYWmH/dkBI8P/Hhzo4Big==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdHA0YmZVL21WMk1JQ090
            L05uY3FHRnNjVWxsQXo4aERTUjI1M0JZTHc0CkhudE56YUFOUzF4T1NDdmxHUW1H
            Q2lDTWQ3L2pXcG5INUFJOHlONGREQTAKLS0tIFY1YllPR0FsRzdqWVhueVhwa1I0
            c1hjanhkWnJQTlMzdUlRVk9XYU9wc3MKII5J1qSRal4WtSY5kzjA4McPRuoUacvc
            BR7j9v58HZh1zeAcwveIBkE4j12afWgCb9o/6eT2cI7xqhnIasWhvQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcnFYMkNvWnZHanlJNkpB
            ajR5MkRFbTNZOHE5dzcrQ29oRFhSV21wSndjClREUy9YdTNtcnZZZCs0WG1LUFZl
            U1RLTDhKTjlQWXRoakpuZFU3c2xuL1UKLS0tIG1lYzhXM1lCZTZ3dEJlaDhkcVE5
            K01nZEtFVW1HSlN1eXp6OS9wd1d4QW8KFhy7BiLqejZrhKkuizK/Yopjz8aKThzz
            JatLdmtffqgx7BpAP42CeVXFzOjwPdeh1fx2VGtwex2sgW+5QILgxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU0VXUnBvS2wvNmV0ZTAr
            WjdsRTN1MytHZHNRYUJ2Z0Q0M1pJWmVKOUFNCnFBM0pOSmQ1Rk1qLzJ4L1dFZHAz
            ZmxERkVLMTBSekpRRWhuWm4wUHR0QVkKLS0tIEVSNlJyRG9DbXE0WkVmM3g5REpM
            N08rMFByWWdJanNIVU84M3Z4Q0l5MkUK0pn5zH9sgOAHQRDyAcFkpJ93V7cjKyTo
            4zW1ysR48SAcImFcbyQbPrxp7tJAPWDD58dKoCc2t3u42Ih+CCqh8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyAwS2pz
            MDlIVGRibW9VdmF6cUJ3UzlOSEZ6UE9CT214UGVmazIzMFk4UVYwCnFEenhpUjl2
            OVRJMWYyT2RicXZXSE4yODI1RXVhKzlDRlNnb285aU1qMkUKLS0tIC93QUF6amV2
            NWF6WDhZSVh4Mm1FTFRERStpSmtCbDU3UjkweWRjeTNBV0UKB3ncQ2pAd7fWfkJ4
            O5O0C8hakxxqckrxS9+74R/kw37YXZtars3g6A1DiIZ6a5MUTIExf0gb1xeEEG0l
            sq/PWA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTDZ1Mld1OTJrQzZ6cDc0
            TmtGNFdRUXJ1WVFHRyttVVBiQkxpV1dmMFdjCm1HZDBNWTNFQjNXMzNDam15bUVD
            SHBBd0xpcXdSdjlMY2VhaGUySlZrVlkKLS0tIFlyd29SeXhGUVcrK242cG00bGxJ
            Yng5cmNEbkpWcEZxQk1DQnVvQ1ZYdXcKI2td4SdBvBtgKT0XwuVRWzRbyOT1xdoK
            U8mO3883kCma6NWkfUrelGuyLCLCvg6dIV+UlDf5dKp+P42Vge8dTw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaE1peDRDL3gvb1JLOUda
            b3RPV0IxblRPWkc0Y3hZWmZqSUZ4TFh3ZkdvCjlnelF3d2pOaHBuSGlzWVBwbmcv
            R0czVUFORVFQakRHV1BQVVM5NEtqTWsKLS0tICtZdmZPbktpUEVEQTN2TStzZjBM
            TjcwZ0gveE5yTFo3b1k3eElqUUVRL2sK/lTThvV4umAkaTgAjiT7YFqUe29zqkTv
            D+i+0Lu05C4cUuDrdfIPASiikyTuT2RZ3uS9DN7X1Cun6J88keoi3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTXVPOGIxUG1pMTJvcjNw
            Y05seWlDOU5tUzF2TnYzQi9EV3h5N1VBMG1FClpJTjREWkQzMTlScExMWmMwMzBk
            aWxwOUh5bHdMczN2dzVjV0JMeWw2OHcKLS0tIDEvbjdWWkl4dVNXclRPNzVnYVUr
            WmJmWTg4c0JQTWRKcm9pVDBBSFJOMlEKwN8jWv7//PLHkdPPjw+Aa5Gy05+xceGw
            O6+k0E7uW7akeprUf5v6vsk9KJ6cfnjskLX9hYXoI400WM8FSsZjvg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeFM4anEvQ3FZb2dUQlFq
            TjlGMEJBRG9iVmNKZGdxaFVXYjlOc25vcmgwCkJnaXIwWHF4djZCbm9yT1A1ZXFW
            Sk45VjVaUlFLaG5Bc2lTbEdTbks2S3MKLS0tIFlOdFRUZll0UDZsbTVRVHZWdXdS
            b3JVV2trWkl6L09pSTZqRy9IMUo0b2sKlNncRVNP8+QS6rGjBkIUi2koMaWATqhk
            D3Phk3TNnOaDT7kauIk87YlZ8ISuzGublEdBbG0+2Gy4QDcTZFczDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-17T07:13:27Z"
    mac: ENC[AES256_GCM,data:mlfq0yeFaRUF16UWa7Dz5EBJgjEEKZX6gFbMgYT9s1BKlC5CC9BgYnANzZ+2lM0+QJkJ48j08R6L2RiG7sBBw8V2LuZ2/X4rv+MVyMsjUy9RnFAsCJkhpEbR9PjfiLFNbfYQ5XHvFarVsaHuLhNh2qdgBdPjbhmbDv6qCH3JXLQ=,iv:oOZNhPK/1OhY56pJWdkwf03M8J3KRNtTq8tgL70FMRc=,tag:u+Wjm5Rmta51i2d0pFcjkQ==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
