apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: immich-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:Q1/8t9Lmn3oaEyQ/cA==,iv:mvob9/TcRssOUGRpO4XfpcxkrwS0a/AjOTyoNbXojVg=,tag:kEhBDjnNsg1omrVVOrNKUA==,type:str]
          stringData:
            TYPESENSE_API_KEY: ENC[AES256_GCM,data:fuhXC0bShx68Knzz2OqTrAowJ2LC1ifivBFIwfwrFCGCx0Wy/+mMgdfKLmpMyExIVZBCipmABJAzwZW9JWscZw==,iv:T11C0zSWG1Dz0z+RTWg87RHwfSveo5gVEawenTQgh8w=,tag:ZJ7WwG9aiYhK8D0IsOcwXA==,type:str]
            DB_HOSTNAME: ENC[AES256_GCM,data:yDvEHaR6+P/xbtK4/5I=,iv:5y1Np0edzG5gF1Cwalfl6fhCRSDNS7RhEzSyBUKBmr8=,tag:cfmZUKqoEy8tI4Vl0z3wVw==,type:str]
            DB_DATABASE_NAME: ENC[AES256_GCM,data:Jl7INI8s,iv:y72dcEAWOdcfUAQrKLUuuac0Q7SmLb3GqGwH8+niTKA=,tag:hXvNeCrJuEFCLmxO3ZLTYw==,type:str]
            IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:o1+fQ0sReGnq5rRqvF7PSRVGtcf8OLOBNThpp4aQEfn/RH8=,iv:BNkxEGH8v7yPp7LbIuDq/Qbtpa6GLvb1UrcIugxdW8A=,tag:Rb7NOMNhY+YwwUwkRbVqBg==,type:str]
            DB_URL: ENC[AES256_GCM,data:DNtqT3aPi/z8g6AjWKWzZWSHsw8EXaA9V/rCoM8z9VBcIOUZRFAMz5vCsxkuqLy1/jrHj5JfFEq1pXfdgZ+2lEaE,iv:namQWjsPwVk/FESst04oV4QHXFNaChq1NtGcKPtXs1Y=,tag:J2/aCCB9ZbhfXbkDf2Okmw==,type:str]
            REDIS_HOSTNAME: ENC[AES256_GCM,data:tMN4FQdk,iv:qfotxc5v4W+PycSY7kT99kalW1H7rEGNu8EIygaqyaM=,tag:FzheLnbtV/LQl0ko+HGmtQ==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0T3h3UlpBMi9nNlZ6U0Vw
            NG5qL0JUOUEwWTlVTHhIUWgvaUtNdDF4ZjFnCjFuMCsrd3gvM0M3SkdYQzQ0NFIw
            T1RhNmRLQXcvUG5xekppVDRTQTJ2bncKLS0tIGtSWDZFMkN2U0lmMXJLcDFoU2VW
            dDhpT01KdWtWbHcydE5lVU9IUjNkTkEK1ZxuRP6n4s4hTLil1NCL+sp2Wsvurnwv
            usoZdLk7I91XiOHd0IJpPdKl/+Nu/rVgnErGdLvq6N8OhsDWt2QqnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdDJCUjhLV29QaFFtT1RI
            Nm4vZkNTTUVWSm0rbFhrSHRBWXhuZEN6ZjJVCjJzR1JRM2dOZ0FVWHNib1N1OHhB
            UUpqdzhWUU9oTUpwNm1KSTY0K1R3SDgKLS0tIEt4ZUdLZGdPL2owdEFWbWw3Tkxv
            MDNPTEU1TGY4ZDNqVnN3OXZJUk5OR00K0ztHKp3V6+BIsO+chYlXmrE1oGdkWKgo
            ziJOQgl/fI+ToRbFuYdU1QXJtgrs6+4hNkPaxXs8Gk1mXDYM76ZQWg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZHV0QkhxVFpwY2NIOWhG
            eXBhM0wzOC8xQTVHV1pVVXMvTUxRVURtcFd3CkpvOGordFdPbzVnVThXclA0ckJO
            RUM4cGNJL1ZUSiszNUhxMHhudFE0aDAKLS0tIGpCa0xtbnlydVNYY01JL3pPbFdY
            YzlmTDNaVVpXL3JacS9RS3phcFBiZm8KNJgB+Q3icQ3oJ5vAX989mOfR1ztznjEl
            gUGoTi/Dm8Z5QyLWfFfMGoCcI9RPSUEI+LakM3Y6y5RT0vwQMqXy/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaXJmUTduc2k0MHl1eWFC
            QnlvVWJpRTBvK1hYQkRRbHFpQll5cmJtZFZzCjJXbEYyTlhyc3VDVlZSdERxMEd1
            eHk0a0NsZmI1dXdrTVBtcDJjWStZNk0KLS0tIDQrOWR5eGtZRm1HWWdKTzRCS0pH
            NW92UlU5eDNlejYrMFNWdWFYSjU5dHMKobRyp8oHK1HzusmlcmRRH6Pi42hSKzSA
            B2kEoHMy86/4wVI5bQPIWoFiw42ySuNTH9EXSqQOM1w4ChbHh1rtHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQY05EMFhNS2VBcHJEeEZk
            bWJidkkyNS96ZGRENnF5c1N3NWl5eHhSa0ZVCnZ5SlUyZ3VIeVBlOUpIbVI0Ui9w
            YXRoS2IrdHFBNGFlbUwwV3Uya2lOWFkKLS0tIEVHd0RHMDdFNVFNN1RZNEpFazly
            ZHlvdDFGWDJBOCswdVZtL3c0alVoN2sKlxYvtZctbXc0J4TNbSOMt2aCawTpSqaL
            0tRKLEYoVnEtvI9PXTRzkrI/8H6JUqNiqjUrohZj2iqtL4MQJmkEIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBGMWV0
            MldiSk9aRHdkSHI0MFJRS1pOb2oweWZkTlJkTG9iOHduMFRpazNjCnl4bTBCL0tp
            Q3FSSElaMlRzWHd6UndWMGF4TlBzbW5RSnFZV1p4TkJra2sKLS0tIGgwMkRKVmpx
            eDllV0pteWlzUUVOQTFCREhLc0h1U2JWQi8rZWxQYy8rdTAK/zWvBfNXrDJe81Uw
            Zra2yJnq2Ls5fb/66afoKjixWJ9URUk2JXGcYCewyUesuJroCeyvNughEvVHoyo2
            gydtlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZEsxVDJyZlM3Nm9lNnFx
            Y3VDdXFyWTdFTFJrL3lvcGJBc3J4OUYyeDBNClZRNTh1NXo2bERETmZWcUlpdHZx
            V0FVT3QrZy84OFZBUmJCWmt5UFpnYUEKLS0tIFF4VkYwWFgyQjI5WUtnUnAzWnox
            OFRmY1RGOHRVWWc5QUFvZEZnaHZsbEkKvvgajFlwSs1sukVMadWRg6pwTfp6rYwf
            lMMRSuvXSIuTOn1hlEE7sgGNcoJXWaads5pMIZ36CZl734avi6+XXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyV1VKOXVLRHpndlNGN3pa
            VWVzNkJDT0JtdjVmbTVYeXZWMEFmcnVid1hVClZBM0FZcFoweVU5Y3locVpxQ3kr
            NDVrRVZkd3paZ29CNElEVklPS0FjN2sKLS0tIGtDWlpGWW1waW5Gb1dDMGRJNlRq
            SHVIY2FZVEZ6c0p2S0FCbUsxbGRoVTgK8Xaixx75fxo4T5LKQDor6BX+uHK0XqCg
            yUlTTscqM0iUPmc7RfbC6LErQktIrH6X4FavB/Li6vj49/jIGfQbUA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQWpjc0ZmaWpyRHZBK3dI
            b0RsSklOaytobFpKU2Y0R2VpdlNNY1FYN2lnCkZ5clhERnRhak5pK1BzelNTd09U
            SHNSVzRLSW0yZzhJcmVwWUg4K1BuWU0KLS0tIDg4S2Y5T3BoQU12aEV4M0ViM2hD
            QjlEdUpOVU5mOTJ1QzVRYmg5dUNYQTgKJH2NdEH+llyRggUI+JGx326bg34GAvSj
            fCz986+n+FOQrkDuXhSek7/CfYeVwBHlZRjSdbGO2uOs0oXttT5mAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCanNXcmtaTjJEZVZabTZq
            RStUVHduSUN1YTdlS25nZVJxYUdRNTRjMHlZCllQZFlxenlMMzQ5KzNBaGE5aVZP
            VGxCWHJrMHVRZzllL1lSc0JSSDJ0amMKLS0tIGl4MkVLd3NuOWx1aWlmazhKWjJh
            MHZFZ2VWbXRKMjVhMklXTTNwM1N3V2sK2FaGZ59P4mW7Y42YBMaIhtKbFwYHK8gh
            1OGk45LcQCHh97UyXt7C0IWGHWaisSOlmGb1OFOhGBHzJRD6zEvEcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T02:37:31Z"
    mac: ENC[AES256_GCM,data:8QI/Qa0MxR+ENDcn+Iww6KbeDGchOJTACj3/qFDYaIRGQ+5Y29vrCP6AX5Il+abWEatv61SHzFyXRT1t542bzzVT0yQU0m0T86pU6zF2NBwcJgRZf/ATwCuSO4Rc/rQ0kFqz95yfX/tJxg++IqSe8GgbxNPBI2MXAkPpt9Jc6Bo=,iv:yoN12o/mOL0wwDlhmySHhymgYj0AJYqoWfD6Hp4kDv8=,tag:5HZPooaQToCS6a7t3rCc6g==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
