apiVersion: v2
name: csi-driver-nfs
version: 0.0.0
dependencies:
  - name: csi-driver-nfs
    version: 4.13.0
    repository: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
maintainers:
  - name: halkeye
    url: https://www.gavinmogan.com
    email: helm@gavinmogan.com
