---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

helmCharts:
  - name: headlamp
    version: 0.40.0
    repo: https://kubernetes-sigs.github.io/headlamp/
    valuesFile: values.yaml
    releaseName: headlamp

resources:
  - ./secret.enc.yaml
  - ./securitypolicy.yaml
