app-template:
    service:
        main:
            loadBalancerIP: ENC[AES256_GCM,data:1joHbSNSc3sE5Y8xAEE=,iv:WpXGCPJJEAACvExhm+wA0np+fX1paib1fFq/pvyXR38=,tag:aNYsy5L33m8hN+D0jz5Cvg==,type:str]
    secrets:
        secret:
            suffix: ENC[AES256_GCM,data:YeYRvHnG,iv:rsR46xG0ygMV3MKn1atvM+KVQ+n/Hvzn3H7Jo4mytS4=,tag:uBgpjQ7+Oe2Cjoi3ij0S0w==,type:str]
            enabled: ENC[AES256_GCM,data:iXgAeg==,iv:rixbIzcxbfKvlGcijEtEdZY/lWdDRXuT5TZ4ePyb5lU=,tag:r1wD1CcR/CQjNLjdijbEZw==,type:bool]
            stringData:
                rclone.conf: ENC[AES256_GCM,data:8KB+0OfKPasSw6yyJAXbp3y8PoL7BIeuRIEiXJ7C43G/+hkWULKqqftTyaZXhfPiE/8T6pMkM0ZGNkxBUF1jx0wWIpVCKivqO82k5FKzCXh4EFZaRQCXSb5XE5X27X9+MDxGmQWqLVMLmjXlVGl2A91D1NprPMJuqeyMGh7SaOC9VSt4zjVR/GeGipGnVOwHFZFtkXhd1rnj/B835oIRfV0wwdjuWnflaEHhzSRhhp9jjcx6t1bWPCd/QAX6TkGFyMZJ1+vqkEdvx34CbbcBJZnNllWMMkJDxhRSrhdwGsGKCXM+ngYHMx4C3eKP+IKRgcoQWyh3Mxv14yQ2AoSYOZ5Dc+Yc,iv:pEKmZ1p0PYGY41Fk0co2gq7MVPQ3RqrYBMQdTh0L78E=,tag:DxZa2qs/xziO/atG0kliUQ==,type:str]
                1xtf5px1.config.gateway.json: ENC[AES256_GCM,data:2hoLkoR+QUw+hzwT9vHq8pwDyzysXi/UIg1VzZSeoHfLt5HI+eWddo0jac/2iGsl9pg9+e62QJhhBoqv/L2MbKy9peoYCdPpebJrD+3srfy6Pm9aj80D18uZm5VmwHnIOPqa9cSCEiRz7iCkCW7LYHzfwIyW/87cptTmzNjkuJddh8Z8wILl5ZKBP4JlqivelatrzuGp+jr7sbJc1rYTzDvgr1rHFEKIhbj9oDXhZN5GctpyAWTYZbCJe5q4vzWXRUbtFVAaeJip9wmbm7cHrvd0RXlVyJb0412lhAJjTj7/CAGeLDFzjm3PQXJAOeLm05ysIAzOLuW4HPkcGp3G9aoQllyP8jttge2G01J++UJviI2jAy2jgrgP0WfHWN5wd2KMAjmzrZRePH9yykbG05FjQaK4HIFPDwpeFlsOWQmH2aK/Unk4ugyKyedxSBgX/lrqgQgflYCgAo2NZgpvkAFIQg7Eq1ZBD3v/1jRmwKW2wZNgNZUMsLhw2s879GwaB+qECx+XZKmJNuE2YSbS8gmHP6HvQxOzuOEthiNpPYg5sZdQWVis7vC/X4efbkWSg5BoAVTE+rfNFd9CkT4EIL/fNFPmwLYp4mTe4KoX/iL1Q9n9rDwsfOzk/kqnBXyIPHVuLU6wrinLIUlBLgnzTT8uaXyewXi+YpieygTkz15Uk0VICthbr3XivA==,iv:r9T5vs4TV1bTQAdaxorRUVdGhoJFcU9SI932UDPAPL0=,tag:o4QUtoMmC79wJpaLa/7N1g==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV3E3SzNhNDFLM2xNNVJu
            UXJsYWtKbWFGcCtSdWRVSVlHeHFMRTBmVEdjCkx0TFBMS0FQTUFRdWpwcFk2R1RB
            TXQwUXNQM1BKeVdKcXdYSjFBQjY5c28KLS0tIFdZSStQRy84alNMZDF3REcyOFJu
            UUNpN25EYVQyRDV4RDhmMWdBcXFpNncKNQqqzJXgpugvQVUlxrsptks87Z3XKTcn
            M8Y5XvljOjCbVzELYV9RbMRy+KVJrUN6kDkBPlJJ0QXG32/pO/5EZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbFRQcWJiWVpVNG5VaHFQ
            LzM3Vmlyck1FYmhpTGo2SGNFSnJpZjJvUTAwCmpnZ1A2UEp4cHQwcFNneXBzdHBh
            MWczallHa3ZLWkRuUzMwRGdsSHJPbUkKLS0tIG1CMmlBVTAvbFhsamY2NU4vM2xk
            UkM5akNQTlBCbUd1RDkvRUVMeEs0U28K/Sjep6JqvkjCR99NSg6QZAHeYu3VaXL8
            6GtbKiSorF5untJJM35hlPkb0YpRswlWY3/OGyIoN8I4lZdR+07IDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzb0plRi9xNjY1MlBtUWJj
            YW5Fa3UxTE1Ba0t0OGw5SktSais5ZlBNOTBvCkJhdlcvNERNd2JMRmxDRUV5WjdS
            T3RsY0NxRDV6TEU5Q09NY29XTEcyRHcKLS0tIC9RRkgxVWFQWkdDVGhxM0pZTFBl
            Z0VVWGR1bnBRYUVxTTU3TUljUUxRWUUK4ug3z6NY7h/KIhfu6e0ZE7rndo8d6iY6
            a1cji6JdAXQl345MyvbePfR4Fd8cVp85kZ2bsVS6usQxPF09W4M5CA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Z2paNEI2ZWcvdSt3UEdy
            bDhvVDlnQUd6LzJnUFpuRUtROGg4UzdKRFQ0CnphQXhEUVIwWGhkOU9wZTFobkdm
            NEhGQXAwYjVQZUxZcjdjbE9FbGpiZEEKLS0tIEY5NmJpbWZWOCtpNnRjU0RTaUE0
            K3hGMFRzVlVoM3Zid0ZqKzlCWFpablUKA43Fom95UWz/j0DIRr4UpF0X3qDHvb/J
            ikZR8s7lDzXcxBXZ7SgYsoVdvexcAHBf/uV/dEkTwGYyMEDExO/aHQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0bXlaMVdDcmpDajZ1MWRR
            VVFHZm5ndHRtVXI1MHhxSFlWaUZ4RUl1MkNFCk96eFJKNHUxVmZsakFGdU8xR2Vs
            UkNJYUtDcDcwMTZiTVlKUDZNeG9GYXMKLS0tIFd5T0tZUVg5cWdpNnhVQlQxdFBo
            cjErSnFJWjB0V3FZUkZIWWZYWldicGMK00hGqzP63Nhi9Ea+6uP89I6NCYDHJAkz
            Tk+/Ah36P60Mf5EnquzFlBeWbDQIqXcSe++b7P32wDT5gwS/B+xnVQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyA2cUFU
            TUJuSktwWXpHeVJoRWJQYnFRQnBaSkFCbFVRV2F6dDk1MmY5Y0Q0CmczYVN2bkxH
            K3JuZFBFNzY5cGpSYURVakJvUUxRT0dSMGlUd2VFQ3NzQ28KLS0tIGZhSkFYZEUx
            bVEzVHRBVXlJRFhFcTlNL1BGSzZNVzl2VDB5eEtMekRHTDgKfJq4X8ezx1lW5/UZ
            QYzYBDjlwhJhI3VImcEm6HtXiH8Y/G7UO/H1FcRY4YcBqtyZMlfGrRHayM6I/4l1
            gZy67g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGc2pmZS9wRGJYaC9SNHNu
            ZFNzVXdNU3p3cUk0enNoSzlPRThtZ3ppdEVNCnBrNXM4NmNJdlNya2sxQkNKUVBh
            V0FKU1p4VTR4ZkdZb283Sk9HeEVEaUEKLS0tIGhBTVVjTHIzWHEyQlhWSm9VNWtS
            VWZjZEtqWkVreUNIdUxhUCtFenFBVFEK4WJ8DJRGOEtJyRKjmE0yVSqsc4w+ZqCG
            xKl4HsBmKYRskx3n81Db/uilOMz0wSdmHtxEKTs92mL6e4se4RMzoQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPT0p1d0tUdHZYQnR2MlM3
            Uk1lekx4QzZvOW9lTXJBMGJOMDV5NmpUWVZjCk15N2tBVmFqY3BlNjd1WmZvQXM4
            SSs3ck9RZ2VmZHdvTmRDQ0ZPd2g5TGsKLS0tIE9HY2F2NXl5UUMwdzhYUUJnazRX
            M3FIVVJmU2pqMHVQZ3lZOHVTY3p5Y0UKG33DqyW33KSLZZZr0wDEgOu1/IZtlgjK
            AogPnCWXOO3NTITRf7/9hiIAPsyI3HH6gY1v+j98a5ReAkYO7dx46A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBncGU4cmJqYWJSaEhtbVR5
            SlZQeEk3ZE9RNW85MFQvbUhaem9LQUpIVEZJCnFkZ1FSb2J2cVVGb2g5Y2xtdGhh
            aUpsQXFmSHlBS05PM3FlNk9CNzB1MTQKLS0tIDBRdXVzM0kxc0c4SUYvbVJ2UFVP
            OVNMRnl5YXZnS3oyNXZuWk9UTE1DR2sKbaBtrMuBG5Pp8W0lQAO9oJQCKb1f7mS9
            A+A/lqSjOrLFeiQ3S/v8SdxW8nZliaER5UqlHZIFyHS3zbYT9iT8qA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTd0ZqblNUbEYxR2h1ZGtU
            T0o0cWFpOUF2citCRXl4NGVJOVdIcm4zVFJnCmk4SXZBWkx0Y0VoQnd0dFY1QXJv
            Um5SandNUldHSURGZmxuL2RJRjd2aWMKLS0tIHpFNUdUalBxV0pBa3d6NTZ6TTZv
            NnYrdEEvaFRhWHZadHM2MWVITENTRGMKQt/zQ1Viifa0RvieTbnkGsZYRWHCH8at
            ASx3jGnpdutGuHo5M/+T56SsM6unTSRBs5cSRCBhf+iDqmwiJY5Q+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T03:38:07Z"
    mac: ENC[AES256_GCM,data:7xfYgYENcVIw6iyfGUH3WzFr0iVVbIQYSqdwnwuLSh78SGUOm+GJ1UAZl6MITRYrALapW9LcvWnqI6cE3PWcVeWt3zdLb4Yuh4+QPkbQOZI70S/W0ek4s1OzYQLv4TIORXUEe0M6kzLb00K8VC4h3tCqLTAd4gbNFYPU5lelwJs=,iv:8NEGyk4dwkHQ5RG8GGyVjwkDWK/bCEhTHZhz6zrvW64=,tag:0yt9UN/dVb/SnGNhs1rTdQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
