apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: bandcampsync-sopssecret
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:kY10f/5NmnOSP91lU8fAGGUtig==,iv:uI/0MJ/8QTr6CjvRy5KcHc3Z12uPD21NV2WNvF+FqwM=,tag:f2rNwgnDuL5pKbPLIX4olw==,type:str]
          stringData:
            cookies.txt: ENC[AES256_GCM,data:GsqD2cwk7wtT5ajtox76DxZ5DzVAvIMPjlx6RJU5KXwoIg3Uw6oiV8kzWurzpBWdhprKSAZWNiBiSPI1ixgRw88N5gOEqFfqcNW6F05zPElk66DB2Z8OS+B5sDFSU2rEaqTSlOj93ShQfmUbDz7OxM47h9MFO7jdCZVwQUFc0k0tQmN71+99JdLMrbTSlaMTDRL9qSsiHwu7mwfeclYN34VvRTuGzw70s4mE5vHvYMOl2mY6qjijAT2Zh1cfjYJO+X3mrlQ/CwTr36BY5ZGDhrJm88UWeniBWitAI1yLQCHwkxQNU3I6wfQRDKUJJak04uF36NlQfkyryHy+mm9U56ScEDZZeUVtJ9cSlBKzpTWRM9Xa7y8VJlXZoeQq9vYref/PFHeYGuFrsSZOQEcg1aEtYBAD0AFcPfOh/MCty1o8E+7FdLWBGNr1MFFgsARRGdN2+wXGrMMkkT/dSMnmLuPKGL2m8dWYRv6CPES8Ce66TcsYbteX2/DlPcbBXurU7uaMtsk7t1EpT2T2AB4lwj8zHOK27bAcAhPD6MwMVYYArrmMFEnc068nabTNsbTd0u5iMPn4qLewlfCRsV7ZHiZiV2lAJK0TOm3rpLDtBHuUu5s7D1lpdijk2UkkP9+BhLfnXeBiO45nQIOzRdmUwtOin1mRNAfPc05u8uAxBWGp5rzod6SPd1BXcw9X3wxmkJedCiPUpEQQRnDFJ1Y79fEtH/c=,iv:UNWAEL9NiZRJHQ3Dsh4j+WRRxdyKSX8W7ckzOHCK1ag=,tag:dmrFOrB+zNhPoe9avPH5XQ==,type:str]
            ignores.txt: ENC[AES256_GCM,data:ltytHTIsYRUOLxtBz0Xjv5NL3e6G7QO8LEnOJfMnPVQH9VPPUGFNREtfntMqaWraYQ4Kwu5Z2nF8oFGpsGnH9QD28bbGYIBkNo6GX9BdMuUbUkRjG1sKO1mkDq2TdVPpVFYJeLqv1OMThrW1xfEq57Dg/Gm9uhyosRdym/5r+QOYYvCZ1XNcPcPXEsWOcyFVSyT5z7/n9xCZ3ZVPKw9XsM/4FocNevgz4/92qLR7j9WlD8ZeVIgiMVOr3ms6dnip6YEKtC1bR4RkVOwnKK6QvFVsUQMb9xTaMrYVDcLGa+5pfXCvy9V0OhgIU+YwDLVeMS6Beso+6wfnggqCPP1mgb1HQ8qFD9+zt3MLFiYn53Wuv8BG7kgNyw5eXLC9CQam+8RA2joZIH4o138uW/pCXJtYOcqlc0nXeYEY2kLWnHq2pD8WmDFoL+SJP1x4DN9zz7MDd+bSzaQfOm7YqL5HrIf7v5nK7vYrwMS+jhdbP235I/ooDvwe2OL6VuW3AozWjnXa2KyRl1+eaTgS1mSaEVVQiIv+HLYp7F1EOqJt0l0dO3GqqK4FCMW1CMfcPw==,iv:XrIXLm3zsemko76roCRFp2TbKwruCl7KZTnH4lW5X/Y=,tag:WDQ00tCsYrJO1sJlpofwjw==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeWExNExrc1gyNytpT21F
            WDAxbTdmUHkyVG42eVJmOFlBSUpOSmhwWUJVCmoxcGZpMVhwWmowbnJKVEc1b2tm
            RzhUZ005bUZQbVltTGQ4bnVlOVJiWUUKLS0tIEpoZ3cxeVY0bnFhYjh6aUJrSER3
            eTlQbmN6ZGdqTWdjcVEybloxOHZzeE0K436FxGZeL4iDXdG1g9ORG7/zk9O+Gi6O
            g/olx6rt69ulD3u4wQMijIHThMZrZLcI9TbWivds3lIxWDfjwBxIuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WHNlNnExTEhjNnpjWFA0
            b0w4ZTJNSExKSTI5Q2FCYzlOeFN4TEk1T0dvCjh6WEdmbWFjWTlkM3ZmV1Z5bGt3
            eWljZTY2ZDRZaGhHUE53c0g5WGorenMKLS0tICtOYmpNdWY1YUpsVjFLVHZPZnIw
            cmhTeWFucFVWbFIwM2RrNlBBKytoY00KVV/HKOcKwW4EZjxC/1fnIORoBbCmuRod
            2CbuaFFFwoUQy2t4Tk8N3Xcr52QmevCd4jtRzr+2hJ/wIlyofWw6UA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NEJTdGZ4OGp3Q0d6QnFn
            Njhxb2MyR010bXV1cGFHaklwUmFNVUdIWFNzClBpV0hXdWxFRnhQUjhYM2QzMDk3
            Yk9PamRRazNqOEFmQUZHRnpsWEtEV1UKLS0tIENrMS9SYjBEaDBQcTVFalhHU3F5
            Rndpc2ZsNVI0ZFZPbU8rZnp2eThCQ1kKQbA1v/swscWP8HSDlCLYF/DiZau7DhIj
            yb+jqIT05k+E2z0QOpT1p1zSeXuCLFCkkNF/n+5VyWOk6fi2hNYKhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2YTY1VktMMjEwdHo0UEV4
            ZU0zTXMzeXMwY3c1V0JKQWZFUXlXaDNLSld3CmR6RkVsampqc2F3bEVBZ3I5ZHA4
            Y09SZU1SRGR4WmVZbmhMb2R1emhxcHcKLS0tIElvSzY3bktSRkg1WVVhTUIrMG5K
            aGlIUXNqTTF3UWtueDY5aGtnM2xDUk0KNx+ygHO02afiNM+zDIn26oSOiCxvJ88m
            Gj9A+CsB3wJpXSeVXv0R81hpOVxWSZcihQIVl7DUcZJpez8NNAbtCg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMzRaTlQzaDZDKzk2QUNO
            V3AwZVRxNTVsUTFCc2hxSXNuWHo3MjRUNVZZCk1RRXNwZnA2Y040ekVVdGY5Kzhl
            aTNLR0xhN1FseWhHclNvT0xHTjNWREUKLS0tIHFxZm54NWNWbDdiSjQ2YVB6NDk5
            dVA0cVJIeGlOTis1K1hqZDFOc29ON2sKzpSkadiB1M1ID+CTEbpioHy0XDlRE8/l
            KRpWss7RUOyGcsUUnK7VWapMmNxSEcRrqeXx7zAMfnWgzqwaqPCtZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyA1VG9u
            d1QrNHoyZisza2dsSUxKS0tqM1VyRDUrM21ySnN0cFRDcktmOEVvCmJzeHhVcVNo
            Ui9EMVdwS3pyMjRETDdoZEFMMU1yMEhxbkVDOFNrdVpvOGcKLS0tIE5SeUYrYnJ5
            eEp5RHVSbEExQkpLYlZqRFBoSnQ4bFdtd0NaVmI1S2VpbEUKAY9v0nVGs2bZjwMM
            YOeEoFtQV6G4s/BtwaSAZfKo3zXJqlhnyQi7fXYL82Ln75qrAJUTucw5EYoM2J0d
            p2+mkw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbmFMelpDQ2ViTWFWekZY
            RzNZanU4cE1vTmlLcWFoMmpQblU0L01qdWpFCkhoWlFTRXRpYU55WVB4bFpxcDRw
            TDVSbzREU0tvc1NCMDc2Tm1JRzY0VW8KLS0tIGFZd2NCN1V1c3dMVDA3MkRxdW5z
            VlFOMERWdlpBOTZxSjFFcmJWNmFnYlEKmcGJ0tUOSDrG+yRYam53aPku3KzLZ6Cf
            xWoXMiis4BE16YCWUsFK40PN2zNzWbfqS6dxg4mpdprA36W3QC/pSA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUc1A5eExPbHFCcnAyelJT
            aEVleXNjNUlPa3RVV2hsSkwvaTVFaWtqWnp3CmFOMStERUZjL09Xb1lGWWhTM3Y2
            SldmblhDSlVwNjg4NTNKSGhBUEJvMXcKLS0tIHBLdmlNZ0pUWnl6cGR4MFYyc0RU
            L1J2Ym94c1MyT1NhR081N25ubUlhM28KTc7yogkl1AyEDlTlgQKGqCsvw3VJvPGY
            J8zbxSMht+1F2dBVbYmT2CyGQCbkjzfPKuHhHeRYeTEnqC8oiLl8Tw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRUxtT2E0REcrU2svTzlK
            ZDZvMU1jenVrRlRvTkNuVzhWY25lMWFBSXpZClpOVGkyTkZlOURob0M4YWRwNUYr
            bWd1cm4zaWxyWmdyQ0UzK1RacjBJUjQKLS0tIEduRXpOVGpEaFNvdGpNdVZqTnNJ
            dW9YdTE4RUFpVW1ONWRReDVGMkhTU3MKO0Tk4PTLXJqlQcZ8AUdNG02OhQMVqQXr
            pK8mmmeWLIGVkewgD82NurQ9+EU1Kcf6Mxw8xEYdrG5K6Aw3zpgDMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZmRPdDdxOURnanlMVU13
            SnF0SmZDcnByOGFyT29MVkYwOXlXOEYxTzF3CmdmL0YwQXlCUE4wa0VYRHAxK2RZ
            cnhKRXJJWk5tVHJjWWFSZ3RINUJsVmcKLS0tIEpQaDRYSjJGcWljbW85UWNMQzF6
            Q0ZZR0ZlZjk0K3Z3WVFJZzdxKy9mVW8K7dkWuSAkHYEjqll+X4yruwAGPJWCBcWi
            GK/88rhZV0LQK05D2m+qvXZqmKmT+IhJFMOH1ZXSOkH0UbAJ1cqrDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T02:02:01Z"
    mac: ENC[AES256_GCM,data:+/r4APa88eFD02hW1AUjCEg423mVTMmR9SabGjF211zS8TtKPCV9QgETI+z0ELU2f9FjOACOTDvzf8tzFGGSffYEWmuY9jfS+/pfq4Nb3FZU2D4IY5yBwFo9gv1wILJxF75YL04oG0PkI9eiRewlXRQyqWApWf/1+CRU6DFkDe0=,iv:hFnOg3+mYaJ8y8TsA9OnSS5HrZmiLMNqISbGSPKlCsc=,tag:gTUppx7hgyrr+kT/vOmQ8A==,type:str]
    encrypted_suffix: Templates
    version: 3.10.2
