apiVersion: v2
name: cert-manager
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: cert-manager
  version: v1.19.2
  repository: https://charts.jetstack.io
maintainers:
  - name: halkeye
    url: https://www.gavinmogan.com
    email: helm@gavinmogan.com
