---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
  - name: cert-manager
    version: v1.19.4
    repo: https://charts.jetstack.io
    valuesFile: values.yaml
    releaseName: cert-manager

resources:
  - ./secret.enc.yaml
  - ./clusterissuer.yaml
