apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cert-manager
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:jQXEkky4TgBryQqKiJecFQuP4NpTjCdyRlzqOhXpHMhv1KOgsdEf+3eBXCj9+FE=,iv:GjW41QtxHTUOSsDYV2MXbomDEkqPd8iAmQ6+vlxRpnk=,tag:r0yGGDBmRS1Hq5bF4Q2rLA==,type:str]
          stringData:
            api-token: ENC[AES256_GCM,data:XaGcM67x5GzvK8XqE5H8hqGML3LAojQyBLVMzvMl44oRvqC+HeNFYg==,iv:WgkvV0Yjo6uIjaJ7JLhEq3dmB6jVigT5ccqvSFxHiIY=,tag:CiFJdpzIfuSGkdzeyQMCoQ==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYWlzeXdnZXlWQ3oxM3d4
            OStBMnRPdUxOM3BWdXVOeHlKdlUwc3BrZ2dnCm56N0dSWHJCcnRtUnhmZE5FenQ1
            QVVQeXRQcHc5Y2g1ZGRFKzhncTdmREEKLS0tIE9yK2dIaXRGYW1lN29oVEJVS3lN
            b0s2WEdNdTZ6MkZiYno3RHBWUTUvdmMK2py1WycJcjKKWsXL3kWxa1GuGPkAKxzP
            zY5ICjl/ipp07dlFGpPeGxgYQC+VUzOob69tHGjr9aYn2SyFRZbPhA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RE1rSmpZd1ZVak5Oa0pa
            a2hrd2o4OUVQa2VHazFNTUM4cmdtSnk4cld3CnliZUgrNXZGNFFWcG90QlEraG5u
            dmtoQXBJTUFjWVFBMytITDByZUZCOEUKLS0tIFhMMkI0TW5FQUJjbVhvNlBQVjRq
            eGI3L1ZNTEw3SURYRGV4N1BkL3hUMkkKqkjQMUett7r2C4Nk1gOgUHWT1zQGjtO3
            Y5d5TvkEDcXkB6Al3dzkT5iVtGu9Lrp4RE8hj7czGPCZq1ma+5AXQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd2NOenQ3bVU1WVE1U2xq
            bVBSelpHLzIxQmY0WDRScnYrcVNoczFCL2s0Ci9TWmFzRm9iNUVybHQzOEcyTUNw
            OS82MTUydlI5QXFzSmNSTmF1ZW0rSjAKLS0tIFpZQUorYVovbEw3YXI1aHRkN25j
            M3pBempHcnBiUHNIZUFMZ0JPWUFoMjQKN4/SMZ5Df9a0LlcfzGzCCw9ycrDDv7at
            VPJX7SRIzcjmcBk1SjQhkbtOBnNQ0jxbq3m/H8s1MVGKngINiBcV8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRFJaWnRGNUdaUXJkdGFr
            a3lTZUZRVlhUUm1jdkZKLzBpOXlHNzY3Nm5ZCmpJUjl1aFZsdTVrRzAxQWZpY0JN
            OW1Mc3FhWTlOK3lRR3loN1VrenNjdk0KLS0tIDRES0VOejY0VStTQldFRmN4NkR6
            eE1iQklRbDZjWUhZM2w4cXk3WXNDbmcKWIEbePafgDHE6fR7Tng6Eao0gWYL9w5z
            RXcVRdv7WM2NNXrOYIRJsdZGCq6wok86KHoPuA1BcA/70iPg2mM0Pw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3clBlU21jZHJ3L1V6QWxH
            UDd2SWtUY2M5MGRrVkNyM3QxcDQwV3drMHlNCmRsNlRDUzB3YWhUSU1vWnF5a0Ns
            Rzg3TGdyaVFRRVFrRkRQMlBVOEZ0dWMKLS0tIFhEb24yeU5SM1hJOXhPelgrTTdm
            N2RVZG1zSzlBZGl1MEdJUkVpOGo4cnMKtjttGP0dwPPTTzPeRJTlq2GoKE6q/HNd
            K1lxIRcwkTlcQyAwiA7IgRrS4l1salv53r8MkJtaiX4NCXNOYzQnBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyBkWFFa
            Uy9EOWk0cXFIWVJuczU3bHA4a0gwZjNhMUNadXcyUzBMNjBiS2cwCmNTaFQySEFa
            YzNydWZKZyt5OWNmVVFpTGdCOTRhOGYwZU1DaksyT0E0bmcKLS0tIDI0WE1tZHli
            MktIUGszZ3JsUk5oYUo2aDRGRlU1Mmh1SnNZY0VVSXJFdE0KQXF4VXy3pNRArZop
            yQwiPiDdO5EgYdney32Ew28vH4Su5ZbuczJcgiSu2SIfaTEOY74uHuS4V9xbzddu
            YZm85g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYjVjay85dk1SUWNka2ht
            M3VNS2NjeCtZT1J4cXJEYUtQSm5TTXZqVjE4ClhiSWNXOEplRFlJMjhkaFVmdjVt
            dGJoNW05bDBCOVZPV0taVUtDNEZNODQKLS0tIDNxMkJDcDZZNldRYnRHM1pVMnEx
            SHV2VmNLRzdHRG1oclJJMVRIek1YcU0K6/KV3tbHvNgiGNZjQUdePKdyu1HGvPQS
            o7NvyfCWw7ADXFiVHNvaqlcPE3qVYF9YkxMpfGq1/ULMXIXap5UW2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1b1JQb3JpODNLamlTb2s0
            d0E4Z0kxV3VGL1QwdEdmU08yZkNzS0l3S0hzCnB5Qkx0bGx1UmhqUG5jTzdIN1Ay
            Z0QvbVNpNlcxYU5XKzludmVadCs2RkEKLS0tIHJ2WnljY0lvRmU2cmNneUhzejk5
            VGN2Yzl6RkFPUTNmRzNzNHFoNllhWXcKusSkE9o0GsoAwFfnUafBh685M5NZGmOV
            HhFBT7/8OU9/OU8hoQtGpdqDL3/v+RHzpWmJhewHQcEk81SuASW3Rg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WFRGQWQvVWFhMC9xbnhR
            OTdoL3J6Z2hwRmk2WHZxU2FMMEVjcmhCeWtRCm5BeTBXRnBOS1UrS2xNOE9NZHEv
            K25INCttTTRyOVpWcGhwQWlvZ09Mc1kKLS0tIEEzY0JHWHY3Vm0vbU85SDg5bXg5
            dVgwYVlzbjhjRnBLTllHM3hwQWtCSW8KnAOQrzWD4Te6h6FuPugwg/nDXrwK6IC4
            /zwWdmRMmGRFAA51UHPksnTWpkotoeIw+4XQrFT7XsXWv8y1wAAZLw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbWc0eWhZdkcyRzI5RkdO
            WjNjeUlpbWpJcXZJN0FTcTBHK0wzUVkvbmwwCkhCZEs4RFZVOEluaHk4azdpVEJ0
            azBseUU1ZWhpVHB0aW9xMjJ0aXBsczgKLS0tIGN0QTdmMEdtWWw1OVFCcGtldGov
            ME5ZOE8zWHB4dEVicTdmZkx0cUNHSkEKWm0cb1nqy2MJlXvJFgE07Y3HI+NW7zyY
            dXtf9cagi7DWWl5HyVs7mLyzHmj1GkyDOYkA8QtrO59YmLD9B3hFMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T04:13:45Z"
    mac: ENC[AES256_GCM,data:l7Gbhjk9DirMivhNKqIYhgB994X7sVZGmrr6D6vUbw4/U4lwzpasCjl3VcVeTi1gBhmElVPdyYs6BD9EqmzVopgD0peAKhzjXfV4nf1miff6KpMzn50pxG3mBSByIB/tnSGUdO5ErrZU4kAeMoffI8ITtUGvRmI0/Qs4ynoK4yM=,iv:e6imif/D0jX0swmA8wCCKQIkvskJjiu+jXXGdGpvPks=,tag:/YYoRoNr5VOzuYqo0GYvow==,type:str]
    encrypted_suffix: Templates
    version: 3.11.0
