apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana-operator

resources:
- ../../../charts/grafana-operator/
- dashboards-3dprinter.yaml
- dashboards-data.yaml
- dashboards-dotdc.yaml
- dashboards-ingress.yaml
- dashboards-mediafetchers.yaml
- dashboards-network.yaml
- dashboards-other.yaml
- dashboards-software.yaml
- dashboards-storage.yaml
- dashboards-unifi.yaml
- dashboards-programming.yaml

patches:
  - patch: |-
      apiVersion: grafana.integreatly.org/v1beta1
      kind: Grafana
      metadata:
        name: grafana
      spec:
        config:
          server:
            root_url: https://grafana.h.g4v.dev
        httpRoute:
          spec:
            hostnames:
              - grafana.h.g4v.dev
