apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: mariadb-operator-crds
    version: 25.10.3
    repo: https://helm.mariadb.com/mariadb-operator
    releaseName: mariadb-operator-crds
  - name: mariadb-operator
    version: 25.10.3
    repo: https://helm.mariadb.com/mariadb-operator
    valuesFile: values.yaml
    releaseName: mariadb-operator
