apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-operator

helmCharts:
  - name: mariadb-operator-crds
    version: 25.10.4
    repo: https://helm.mariadb.com/mariadb-operator
    releaseName: mariadb-operator-crds
  - name: mariadb-operator
    version: 25.10.4
    repo: https://helm.mariadb.com/mariadb-operator
    valuesFile: operator-values.yaml
    releaseName: mariadb-operator
  - name: mariadb-cluster
    version: 25.10.4
    repo: https://helm.mariadb.com/mariadb-operator
    valuesFile: cluster-values.yaml
    releaseName: mariadb-cluster

resources:
  - ./secret.enc.yaml
