# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/library/common/values.schema.json
controllers:
  main:
    replicas: 1
    containers:
      mindustry:
        image:
          repository: ghcr.io/usa-reddragon/mindustry
          tag: v146@sha256:79fb944f8e5f414418d5ac1dcd8745e1d46e480ddf3331cf0f9e437b30fca360
        env:
          TZ: America/Vancouver
          MINDUSTRY_ANTI_SPAM: "true"
          MINDUSTRY_AUTO_PAUSE: "true"
          MINDUSTRY_DEBUG: "true"
          MINDUSTRY_DESC: "Halkeye's mindustry server"
          MINDUSTRY_ENABLE_VOTEKICK: "true"
          MINDUSTRY_LOGGING: "true"
          MINDUSTRY_NAME: halkeye
          MINDUSTRY_SHOW_CONNECT_MESSAGES: "true"
          MINDUSTRY_START_COMMANDS: "host Archipelago"
          MINDUSTRY_STRICT: "true"
          MINDUSTRY_WHITELIST: "true"
        # probes:
        #   liveness:
        #     enabled: true
        #   readiness:
        #     enabled: true
        #   startup:
        #     enabled: true
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            memory: 1Gi
            cpu: 10m
    pod:
      securityContext:
        runAsUser: 1026
        runAsGroup: 100
        runAsNonRoot: true
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
service:
  main:
    controller: main
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-name: 'dok8s-mindustry'
      external-dns.alpha.kubernetes.io/hostname: mindustry.halkeye.net
      external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    ports:
      game-tcp:
        port: 6567
        primary: true
        protocol: TCP
      game-udp:
        port: 6567
        primary: false
        protocol: UDP
persistence:
  config:
    enabled: true
    suffix: config
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 10Gi
