apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: vaultwarden
spec:
    secretTemplates:
        - name: ENC[AES256_GCM,data:wJSrLiuvKMQwyVM=,iv:eX3E+jdcZVJ8IYWpp9akm7vIf4ZqB8s/Esxh+mpvS08=,tag:X5ldKn1a60SNM9AacNq07A==,type:str]
          stringData:
            PUSH_INSTALLATION_ID: ENC[AES256_GCM,data:hzWS4XvgeBqRvXuFyetAPTsb5zJaXzzImVY+hIpS5qqrVYEw,iv:khZrSKz3TOGeos1Aw+jFD1Tq2I0J+JRke/Wijoqq970=,tag:zs9q4ENo9QZoWysnBRgPow==,type:str]
            PUSH_INSTALLATION_KEY: ENC[AES256_GCM,data:2se0X/YOzEVxLW+3WgRqxyBTRp4=,iv:eG2gv/AR9pJs9LDjWLEzLviyko+7JKfH2CEpyCriIHg=,tag:mS1tU+2h4gjgGmBua4RvBA==,type:str]
            HIBP_API_KEY: ENC[AES256_GCM,data:BiHUssgPbajM6AGxI/ZdOUIlvDJWWT4JkAYN0g6nhJ8=,iv:ZJq8SzJWqAJ3I4A+A3c4adiKS9xG1LgeENzaOd9gZuc=,tag:/x1HVxqwsZvDSfS5yqMHcQ==,type:str]
            ADMIN_TOKEN: ENC[AES256_GCM,data:eevIrz9yN45faviD7neERDU0d7MzXWHD9NY+RwJWmk1hSge4C689VreRE6pK6Tft6wYCpVuHJNvOr2bXqqotfsMRN6E0FRop,iv:CmTb6YACyTnLRbono3/VqLKlS4axsqpknhsmxeEDNh0=,tag:n373G68TcNlYblc7lg0M4Q==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:oAdOcD/QkZeWIsi7RTCzw1+WjZseJI1aAcOqsN3vINrzrmJFeZT5LLL++1LDPPHmVcsrjmMQCznpfyUuFInDUlDEyfXHBTpzXotz88Uoph8i+Ll3otMxmrlYYG2MB3CMuf/u0h+wzXST+OokqfQ1MZfnh+CXY7p7lFs/OA==,iv:yYgCeJjrZtajiOU4ErHe8agAQw/9xpXV0OPr/5GvvR4=,tag:hKIOt1Y9jmxAlYc/bvt74w==,type:str]
            SMTP_HOST: ENC[AES256_GCM,data:SqrEWClaUGQVXQknQF7ZCg==,iv:zjNZvsIndZAZuAM2i600FFRhjr/gRXtL30Ww2rf7LPo=,tag:USlFHcR7wVQcFbrLL5kgZg==,type:str]
            SMTP_FROM: ENC[AES256_GCM,data:/jD/Kr+6lTyMZbNe9y5k7jw=,iv:Xxj6nciiPeFuqbTpleygLTp5MUBscxs0i+UpNtHVQg8=,tag:uXzz/WZZ7stTkmbInKiTzw==,type:str]
            SMTP_FROM_NAME: ENC[AES256_GCM,data:6tlbpwUeWwoE,iv:Rb+ilVUrvSlihcsAPvgK9DCWBsR9iUgDefOGl3EpFIQ=,tag:daDrtkO3E9BRkLhK5wQwsA==,type:str]
            SMTP_SECURITY: ENC[AES256_GCM,data:6nSMmBOhZHTB,iv:h91rJN3t/kbIEYKpORFTODzgdFW7ogFeca8BAyysyQg=,tag:5fNhg8QO3pKWEAI8bo0VOQ==,type:str]
            SMTP_USERNAME: ENC[AES256_GCM,data:79jpRUPzGxIRKZgwzBPWmMAk7BmKOts9,iv:zJvPW3G4L5YelEDH8an2F1BYp1f2Q+45XyZ379Hvr18=,tag:ltrlP2NmbFKb5BErNOiaRQ==,type:str]
            SMTP_PASSWORD: ENC[AES256_GCM,data:lGWEsFDzXdjQ+lpFJfuVykB6IXp1f6iQwMQbMDm9DPlO9ccB9qAwJxwRLpFMicgtawE=,iv:R3oPROwuDTzr3i97YkTyfGiShVyt4oE9jX7PhwWRFBs=,tag:fFEbsgTKmxU5Ht8sGFtkUQ==,type:str]
sops:
    age:
        - recipient: age1vqm5gwkmf38jsmt3j4lm3fdslausskaadtz360ewn0g7z2fchahqyr694v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHb3puekNhNGczNkdMa0cr
            eTdYV1J2bStvODdPY0xBZHU3UmZ3bTJMK0hBCno3OUpMaFNjWDJMMk9KR3JYUjRU
            NjFCRUFJUmxDNFhVZ1BCUFhtQTZIcHcKLS0tIFZZMmljS1NIUWNMcE1hTm5URm5m
            NFpMR2pvNkMvdlNPbVJIeHBIQ2RaUXMK6tTcLu3ivwbhhRRgZzJO4y8CtWmR0Gl6
            ztdgHhsxN+OV+5NBOTLnhtVeuiQKyoeQPyP26MOeCynNB9ec+K1HBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1aqel4n2xyfjmzjgey0mhxzhlmg2qd7xusjweku4w8u94dsq2gpmqye3wus
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQTdXbWxET3Azb3VBeDNI
            c0JkZGZoUlJrdTJsbmlIcEpjL3krUWIzUzN3Cjl2TTBiSUd6YmVKU2RJM1BCRGI2
            OWM5ZFo2TDdJRlE0aURtczVFNkVBTTgKLS0tIHpYS254dDk1QWRaV1NIU3oyVmtW
            b0FXUXBHWVNOL0NOZ1NEeVF6SStwVjQKvgEaCbGUdJFdhn5Ua6bEEjqaENEyBjNA
            +nkCkCrNnEpPvA1uFflfBnc4+8GTy41WJWWb3xY5hrk5KXp+ko+awQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y562y0u4k8y0eyq56s4g00ssd2cduamddcgfpu8fs7t00pfjss2s9nymt8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cytDSDY0VEdGVTh3dmtB
            dUFjNjFvNkU5UXg1WGRyUEMrZUxjRVM0NTJjCmtuUVVkRlVHalhzRTZnZnJZanl1
            SWQ5QkV2ZmhZUVhPa3JpbFJZbE5zT00KLS0tIFhPODlSZDMzWm9Kci9CQnZPZEty
            eGtSbXJ5dys1czRsRUdJeGhzYnp4RjgKvmn6kJU8Fc0FuPjTc1yomiqt+qL84YDL
            CUZdBe9qhzswGJWkQ16+bqACBDym98tyZ7PNJ/TOb5H3yH0YtuAovg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lv53trxftjem0a4hewf9h9dmp65cql6ycaj5q8kvfnfspccg747s6lxpxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUb24rUGxNbjhiK0wrVk4v
            bUs5VlJRQVRhYWFFUEdOa1BFblRwZ3Y1aFZnCmNsUXRiaHIzTFZ4dTNNVmRpU3hH
            VHZQZ2ZvZHhpS3R1di9nTkQ4UVlDQWcKLS0tIGY3Y0VDUVFtVndiWjdsOEZOSVVO
            ZEM3UHpnMndHbFcvTUpXYk9zdlNVVlkKLhrW34hgA6WOj4eXfuniu2lv4eM2EB12
            1xzyyRZgHHQoKs4a6sltgAlUzz8c/bAZiewa3wLepDm7yXLmhfeRjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ryqtmnakl6rc3z6qpqkhmw5pnsnzy2arwv7ecnh3ayf0za5pgtqft7lcn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIV1ZKbWpwN3o0T1pXN0dv
            TFRxcXFTekFlS3JCWU1NS01JSHJKaHAzOVdnCkhzcERXTG53RTlCS1RjOHJXeDF2
            cFg1T3p6L3haNlg0WTc1MkhnNk1JMTAKLS0tIFIyNFIyZ0g3VzZBQmZzam9nYW4z
            MWQ3ZkJ6SktOMFlmRFpKSHhubnYrNHMKzK9dk6jzeaRzsFZOd4MU7DBSYV3ZmJa2
            1gWIQbmyIRvO8ojXgvtliu3+7NC3prdbT0XL7hSn3L0iPytfWWnlKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFB0EXmaOVc61axVxDoWw1Y7JypG4LFFbS6+96dFY2VS
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IGt0aTNnZyB6Q2JS
            anhqMUJSS1A5cmRycS91YXJsM0p6NkdJTTNKSndBd2xhdXhheGprCjRoUzZNZHY1
            Zm5DbGV1MnFIendFdktWZ2JrNCtiVnY1ak1aQllTK2lqZTAKLS0tIHpTY3BPbksw
            aVZPa05HOWZqWnBncjIvWE9OMENVaHFlR3o3eEFZL1N5K2MK1EppYjLznFeKq8O3
            7DkPWcKydCYspEkafqHzgYcfrZMfX9AZetjepSD/ehydM+yGh6AgYbQ61dss2B17
            HGTzGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age179mmzgpy7ldyh3w6zld9vxjegxv80mkt6kffgg5enyquqrwnspkqv7sq7v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeEVVSStpY1cxRldvR3Jh
            cGwxTThZczdaUk50V2pWWnpIVHAxVmI4K1RFCisvdDhFeTBYdUFrZzJWTWJ3MWlP
            ZXhCTnJzeFo2bTdMZVF3WmNUdG4wUWcKLS0tIEVJS2E2aVROU0F6NWZESzZvWCtU
            UkZpY3RxZzZWNG56VzZmelNqaUV1bnMK6im3EL/4eIWQLqSrnvmOzPDQxRoyX/bL
            oij8yFaJ/1knVbHEJpCSDi7qnJRMHXxvAUt5Whc7UU85MOYqWcoBZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1k63d5ts2w8hfvdar7lan2qamhcgrjpfdv4um97q0ehjs553x4sysx08xcg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVzRnRmhzSW5OdVV5Q21v
            Qm94a3RSemQzb2lwUm5BSU05TjhOdTJyamhBCm5KVjhmVHdDVXNDL2kvOUlmNC9F
            U0F0Z0dtbjcwdk9YYkE4Ym5UMmZ6VmMKLS0tIEpITkcwUElWZkFiRG96MGVmVUFU
            Y1pnbEZNTjFaOTR0Sm90b1l4NHRsN2cK2JTn8VXV6aazpYx/2+xxWpfINMijKvGs
            uJm0OQa+guepEbRI6LH3NZnsfWQkD7bGGRHqPHQfh0Rf1Y31yKXyaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mkkltp58ptsvn5t7x8anr4hy20z0z6568nsljfa7tmwx07ug09aqf6rxe6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMXlGMFBJUjhvQUpFb2lu
            dG5QaXYzTW1XK00vOWxxa2Y3YlRCMXNUcGhNCnJCMU5BTExtR3BIckFxUHhVWGgr
            TmdzZW5tdlhNZUtuc0JVaWVkYS8zT1kKLS0tIHoyYjV1Vm8yZ1laSXRrWlZzWERL
            YlBETUZRK1JXK0hqS0VpMklHdFhBYk0KYmaX0AB9lePuwen5isF8Y1I9DHQVfDAf
            kUP9heMsFLYRxHtQqHA+5kaQnr4vdRlbfus6TxY5Kk4cc37apjQEmA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tfj0kfd2twsa655d5hx2afczlpcfzw7hapc07gr7ywnqq08qxdtsud2gfz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOGxTT2E4ZTQ3NjVrK1hD
            K3VFRjVUc1JqYTJETzRsOFFaYTZuK1ppMDNJClNzdUYwbTNYMjA0R3pOc0t0dFFm
            NEZSd2FiVE5pVUNkZUEzTzNaVk9WRkUKLS0tIDZwSHdrVmc2TVNiZFpGNElxbjUy
            aDJEVUlRdjMxZXBCY3A4QU5oRS85V2MK9YAfXWrDs+n70d8LKkzc/u4iKEotzTWZ
            fLTu5655nLcryYDc8BHrTgnEX7l304svtp0wHCdpdySH+OfEYQhepQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T03:44:55Z"
    mac: ENC[AES256_GCM,data:O6P8BMHca73dsmbfp7rSud7wHFO7TgBtVMnFrHf92MOptBgmfzXKiL+hu2riOp68Zu1yDmwnEJgmGdkMWesRzsZxb1G32p6VkEPYPLQF1iKpSXyG+4vMr5Hb0fGZK7CcO4b0JGIuGTuYSrVpTffjnItmb1pL7Dz7SKAVYk+S39A=,iv:5r1uAwcrur41iQG7LHDCxMmMPCxhTJcieO3qGIsyKC4=,tag:tc06nlniWblmizesM7jIUg==,type:str]
    encrypted_suffix: Templates
    version: 3.12.1
