apiVersion: v2
name: argocd
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: argo-cd
    version: 9.0.3
    repository: https://argoproj.github.io/argo-helm
maintainers:
  - name: halkeye
    url: https://www.gavinmogan.com
    email: helm@gavinmogan.com
