---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-g4v-tls
  namespace: cilium-secrets
spec:
  dnsNames:
    - '*.g4v.dev'
    - '*.h.g4v.dev'
  commonName: "*.g4v.dev"
  issuerRef:
    name: acme-letsencrypt-prod
    kind: ClusterIssuer
  secretName: wildcard-g4v-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-home-g4v-tls
  namespace: cilium-secrets
spec:
  dnsNames:
    - '*.g4v.dev'
    - '*.h.g4v.dev'
  commonName: "*.g4v.dev"
  issuerRef:
    name: acme-letsencrypt-prod
    kind: ClusterIssuer
  secretName: wildcard-home-g4v-tls
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: wildcard-do-g4v-tls
# spec:
#   dnsNames:
#     - '*.g4v.dev'
#     - '*.do.g4v.dev'
#   commonName: "*.g4v.dev"
#   issuerRef:
#     name: acme-letsencrypt-prod
#     kind: ClusterIssuer
#   secretName: wildcard-do-g4v-tls
