---
operator:
  replica: 1

hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    auto:
      enabled: true
      method: cronJob

clustermesh:
  apiserver:
    tls:
      auto:
        enabled: true
        method: cronJob

gatewayAPI:
  enabled: true

ingressController:
  enabled: true
  service:
    annotations:
      kube-vip.io/loadbalancerIPs: 172.16.10.212
      lbipam.cilium.io/ips: 172.16.10.212

# Increase rate limit when doing L2 announcements
# k8sClientRateLimit:
#   qps: 50
#   burst: 100

# Announce IPs from services' `.status.loadbalancer.ingress` field (automatically assigned by LB-IPAM).
l2announcements:
  enabled: true

# Announce manually assigned IPs from services' `.spec.externalIPs` field
externalIPs:
  enabled: true

loadBalancer:
  standalone: true

wellKnownIdentities:
  enabled: true
