debug = true
source_code = "https://github.com/realaravinth/libmedium"
cache = "/cache"

[server]
# The port at which you want authentication to listen to
# takes a number, choose from 1000-10000 if you dont know what you are doing
port = 7000
#IP address. Enter 0.0.0.0 to listen on all available addresses
ip= "0.0.0.0"
# enter your hostname, eg: example.com
domain = "g4v.dev"
allow_registration = false
proxy_has_tls = false
#workers = 2

